GLYLIB: src/deallocate_structures.c File Reference
deallocate_structures.c File Reference
#include "../inc/mylib.h"
#include "../inc/molecules.h"
Functions
void deallocateBondType (bond_type btp)
void deallocateMolbond (molbond mlb)
void deallocateConnectionTree (connection_tree con)
void deallocateBond (bond bnd)
void deallocateBondset (bondset bst)
void deallocateAtom (atom atm)
void deallocateResidue (residue res)
void deallocateMolecule (molecule mol)
Function Documentation
void deallocateAtom (atom atm)
Definition at line 61 of file deallocate_structures.c.
References atom::ch, atom::d, atom::D, atom::ensi, atom::i, atom::N, atom::nalt, atom::nch, atom::nd, atom::nensi, atom::ni, atom::nOD, atom::nvec, atom::OD, atom::sres, atom::T, atom::v, and atom::xa.
Referenced by deallocateResidue().
void deallocateBond (bond bnd)
Definition at line 40 of file deallocate_structures.c.
References bond::D, deallocateBondType(), and bond::typ.
Referenced by deallocateBondset().
void deallocateBondset (bondset bst)
Definition at line 49 of file deallocate_structures.c.
References bondset::b, deallocateBond(), and bondset::n.
void deallocateBondType (bond_type btp)
Definition at line 4 of file deallocate_structures.c.
References bond_type::desc, and bond_type::NT.
Referenced by deallocateBond(), and deallocateMolbond().
void deallocateConnectionTree (connection_tree con)
Definition at line 23 of file deallocate_structures.c.
References connection_tree::angle, connection_tree::chirot, connection_tree::distance, connection_tree::i, connection_tree::iso, connection_tree::ni, connection_tree::no, and connection_tree::o.
void deallocateMolbond (molbond mlb)
Definition at line 14 of file deallocate_structures.c.
References molbond::D, deallocateBondType(), and molbond::typ.
void deallocateMolecule (molecule mol)
Definition at line 147 of file deallocate_structures.c.
References molecule::d, molecule::D, deallocateResidue(), molecule::ensi, molecule::N, molecule::nd, molecule::nensi, molecule::nOD, molecule::noi, molecule::nr, molecule::nrc, molecule::OD, molecule::oi, molecule::r, and molecule::rc.
Referenced by load_dlg_mol().
void deallocateResidue (residue res)
Definition at line 97 of file deallocate_structures.c.
References residue::a, residue::d, residue::D, deallocateAtom(), residue::ensi, residue::i, residue::N, residue::na, residue::nd, residue::nensi, residue::ni, residue::nOD, residue::nrp, residue::OD, residue::rc, and residue::rp.
Referenced by deallocateMolecule().