GLYLIB: stats.h File Reference
stats.h File Reference
Classes
struct statsarray
struct meanvar
struct autocorr
Defines
#define GLYLIB_STATS
Functions
meanvar get_meanvar_array (statsarray S)
meanvar zero_meanvar ()
statsarray zero_statsarray ()
statsarray init_statsarray ()
autocorr zero_autocorr ()
autocorr init_autocorr ()
autocorr get_autocorr_est_array (statsarray S, meanvar M)
Detailed Description
Statistics utilities for glylib.
Begun in the spring of 2008 by BLFoley and modified by heaven only knows who since then.
Definition in file stats.h.
Define Documentation
#define GLYLIB_STATS
Definition at line 7 of file stats.h.
Function Documentation
autocorr get_autocorr_est_array (statsarray S, meanvar M)
Definition at line 8 of file get_autocorr_est_array.c.
References autocorr::a, statsarray::d, autocorr::k, meanvar::m, statsarray::n, meanvar::n, and meanvar::v.
{
autocorr A;
int k=0,j=0;
double *Dmu;
// initialize
A.k=M.n;
A.a=(double*)calloc((A.k),sizeof(double));
Dmu=(double*)calloc(S.n,sizeof(double));
for(j=0;j<S.n;j++){
        Dmu[j]=S.d[j]-M.m;
        }
for(k=0;k<(A.k);k++){
        for (j=0;j<(A.k-k);j++){
                A.a[k]+=Dmu[j+k]*Dmu[j];
                }
        A.a[k]/=((A.k-k)*M.v); // assumes whole population or biased sample
        }
return A;
}
meanvar get_meanvar_array (statsarray S)
Definition at line 9 of file get_meanvar_array.c.
References statsarray::d, meanvar::m, mywhine(), statsarray::n, meanvar::n, meanvar::s, statsarray::t, meanvar::t, meanvar::v, and zero_meanvar().
{
meanvar M;
int i=0;
// initialize
M=zero_meanvar();
M.t=S.t;
M.n=S.n;
for(i=0;i<S.n;i++){
        M.m+=S.d[i];
        M.v+=S.d[i]*S.d[i];
        }
M.v-=(M.m*M.m/(double)M.n);
M.m/=(double)M.n;
switch(M.t){ // calculate standard deviation
        case 's':
                  M.v/=(double)(M.n-1); // for sample / unbiased pop estimate
                  break;
        case 'p':
                  M.v/=(double)(M.n); // for whole population or biased sample
                  break;
        default: mywhine("unknown type for statistical set in get_meanvar_array");
        }
M.s=sqrt(M.v);
return M;
}
autocorr init_autocorr ()
Definition at line 37 of file zero_stat.c.
References autocorr::a, and autocorr::k.
                        { // for dynamic allocations
autocorr A;
A.k=0; // number in autocorrelation function
A.a=(double*)calloc(1,sizeof(double)); //the autocorr function
return A;
}
statsarray init_statsarray ()
Definition at line 24 of file zero_stat.c.
References statsarray::d, statsarray::n, and statsarray::t.
                            { // for dynamic allocations
statsarray S;
S.t='\0'; // type, population (p) or sample (s)
S.n=0; // number in sample/population
S.d=(double*)calloc(1,sizeof(double));
return S;
}
autocorr zero_autocorr ()
Definition at line 32 of file zero_stat.c.
References autocorr::k.
                        { // if only one allocation
autocorr A;
A.k=0; // number in autocorrelation function
return A;
}
meanvar zero_meanvar ()
Definition at line 7 of file zero_stat.c.
References meanvar::m, meanvar::n, meanvar::s, meanvar::t, and meanvar::v.
Referenced by get_meanvar_array().
                      {
meanvar M;
M.t='\0'; // type population (p) or sample (s)
M.n=0; // number of units in sample
M.m=0; // mean
M.v=0; // variance
M.s=0; // standard deviation
return M;
}
statsarray zero_statsarray ()
Definition at line 17 of file zero_stat.c.
References statsarray::n, and statsarray::t.
                            { // if only one allocation
statsarray S;
S.t='\0'; // type, population (p) or sample (s)
S.n=0; // number in sample/population
return S;
}