GLYLIB: inc/mylib.h File Reference
mylib.h File Reference
generic header file that loads utilities often needed by programmers
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
#include <time.h>
#include <malloc.h>
#include <general.h>
Defines
#define GLYLIB_HEAD
#define _GNU_SOURCE
Functions
void myusage (const char *USAGE)
Prints usage message and exits(1).
void mywhine (const char *whinetext)
Prints error message and exits(1).
void mywhineusage (const char *whinetext, const char *USAGE)
Prints error message and usage and exits(1).
FILE * myfopen (const char *Name, const char *option)
Opens a file with error checking.
FILE * myfreopen (const char *Name, const char *, FILE *option)
Like myfopen, but the freopen version.
void read_eek (const char *surprise, const char *FileDesc)
Complains (EEK!!!) if a file read fails.
void read_neek (const char *surprise, int line, int field)
Complains (EEK!!!) if a file read fails.
void read_fneek (const char *surprise, int line, int field, const char *FILENAME)
Complains (EEK!!!) if a file read fails.
int crdsnaps (const char *, const char *, int)
counts snapshots in a crd file
const char * mytime (const char *)
Gets the time in a nice format.
int sscan_file (FILE *F, const char *str)
Scans a file for instances of a string.
int cscan_file (FILE *F, char c)
Scans a file for instances of a character.
fileslurp slurp_file (fileset F)
Slurps in the contents of an entire file.
Detailed Description
generic header file that loads utilities often needed by programmers
The header files included here are basic C library headers (such as string.h). The other entries are declarations of functions that are expected to be commonly used by programmers using the library. For example, functions for opening files and writing error messages are declared in this file.
Definition in file mylib.h.
Define Documentation
#define _GNU_SOURCE
Some libraries that are often needed Defines that are often needed
Definition at line 30 of file mylib.h.
#define GLYLIB_HEAD
Definition at line 13 of file mylib.h.
Function Documentation
void myusage (const char * USAGE)
Prints usage message and exits(1).
Some general-use functions Prints usage.
Definition at line 7 of file myusage.c.
void mywhine (const char * whinetext)
Prints error message and exits(1).
Prints error message and exits(1). Prints the following:
"This program encountered the following error and will exit:
whinetext "
Definition at line 7 of file mywhine.c.
Referenced by assign_assembly_COM(), assign_ensemble_COM(), assign_molecule_COM(), assign_residue_COM(), crdsnaps(), find_molecules_molbond_array(), follow_find_molecule_amber_prmtop_bond_target(), get_alt_rms_mol(), get_alt_rms_res(), get_assembly_COM(), get_ensemble_COM(), get_geometric_center(), get_meanvar_array(), get_molecule_COM(), get_molecule_point_charge_dipole(), get_residue_COM(), load_atypes(), load_dlg_mol(), mytime(), normalize_molecule_vectors(), parse_amber_prmtop(), read_amber8_mden(), read_amber_prmtop_asis(), read_prep(), read_prepatom(), rotate_vector_to_Z_list(), rotate_vector_to_Z_M(), shift_molecule_atoms_by_vector_scale(), translate_to_COM(), translate_zero_to_coord_M(), and write_amber_prmtop().
void mywhineusage (const char * whinetext, const char * USAGE)
Prints error message and usage and exits(1).
Prints usage and an error message and exits(1). See mywhine for more information. Prints a usage statement after the whinetext
Definition at line 6 of file mywhineusage.c.