GLYLIB: vector_movements.c File Reference
vector_movements.c File Reference
#include <mylib.h>
#include <molecules.h>
Functions
void shift_molecule_atoms_by_vector_scale (molecule *m, int xs, int xt, int vr, double scale)
Function Documentation
void shift_molecule_atoms_by_vector_scale (molecule * m, int xs, int xt, int vr, double scale)
Definition at line 21 of file vector_movements.c.
References residue::a, add_coord(), mywhine(), residue::na, molecule::nr, molecule::r, scalarmult_coord(), vec_to_coord(), atom::x, and atom::xa.
{
int ta=0,tb,tuse=0,tsz=0,tbins=0;
coord_3D c;
// move atoms by scale * vector
if((xs==-1)&&(xt==-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        c=scalarmult_coord(vec_to_coord(m[0].r[ta].a[tb].v[vr]),scale);
                        m[0].r[ta].a[tb].x=add_coord(m[0].r[ta].a[tb].x,c);
                        }
                }
        }
if((xs!=-1)&&(xt==-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        tuse=malloc_usable_size(m[0].r[ta].a[tb].xa);
                        tsz=sizeof(coord_3D);
                        tbins=tuse/tsz;
                        if(tbins<(xs+1)){mywhine("memory issue: source coords (1) not allocated in shift_molecule_atoms_by_vector_scale");}
                        c=scalarmult_coord(vec_to_coord(m[0].r[ta].a[tb].v[vr]),scale);
                        m[0].r[ta].a[tb].x=add_coord(m[0].r[ta].a[tb].xa[xs],c);
                        }
                }
        }
if((xs==-1)&&(xt!=-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        tuse=malloc_usable_size(m[0].r[ta].a[tb].xa);
                        tsz=sizeof(coord_3D);
                        tbins=tuse/tsz;
                        if(tbins<(xt+1)){mywhine("memory issue: translated coords (1) not allocated in shift_molecule_atoms_by_vector_scale");}
                        c=scalarmult_coord(vec_to_coord(m[0].r[ta].a[tb].v[vr]),scale);
                        m[0].r[ta].a[tb].xa[xt]=add_coord(m[0].r[ta].a[tb].x,c);
                        }
                }
        }
if((xs!=-1)&&(xt!=-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        tuse=malloc_usable_size(m[0].r[ta].a[tb].xa);
                        tsz=sizeof(coord_3D);
                        tbins=tuse/tsz;
                        if(tbins<(xs+1)){mywhine("memory issue: source coords (2) not allocated in shift_molecule_atoms_by_vector_scale");}
                        if(tbins<(xt+1)){mywhine("memory issue: translated coords (2) not allocated in shift_molecule_atoms_by_vector_scale");}
                        c=scalarmult_coord(vec_to_coord(m[0].r[ta].a[tb].v[vr]),scale);
                        m[0].r[ta].a[tb].xa[xt]=add_coord(m[0].r[ta].a[tb].xa[xs],c);
                        }
                }
        }
return;
}