GLYLIB: src/get_COM.c File Reference
get_COM.c File Reference
#include <mylib.h>
#include <molecules.h>
Functions
coord_3D get_residue_COM (residue *r, atype *ATYPE, int xs)
coord_3D get_molecule_COM (molecule *m, atype *ATYPE, int xs)
coord_3D get_assembly_COM (assembly *a, atype *ATYPE, int xs)
coord_3D get_ensemble_COM (ensemble *e, atype *ATYPE, int xs)
Function Documentation
coord_3D get_assembly_COM (assembly * a, atype * ATYPE, int xs)
Definition at line 105 of file get_COM.c.
References residue::a, coord_3D::i, coord_3D::j, coord_3D::k, atype::m, assembly::m, assembly::mass, mywhine(), residue::na, assembly::nm, molecule::nr, molecule::r, atom::t, atom::x, and atom::xa.
coord_3D get_ensemble_COM (ensemble * e, atype * ATYPE, int xs)
Definition at line 167 of file get_COM.c.
References residue::a, coord_3D::i, coord_3D::j, coord_3D::k, atype::m, ensemble::m, ensemble::mass, mywhine(), residue::na, ensemble::nm, molecule::nr, molecule::r, atom::t, atom::x, and atom::xa.
coord_3D get_molecule_COM (molecule * m, atype * ATYPE, int xs)
Definition at line 55 of file get_COM.c.
References residue::a, coord_3D::i, coord_3D::j, coord_3D::k, molecule::m, atype::m, mywhine(), residue::na, molecule::nr, molecule::r, atom::t, atom::x, and atom::xa.
Referenced by get_molecule_point_charge_dipole().
coord_3D get_residue_COM (residue * r, atype * ATYPE, int xs)
Definition at line 11 of file get_COM.c.
References residue::a, coord_3D::i, coord_3D::j, coord_3D::k, residue::m, atype::m, mywhine(), residue::na, atom::t, atom::x, and atom::xa.