GLYLIB: dprint_X.c File Reference
dprint_X.c File Reference
#include <mylib.h>
#include <molecules.h>
Functions
void dprint_coord_3D (coord_3D *c)
void dprint_vectormag_3D (vectormag_3D *v)
void dprint_plane (plane *p)
void dprint_atype (atype *t, int i)
void dprint_bond (bond *b)
void dprint_atom (atom *a, int i)
void dprint_bondset (bondset *bs, int i)
void dprint_residue (residue *r, int i)
void dprint_molecule (molecule *m, int i)
Function Documentation
void dprint_atom (atom * a, int i)
Definition at line 60 of file dprint_X.c.
References dprint_bond(), dprint_coord_3D(), dprint_vectormag_3D(), atom::i, coord_3D::j, coord_3D::k, and atom::x.
{
        int pa=0,psz=0,puse=0,pbins=0;
        printf("atom \tn=%d ; N=>>%s<< ; t=%d ; nb=%d ; nalt=%d ; nvec=%d\n",a[0].n,a[0].N,\
                a[0].t,a[0].nb,a[0].nalt,a[0].nvec);
        printf("\tcoords x y z \t%20.12f \t%20.12f \t%20.12f\n",a[0].x.i,a[0].x.j,a[0].x.k);
        if(i>0){
                puse=malloc_usable_size(a[0].b);
                psz=sizeof(bond);
                pbins=puse/psz;
                printf("\t%d bonds have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<a[0].nb)&&(pa<pbins));pa++){
                        printf("\tbond set %d:  ",pa);
                        dprint_bond(&(a[0].b[pa]));
                        }
                puse=malloc_usable_size(a[0].xa);
                psz=sizeof(coord_3D);
                pbins=puse/psz;
                printf("\t%d alternate coordinates have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<a[0].nalt)&&(pa<pbins));pa++){
                        printf("\talt coord set %d:  ",pa);
                        dprint_coord_3D(&(a[0].xa[pa]));
                        }
                puse=malloc_usable_size(a[0].v);
                psz=sizeof(vectormag_3D);
                pbins=puse/psz;
                printf("\t%d vectors have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<a[0].nvec)&&(pa<pbins));pa++){
                        printf("\tset %d:  ",pa);
                        dprint_vectormag_3D(&(a[0].v[pa]));
                        }
                }
return;
}
void dprint_atype (atype * t, int i)
Definition at line 38 of file dprint_X.c.
{
        int pa=0,psz=0,puse=0,pbins=0;
        printf("atype \tn=%d ; N=>>%s<< ; NT=>>%s<< ; m=%20.12f ; nb=%d\n",t[0].n,t[0].N,t[0].NT,t[0].m,t[0].nb);
        printf("\tdesc=>>%s<<\n",t[0].desc);
        if(i>0){
                puse=malloc_usable_size(t[0].bo);
                psz=sizeof(double);
                pbins=puse/psz;
                printf("\t%d bond orders have been allocated: ",pbins);
                for(pa=0;((pa<i)&&(pa<t[0].nb)&&(pa<pbins));pa++){
                        printf("\t%20.12f",t[0].bo[pa]);
                        }
                printf("\n");
                }
return;
}
void dprint_bond (bond * b)
Definition at line 55 of file dprint_X.c.
Referenced by dprint_atom(), and dprint_bondset().
{
        printf("bond s t o \t%d \t%d \t%20.12f\n",b[0].s,b[0].t,b[0].o);
return;
}
void dprint_bondset (bondset * bs, int i)
Definition at line 94 of file dprint_X.c.
References dprint_bond().
{
        int pa=0,psz=0,puse=0,pbins=0;
        printf("bondset contains n=%d bonds\n",bs[0].n);
        if(i>0){
                puse=malloc_usable_size(bs[0].b);
                psz=sizeof(bond);
                pbins=puse/psz;
                printf("\t%d consecutive bonds have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<bs[0].n)&&(pa<pbins));pa++){
                        printf("\tconsec bonds set %d : \t",pa);
                        dprint_bond(&(bs[0].b[pa]));
                        }
                }
return;
}
void dprint_coord_3D (coord_3D * c)
Definition at line 23 of file dprint_X.c.
Referenced by dprint_atom(), dprint_residue(), and rotate_vector_to_Z_M().
{
        printf("coord i j k \t%20.12f \t%20.12f \t%20.12f\n",c[0].i,c[0].j,c[0].k);
return;
}
void dprint_molecule (molecule * m, int i)
Definition at line 160 of file dprint_X.c.
References dprint_residue().
{
        int pa=0,psz=0,puse=0,pbins=0;
        printf("molecule \ti=%d ; N=>>%s<< ; nr=%d \n",m[0].i,m[0].N,m[0].nr);
        if(i>0){
                puse=malloc_usable_size(m[0].r);
                psz=sizeof(residue);
                pbins=puse/psz;
                printf("\t%d residues have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<m[0].nr)&&(pa<pbins));pa++){
                        printf("\t\tset %d\n",pa);
                        dprint_residue(&(m[0].r[pa]),i);
                        }
                }
return;
}
void dprint_plane (plane * p)
Definition at line 33 of file dprint_X.c.
Referenced by dprint_residue().
{
        printf("plane A B C D \t%20.12f \t%20.12f \t%20.12f \t%20.12f\n",p[0].A,p[0].B,p[0].C,p[0].D);
return;
}
void dprint_residue (residue * r, int i)
Definition at line 110 of file dprint_X.c.
References dprint_atom(), dprint_bondset(), dprint_coord_3D(), and dprint_plane().
Referenced by dprint_molecule().
{
        int pa=0,psz=0,puse=0,pbins=0;
        printf("residue \tn=%d ; N=>>%s<< ; na=%d ; nbs=%d ; nr=%d \n",r[0].n,r[0].N,\
                r[0].na,r[0].nbs,r[0].nr);
        if(i>0){
                puse=malloc_usable_size(r[0].a);
                psz=sizeof(atom);
                pbins=puse/psz;
                //printf("usable return is %d, size is %d, bins is %d\n",puse,psz,pbins);
                printf("\t%d atoms have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<r[0].na)&&(pa<pbins));pa++){
                        printf("\tatom set %d\n",pa);
                        dprint_atom(&(r[0].a[pa]),i);
                        }
                puse=malloc_usable_size(r[0].bs);
                psz=sizeof(bondset);
                pbins=puse/psz;
                printf("\t%d consecutive, linear bonds have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<r[0].nbs)&&(pa<pbins));pa++){
                        printf("\tconsec. lin, bondset set %d\n",pa);
                        dprint_bondset(&(r[0].bs[pa]),i);
                        }
                puse=malloc_usable_size(r[0].rbs);
                psz=sizeof(bondset);
                pbins=puse/psz;
                printf("\t%d consecutive ring bonds have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<r[0].nrbs)&&(pa<pbins));pa++){
                        printf("\tconsec. ring bondset set %d\n",pa);
                        dprint_bondset(&(r[0].rbs[pa]),i);
                        }
                puse=malloc_usable_size(r[0].rc);
                psz=sizeof(coord_3D);
                pbins=puse/psz;
                printf("\t%d ring center coordinates have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<r[0].nrc)&&(pa<pbins));pa++){
                        printf("\tconsec ring coords set %d:  ",pa);
                        dprint_coord_3D(&(r[0].rc[pa]));
                        }
                puse=malloc_usable_size(r[0].rp);
                psz=sizeof(plane);
                pbins=puse/psz;
                printf("\t%d ring plane equations have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<r[0].nrp)&&(pa<pbins));pa++){
                        printf("\tring plane set %d:  ",pa);
                        dprint_plane(&(r[0].rp[pa]));
                        }
                }
return;
}
void dprint_vectormag_3D (vectormag_3D * v)
Definition at line 28 of file dprint_X.c.
{
        printf("vectormag i j k d \t%20.12f \t%20.12f \t%20.12f \t%20.12f\n",v[0].i,v[0].j,v[0].k,v[0].d);
return;
}