GLYLIB: src/normalize_vec.c File Reference
normalize_vec.c File Reference
#include <mylib.h>
#include <molecules.h>
Functions
vectormag_3D normalize_vec (vectormag_3D v)
Function Documentation
vectormag_3D normalize_vec (vectormag_3D v)
Definition at line 7 of file normalize_vec.c.
References vectormag_3D::d, vectormag_3D::i, vectormag_3D::j, and vectormag_3D::k.
Referenced by normalize_molecule_vectors(), rotate_vector_to_Z_list(), and rotate_vector_to_Z_M().