GLYLIB: src/find_molecules.c File Reference
find_molecules.c File Reference
#include "AMBER/amber_prmtop.h"
Classes
struct tempintset
Functions
void follow_find_molecule_amber_prmtop_bond_target (molbond *MB, molindex *AT, tempintset *SI, tempintset *TI, int i, int mN)
void find_molecules_molbond_array (int nMB, molbond *MB, int NATOM, molindex *AT)
Function Documentation
void find_molecules_molbond_array (int nMB, molbond * MB, int NATOM, molindex * AT)
Definition at line 37 of file find_molecules.c.
References follow_find_molecule_amber_prmtop_bond_target(), molbond::i, molindex::i, tempintset::i, molindex::m, mywhine(), tempintset::n, molbond::s, and molbond::t.
Referenced by parse_amber_prmtop().
void follow_find_molecule_amber_prmtop_bond_target (molbond * MB, molindex * AT, tempintset * SI, tempintset * TI, int i, int mN)
Definition at line 123 of file find_molecules.c.
References molindex::i, tempintset::i, molbond::i, molindex::m, mywhine(), tempintset::n, molbond::s, and molbond::t.
Referenced by find_molecules_molbond_array().