GLYLIB: inc/AMBER/read_prep.h File Reference
read_prep.h File Reference
Classes
struct ambermprepinfo
struct amberrprepinfo
struct amberaprepinfo
Defines
#define GLYLIB_AMBER_PREP_HEADERS
Functions
void read_prep (molecule *M, fileset F, types *TYP)
residue read_prepres (fileset F, types *TYP)
atom read_prepatom (const char *line, types *TYP)
Detailed Description
Header file for function read_prep that reads the contents of a prep file into an existing molecule structure
begun on 20071120 by BLFoley
These are loaded in the source
include <mylib.h>
include <molecules.h>
include <general.h>
See also AMBER documentation for prep file entry information
Definition in file read_prep.h.
Define Documentation
#define GLYLIB_AMBER_PREP_HEADERS
Definition at line 15 of file read_prep.h.
Function Documentation
void read_prep (molecule * M, fileset F, types * TYP)
Definition at line 41 of file read_prep.c.
References fileset::F, ambermprepinfo::FN, line, myfreopen(), mywhine(), fileset::N, ambermprepinfo::NAMDBF, molecule::nr, molecule::nVP, molecule::r, read_prepres(), and molecule::VP.
atom read_prepatom (const char * line, types * TYP)
Definition at line 235 of file read_prep.c.
References amberaprepinfo::I, amberaprepinfo::IGRAPH, amberaprepinfo::ISYMBL, amberaprepinfo::ITREE, mywhine(), atom::n, atom::N, types::na, atom::nVP, atom::t, atom::T, and atom::VP.
Referenced by read_prepres().
residue read_prepres (fileset F, types * TYP)
Definition at line 97 of file read_prep.c.
References types::a, residue::a, residue::bs, residue::COM, residue::D, residue::d, fileset::F, residue::i, amberrprepinfo::IFIXC, amberrprepinfo::INTX, amberrprepinfo::IOMIT, amberrprepinfo::IOPR, amberrprepinfo::IPOS, amberrprepinfo::ISYMDU, amberrprepinfo::KFORM, line, atype::m, residue::m, fileset::N, residue::N, residue::n, residue::na, amberrprepinfo::NAMF, amberrprepinfo::NAMRES, residue::nbs, residue::nd, residue::ni, amberrprepinfo::nIOPR, residue::nVP, read_eek(), read_prepatom(), llcharset::T, atom::t, amberrprepinfo::TITLE, residue::VP, and zero_coord().
Referenced by read_prep().