GLYLIB: inc/AMBER/amber_prmtop.h File Reference
amber_prmtop.h File Reference
#include <mylib.h>
#include <general.h>
#include <molecules.h>
#include <declarations.h>
#include <AMBER/amber_prmtop_structs.h>
Defines
#define GLYLIB_AMBER_PRMTOP_HEADER
Functions
void amber_prmtop_init (amber_prmtop *P)
void read_amber_prmtop_asis (fileset F, amber_prmtop *P)
assembly parse_amber_prmtop (amber_prmtop *P)
void find_molecules_molbond_array (int nMB, molbond *MB, int NATOM, molindex *AT)
assembly load_amber_prmtop (fileset F)
Detailed Description
Header file for functions that read amber prmtop files into the GLYLIB structures
begun on 20080622 by BLFoley
Definition in file amber_prmtop.h.
Define Documentation
#define GLYLIB_AMBER_PRMTOP_HEADER
Definition at line 8 of file amber_prmtop.h.
Function Documentation
void amber_prmtop_init (amber_prmtop * P)
Definition at line 7 of file amber_prmtop_init.c.
References AMBER_PRMTOP_FLAGS, AMBER_PRMTOP_FORMATS, amber_prmtop::FLAGS, amber_prmtop::FORMATS, amber_prmtop::IFBOX, amber_prmtop::IFCAP, amber_prmtop::IFPERT, amber_prmtop::MBONA, amber_prmtop::MBPER, amber_prmtop::MDPER, amber_prmtop::MGPER, amber_prmtop::MPHIA, amber_prmtop::MTHETA, amber_prmtop::NATOM, amber_prmtop::NATYP, amber_prmtop::NBONA, amber_prmtop::NBONH, amber_prmtop::NBPER, amber_prmtop::NDPER, amber_prmtop::nES, amber_prmtop::NEXT, amber_prmtop::nFF, amber_prmtop::NGPER, amber_prmtop::NHPARM, amber_prmtop::NMXRS, amber_prmtop::NPARM, amber_prmtop::NPHB, amber_prmtop::NPHIA, amber_prmtop::NPHIH, amber_prmtop::NPTRA, amber_prmtop::NRES, amber_prmtop::nS, amber_prmtop::nSS, amber_prmtop::NTHETA, amber_prmtop::NTHETH, amber_prmtop::NTYPES, amber_prmtop::NUMANG, and amber_prmtop::NUMBND.
Referenced by load_amber_prmtop().
void find_molecules_molbond_array (int nMB, molbond * MB, int NATOM, molindex * AT)
Definition at line 37 of file find_molecules.c.
References follow_find_molecule_amber_prmtop_bond_target(), molbond::i, molindex::i, tempintset::i, molindex::m, mywhine(), tempintset::n, molbond::s, and molbond::t.
Referenced by parse_amber_prmtop().
assembly load_amber_prmtop (fileset F)
Definition at line 7 of file load_amber_prmtop.c.
References amber_prmtop_init(), parse_amber_prmtop(), and read_amber_prmtop_asis().
assembly parse_amber_prmtop (amber_prmtop * P)
Drop the contents of the original file in the void pointer space
< One for the "boxang" and the other for the x,y,z values
< Just an angle ("BETA" in the amber file specs)
< 3-D coordinate
< Record value of BETA
< Record BOX X
< Record BOX Y
< Record BOX Z
Definition at line 8 of file parse_amber_prmtop.c.
References molecule::a, torsion_index::a, angle_index::a, molindex::a, residue::a, assembly::a, amber_prmtop::ALMPER, amber_prmtop::AMASS, assembly::ANG, parameter_set::ANT, amber_prmtop::ASOL, parameter_set::AT, amber_prmtop::ATPOL, amber_prmtop::ATPOL1, torsion_index::b, angle_index::b, assembly::b, amber_prmtop::BETA, amber_prmtop::BOX, assembly::BOX, amber_prmtop::BSOL, parameter_set::BT, torsion_index::c, angle_index::c, boxinfo::C, boxinfo::CD, amber_prmtop::CGPER, atom::ch, amber_prmtop::CHRG, amber_prmtop::CN1, amber_prmtop::CN2, amber_prmtop::CUTCAP, molecule::D, torsion_index::d, torsion_index::D, angle_index::D, molbond::D, amber_prmtop_section::D, assembly::D, coord_nD::D, fileset::F, find_molecules_molbond_array(), amber_prmtop_section::FORMAT, boxinfo::GTYPE, amber_prmtop::HBCUT, parameter_set::HBT, torsion_index::i, angle_index::i, molbond::i, molindex::i, amber_prmtop::IAC, amber_prmtop::IACPER, amber_prmtop::IAPER, amber_prmtop::IB, amber_prmtop::IBH, amber_prmtop::IBPER, amber_prmtop::ICB, amber_prmtop::ICBH, amber_prmtop::ICBPER, amber_prmtop::ICO, amber_prmtop::ICP, amber_prmtop::ICPH, amber_prmtop::ICPPER, amber_prmtop::ICT, amber_prmtop::ICTH, amber_prmtop::ICTPER, amber_prmtop::IGRAPH, amber_prmtop::IGRPER, amber_prmtop::IP, amber_prmtop::IPH, amber_prmtop::IPPER, amber_prmtop::IPRES, amber_prmtop::IPTER, amber_prmtop::IPTRES, amber_prmtop::IRES, amber_prmtop::IROTAT, amber_prmtop_section::is_standard, amber_prmtop::ISMPER, amber_prmtop::ISYMBL, amber_prmtop::IT, amber_prmtop::ITH, amber_prmtop::ITITL, amber_prmtop::ITREE, amber_prmtop::JB, amber_prmtop::JBH, amber_prmtop::JBPER, amber_prmtop::JOIN, amber_prmtop::JP, amber_prmtop::JPH, amber_prmtop::JPPER, amber_prmtop::JT, amber_prmtop::JTH, amber_prmtop::JTPER, torsion_type::k, angle_type::k, bond_type::k, amber_prmtop::KP, amber_prmtop::KPH, amber_prmtop::KPPER, amber_prmtop::KT, amber_prmtop::KTH, amber_prmtop::KTPER, angle_type::l, bond_type::l, amber_prmtop::LABRES, bond_type::LJ10_1012, bond_type::LJ12_1012, bond_type::LJ12_612, bond_type::LJ6_612, amber_prmtop::LP, amber_prmtop::LPH, amber_prmtop::LPPER, assembly::m, molindex::m, atom::mb, amber_prmtop::MBONA, amber_prmtop::MPHIA, amber_prmtop::MTHETA, myfopen(), mywhine(), molecule::N, atype::N, amber_prmtop_section::N, torsion_type::N, torsion_type::n, atom::n, residue::n, residue::N, atom::N, molecule::na, residue::na, assembly::na, assembly::nANG, parameter_set::nANT, parameter_set::nAT, amber_prmtop::NATCAP, amber_prmtop::NATEX, amber_prmtop::NATOM, assembly::nb, amber_prmtop::NBONA, amber_prmtop::NBONH, assembly::nBOX, parameter_set::nBT, parameter_set::NBT, boxinfo::nC, boxinfo::nCD, atom::nch, coord_nD::nD, parameter_set::nHBT, assembly::nm, atom::nmb, parameter_set::nNBT, amber_prmtop::NPHB, amber_prmtop::NPHIA, amber_prmtop::NPHIH, assembly::nPRM, amber_prmtop::NPTRA, molecule::nr, assembly::nr, amber_prmtop::NRES, amber_prmtop::nS, amber_prmtop::NSP, amber_prmtop::NSPM, amber_prmtop::NSPSOL, bond_type::NT, amber_prmtop_section::nt, amber_prmtop::NTHETA, amber_prmtop::NTHETH, assembly::nTOR, parameter_set::nTRT, amber_prmtop::NTYPES, amber_prmtop::NUMANG, amber_prmtop::NUMBND, amber_prmtop::NUMEX, assembly::nVP, torsion_type::P, amber_prmtop::PHASE, amber_prmtop::PK, amber_prmtop::PN, amber_prmtop::POINTERS, assembly::PRM, molecule::r, molindex::r, assembly::r, amber_prmtop::REQ, amber_prmtop::RK, molbond::s, amber_prmtop::S, amber_prmtop::SOLTY, boxinfo::STYPE, molbond::t, atom::t, amber_prmtop::TEQ, amber_prmtop::TK, assembly::TOR, parameter_set::TRT, amber_prmtop::VERSION, assembly::VP, amber_prmtop::XCAP, amber_prmtop::YCAP, and amber_prmtop::ZCAP.
Referenced by load_amber_prmtop().
void read_amber_prmtop_asis (fileset F, amber_prmtop * P)
Definition at line 17 of file read_amber_prmtop.c.
References amber_prmtop_section::D, fileset::F, amber_prmtop::FN, amber_prmtop_section::FORMAT, line, myfopen(), mywhine(), amber_prmtop_section::N, fileset::N, amber_prmtop_section::nc, amber_prmtop::nS, amber_prmtop_section::nt, read_eek(), read_fneek(), amber_prmtop::S, amber_prmtop::SN, and amber_prmtop::VERSION.
Referenced by load_amber_prmtop().