GLYLIB: src/mywhine.c File Reference
mywhine.c File Reference
#include <mylib.h>
Functions
void mywhine (const char *msg)
Prints error message and exits(1).
Function Documentation
void mywhine (const char * whinetext)
Prints error message and exits(1).
Prints error message and exits(1). Prints the following:
"This program encountered the following error and will exit:
whinetext "
Definition at line 7 of file mywhine.c.
Referenced by add_to_moiety_selection(), add_trajcrds_to_prmtop_assembly(), assign_assembly_COM(), assign_ensemble_COM(), assign_molecule_COM(), assign_residue_COM(), crdsnaps(), find_molecules_molbond_array(), follow_find_molecule_amber_prmtop_bond_target(), get_alt_rms_mol(), get_alt_rms_res(), get_assembly_COM(), get_char_string(), get_ensemble_COM(), get_float_string(), get_geometric_center(), get_meanvar_array(), get_moiety_selection_assembly(), get_molecule_COM(), get_molecule_point_charge_dipole(), get_residue_COM(), gly_get_current_working_directory(), load_atypes(), load_dlg_mol(), mytime(), normalize_molecule_vectors(), parse_amber_prmtop(), read_amber8_mden(), read_amber_prmtop_asis(), read_prep(), read_prepatom(), rotate_vector_to_Z_list(), rotate_vector_to_Z_M(), shift_molecule_atoms_by_vector_scale(), translate_to_COM(), translate_zero_to_coord_M(), and write_amber_prmtop().