GLYLIB: add_coord.c File Reference
add_coord.c File Reference
#include <mylib.h>
#include <molecules.h>
Functions
coord_3D add_coord (coord_3D ca, coord_3D cb)
coord_3D subtract_coord (coord_3D ca, coord_3D cb)
coord_3D scalarmult_coord (coord_3D ca, double cb)
Function Documentation
coord_3D add_coord (coord_3D ca, coord_3D cb)
Definition at line 7 of file add_coord.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
Referenced by shift_molecule_atoms_by_vector_scale().
{
coord_3D nc;
nc.i=ca.i+cb.i;
nc.j=ca.j+cb.j;
nc.k=ca.k+cb.k;
return nc;
}
coord_3D scalarmult_coord (coord_3D ca, double cb)
Definition at line 29 of file add_coord.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
Referenced by shift_molecule_atoms_by_vector_scale().
{
coord_3D nc;
nc.i=ca.i*cb;
nc.j=ca.j*cb;
nc.k=ca.k*cb;
return nc;
}
coord_3D subtract_coord (coord_3D ca, coord_3D cb)
Definition at line 18 of file add_coord.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
Referenced by get_alt_rms_mol(), get_alt_rms_res(), and translate_zero_to_coord_M().
{
coord_3D nc;
nc.i=ca.i-cb.i;
nc.j=ca.j-cb.j;
nc.k=ca.k-cb.k;
return nc;
}