GLYLIB: load_pdb.h File Reference
load_pdb.h File Reference
#include <molecules.h>
#include <structures.h>
#include <mylib.h>
Defines
#define GLYLIB_LOADPDB
#define LA (int)0
Functions
assembly * load_pdb (char *file_name)
int howManyMolecules ()
assembly * getAssembly ()
int findTotalResidue (int start)
int endOfMol (linedef *line)
int isAtom (linedef *line)
void getResInfo (residue *res, int start)
void init_struct ()
linetype get_type (char *)
void pdb_def ()
void rwm_line (int)
Variables
FILE * IN
FILE * OUT
FILE * OUTC
linedef line [1]
int WARN
int SILENT
char froot [200]
char suf [6]
char sufc [20]
char ACT
int INWC
int DATE
int UNCUT
int UNx
int UNy
int UNz
int LASTRES
int LASTOKX
int LASTOKY
int LASTOKZ
float UNCTOL
float CRYX
float CRYY
float CRYZ
float LASTX
float LASTY
float LASTZ
int DEBUG
Detailed Description
Header file for loading pdb files into structures.
Begun at some point in the past by BLFoley and possibly modified at some point by Mike Tessier. See also the load_pdb functions.
Definition in file load_pdb.h.
Define Documentation
#define GLYLIB_LOADPDB
Definition at line 7 of file load_pdb.h.
#define LA (int)0
Definition at line 11 of file load_pdb.h.
Function Documentation
int endOfMol (linedef * line)
Definition at line 140 of file load_pdb.c.
Referenced by findTotalResidue(), getAssembly(), getResInfo(), and howManyMolecules().
{
  if(((*line).a == 4 && (*line).b == 2)||
     ((*line).a == 2 && ((*line).b == 9||(*line).b == 3)))
    return 1;
  else
    return 0;
}
int findTotalResidue (int start)
Definition at line 119 of file load_pdb.c.
References endOfMol(), INWC, isAtom(), and ln.
Referenced by getAssembly().
{
  int ret = 0;int i = start;int curRes = 0;int thisRes;
  char* temp;
  while(endOfMol((ln+i)) == 0 && i != INWC)
  {
    if(isAtom((ln+i)) == 1)
    {
      temp  = (*(ln+i)).f[8].c;
      sscanf(temp,"%d",&thisRes);
      if(thisRes != curRes)
      {
        ret ++;
        curRes = thisRes;
      }
    }
   i++;
  }
  return ret;
}
linetype get_type (char *)
Definition at line 6 of file get_type.c.
References linetype::a, linetype::b, and DEBUG.
Referenced by rwm_line().
{
int gta=0;
char gt_other[20];
linetype gtlt;
if(DEBUG>=1){printf("gca is >>>%s<<<\n", gca);}
gtlt.a=-1;
gtlt.b=-1;
/* CLASS 0 */
if(strcmp(gca,"CRYST1")==0){
        gtlt.a=0;
        gtlt.b=0;
        }  /* CRYST1 */
if(strcmp(gca,"END   ")==0){
        gtlt.a=0;
        gtlt.b=1;
        }  /* END */
if(strcmp(gca,"HEADER")==0){
        gtlt.a=0;
        gtlt.b=2;
        }  /* HEADER */
if(strcmp(gca,"MASTER")==0){
        gtlt.a=0;
        gtlt.b=3;
        }  /* MASTER */
/* In case ORIGXn and SCALEn are taken literally: */
if(strcmp(gca,"ORIGXn")==0){
        gtlt.a=0;
        gtlt.b=4;
        }  /* ORIGXn */
if(strcmp(gca,"SCALEn")==0){
        gtlt.a=0;
        gtlt.b=5;
        }  /* SCALEn */
/* In case ORIGXn and SCALEn are given n=variable: */
for(gta=0;gta<5;gta++){
        gt_other[gta]=gca[gta];
        }
gt_other[5]='\0';
if(strcmp(gt_other,"ORIGX")==0){
        gtlt.a=0;
        gtlt.b=4;
        }  /* ORIGXn */
if(strcmp(gt_other,"SCALE")==0){
        gtlt.a=0;
        gtlt.b=5;
        }  /* ORIGXn */
/* CLASS 1 */
if(strcmp(gca,"AUTHOR")==0){
        gtlt.a=1;
        gtlt.b=0;
        }  /* AUTHOR */
if(strcmp(gca,"CAVEAT")==0){
        gtlt.a=1;
        gtlt.b=1;
        }  /* CAVEAT */
if(strcmp(gca,"COMPND")==0){
        gtlt.a=1;
        gtlt.b=2;
        }  /* COMPND */
if(strcmp(gca,"EXPDTA")==0){
        gtlt.a=1;
        gtlt.b=3;
        }  /* EXPDTA */
if(strcmp(gca,"KEYWDS")==0){
        gtlt.a=1;
        gtlt.b=4;
        }  /* KEYWDS */
if(strcmp(gca,"OBSLTE")==0){
        gtlt.a=1;
        gtlt.b=5;
        }  /* OBSLTE */
if(strcmp(gca,"SOURCE")==0){
        gtlt.a=1;
        gtlt.b=6;
        }  /* SOURCE */
if(strcmp(gca,"SPRSDE")==0){
        gtlt.a=1;
        gtlt.b=7;
        }  /* SPRSDE */
if(strcmp(gca,"TITLE ")==0){
        gtlt.a=1;
        gtlt.b=8;
        }  /* TITLE */
/* CLASS 2 */
if(strcmp(gca,"ANISOU")==0){
        gtlt.a=2;
        gtlt.b=0;
        }  /* ANISOU */
if(strcmp(gca,"ATOM  ")==0){
        gtlt.a=2;
        gtlt.b=1;
        }  /* ATOM */
if(strcmp(gca,"CISPEP")==0){
        gtlt.a=2;
        gtlt.b=2;
        }  /* CISPEP */
if(strcmp(gca,"CONECT")==0){
        gtlt.a=2;
        gtlt.b=3;
        }  /* CONECT */
if(strcmp(gca,"DBREF ")==0){
        gtlt.a=2;
        gtlt.b=4;
        }  /* DBREF */
if(strcmp(gca,"HELIX ")==0){
        gtlt.a=2;
        gtlt.b=5;
        }  /* HELIX */
if(strcmp(gca,"HET   ")==0){
        gtlt.a=2;
        gtlt.b=6;
        }  /* HET */
if(strcmp(gca,"HETSYN")==0){
        gtlt.a=2;
        gtlt.b=7;
        }  /* HETSYN */
if(strcmp(gca,"HYDBND")==0){
        gtlt.a=2;
        gtlt.b=8;
        }  /* HYDBND */
if(strcmp(gca,"LINK  ")==0){
        gtlt.a=2;
        gtlt.b=9;
        }  /* LINK */
if(strcmp(gca,"MODRES")==0){
        gtlt.a=2;
        gtlt.b=10;
        }  /* MODRES */
if(strcmp(gca,"MTRIXn")==0){
        gtlt.a=2;
        gtlt.b=11;
        }  /* MTRIXn */
if(strcmp(gca,"REVDAT")==0){
        gtlt.a=2;
        gtlt.b=12;
        }  /* REVDAT */
if(strcmp(gca,"SEQADV")==0){
        gtlt.a=2;
        gtlt.b=13;
        }  /* SEQADV */
if(strcmp(gca,"SEQRES")==0){
        gtlt.a=2;
        gtlt.b=14;
        }  /* SEQRES */
if(strcmp(gca,"SHEET ")==0){
        gtlt.a=2;
        gtlt.b=15;
        }  /* SHEET */
if(strcmp(gca,"SIGATM")==0){
        gtlt.a=2;
        gtlt.b=16;
        }  /* SIGATM */
if(strcmp(gca,"SIGUIJ")==0){
        gtlt.a=2;
        gtlt.b=17;
        }  /* SIGUIJ */
if(strcmp(gca,"SITE  ")==0){
        gtlt.a=2;
        gtlt.b=18;
        }  /* SITE */
if(strcmp(gca,"SLTBRG")==0){
        gtlt.a=2;
        gtlt.b=19;
        }  /* SLTBRG */
if(strcmp(gca,"SSBOND")==0){
        gtlt.a=2;
        gtlt.b=20;
        }  /* SSBOND */
if(strcmp(gca,"TURN  ")==0){
        gtlt.a=2;
        gtlt.b=21;
        }  /* TURN */
if(strcmp(gca,"TVECT ")==0){
        gtlt.a=2;
        gtlt.b=22;
        }  /* TVECT */
/* CLASS 3 */
if(strcmp(gca,"FORMUL")==0){
        gtlt.a=3;
        gtlt.b=0;
        }  /* FORMUL */
if(strcmp(gca,"HETATM")==0){
        gtlt.a=3;
        gtlt.b=1;
        }  /* HETATM */
if(strcmp(gca,"HETNAM")==0){
        gtlt.a=3;
        gtlt.b=2;
        }  /* HETNAM */
/* CLASS 4 */
if(strcmp(gca,"ENDMDL")==0){
        gtlt.a=4;
        gtlt.b=0;
        }  /* ENDMDL */
if(strcmp(gca,"MODEL ")==0){
        gtlt.a=4;
        gtlt.b=1;
        }  /* MODEL */
if(strcmp(gca,"TER   ")==0){
        gtlt.a=4;
        gtlt.b=2;
        }  /* TER */
/* CLASS 5 */
if(strcmp(gca,"JRNL  ")==0){
        gtlt.a=5;
        gtlt.b=0;
        }  /* JRNL */
if(strcmp(gca,"REMARK")==0){
        gtlt.a=5;
        gtlt.b=1;
        }  /* REMARK */
if(gtlt.a<0){
printf("String type of %s found in file.  This type not supported.\n",gca);
printf("    [feel free to write it in!]\n");
printf("Deleting entry from output file.\n");
gtlt.a=-1;
gtlt.b=-1;
}
return gtlt;
}
assembly* getAssembly ()
Definition at line 48 of file load_pdb.c.
References residue::a, endOfMol(), findTotalResidue(), getResInfo(), howManyMolecules(), INWC, isAtom(), ln, and molecule::nr.
Referenced by load_pdb().
{
  int molNum = howManyMolecules();
  int i = 0;int j = 0;int k = 0;int l = 0;int atom_num;double x,y,z;
  char* temp;char name[6] = ""; char* atmName = name;
  assembly* asmbl = (assembly*) malloc (1 * sizeof(assembly));
  (*asmbl).nm = molNum;
  molecule* mol = (molecule*) malloc (molNum * sizeof(molecule));
  (*asmbl).m = (molecule**)calloc(1,sizeof(molecule*));//added by MNT on 20080806
  (*asmbl).m[0] = mol; // changed by BLF on 20080622 -- might need revisiting
  molecule* curMol; residue* curRes;// residue* res;
  atom* curAtm;// atom* atm;
  //Get all the information for the first molecule
  curMol = (mol+j);
  (*curMol).nr = findTotalResidue(i);
  (*curMol).r = (residue*) malloc ((*curMol).nr*sizeof(residue));
  getResInfo((*curMol).r,i);
  curRes = ((*curMol).r+k);
  (*curRes).a = (atom*) malloc ((*curRes).na*sizeof(atom));
  curAtm = ((*curRes).a+l);
  for(i = 0; i < INWC; i++)
  {
    //If it is a TER, LINK, or CONECT card
    if(endOfMol((ln+i)) == 1)
    {
      j++;
      curMol = (mol+j);
      (*curMol).nr = findTotalResidue(i+1);
      (*curMol).r = (residue*) malloc ((*curMol).nr*sizeof(residue));
      getResInfo((*curMol).r,i+1);
      curRes = ((*curMol).r+k);
      k = 0;l = 0;
      (*curRes).a = (atom*) malloc ((*curRes).na*sizeof(atom));
      curAtm = ((*curRes).a+l);
    }
    else if(isAtom((ln+i)) == 1)
    {
      if(l == (*curRes).na)
      {
       k++;l = 0;
       curRes = ((*curMol).r+k);
       (*curRes).a = (atom*) malloc ((*curRes).na*sizeof(atom));
       //curAtm = ((*curRes).a+l);
      }
      curAtm = ((*curRes).a+l);
      //Getting the atom #
      temp  = (*(ln+i)).f[1].c;
      sscanf(temp,"%d",&atom_num);
      //Getting the atom name
      temp  = (*(ln+i)).f[3].c;
      sscanf(temp,"%s",atmName);
      //Getting the X coordinate
      temp  = (*(ln+i)).f[11].c;
      sscanf(temp,"%lf",&x);
      //Getting the Y coordinate
      temp  = (*(ln+i)).f[12].c;
      sscanf(temp,"%lf",&y);
      //Getting the Z coordinate
      temp  = (*(ln+i)).f[13].c;
      sscanf(temp,"%lf",&z);
      (*curAtm).n = atom_num;//set the atom #
      (*curAtm).N = strdup(atmName);//set the atom name
      //set the atom's coordinates
      (*curAtm).x.i = x; (*curAtm).x.j = y; (*curAtm).x.k = z;
      l++;
    }
  }
 return asmbl;
}
void getResInfo (residue * res, int start)
Definition at line 156 of file load_pdb.c.
References endOfMol(), INWC, isAtom(), and ln.
Referenced by getAssembly().
{
  int atmTot = 0;int resNum,thisRes;int i = start;int j = 0;
  char name [10];char* temp;char* resName = name;
  while(isAtom(ln+i) == 0 && i < INWC)
   i++;
  //Getting the residue name
  temp = (*(ln+i)).f[5].c;
  sscanf(temp,"%s",resName);
  (*(res+j)).N = strdup(resName);
  //Getting the residue #
  temp  = (*(ln+i)).f[8].c;
  sscanf(temp,"%d",&thisRes);
  resNum = thisRes;
  (*(res+j)).n = resNum;
  i = start;
  while(endOfMol((ln+i)) == 0 && i != INWC)
  {
    if(isAtom((ln+i)) == 1)
    {
      temp  = (*(ln+i)).f[8].c;
      sscanf(temp,"%d",&thisRes);
      if(thisRes != resNum)
      {
        //Setting the total # of atoms on the old res
        resNum = thisRes;
        (*(res+j)).na = atmTot;
        atmTot = 0; j++;
        //Getting the residue name for the new res
        temp = (*(ln+i)).f[5].c;
        sscanf(temp,"%s",resName);
        (*(res+j)).N = strdup(resName);
        //Setting the residue # on the new res
        (*(res+j)).n = resNum;
      }
      else
        atmTot++;
    }
   i++;
  }
 (*(res+j)).na = atmTot;
}
int howManyMolecules ()
Definition at line 36 of file load_pdb.c.
References endOfMol(), INWC, isAtom(), and ln.
Referenced by getAssembly(), and load_pdb().
{
 int i; int counter = 0;
 for(i = 0; i < INWC; i++)
  if(endOfMol((ln+i)) == 1)//If it is a TER, LINK, or CONECT card
   counter++;
 if(counter == 0 || isAtom(ln+(INWC-1)) == 1)
  counter ++;
 return counter;
}
void init_struct ()
Definition at line 11 of file init_struct.c.
References linefield::c, DEBUG, linedef::f, linedef::ignore, IN, INWC, ln, linedef::m, linedef::n, and pdb_def().
Referenced by load_pdb().
                  {
int isa=0, isb=0,isc=0, iswc=0;
char istst='\0';
if(DEBUG>=0){printf("init_struct at 1 \n");}
// Get number of lines in input file
rewind(IN);
while(istst!=EOF){
        istst=fgetc(IN);
        if(istst=='\n') iswc++;
        }
INWC=iswc;
/* Allocate array for line info */
ln=(linedef*)calloc(iswc,sizeof(linedef));
for(isa=0;isa<iswc;isa++){
        ln[isa].m='\0';
        ln[isa].n=isa+1;
        ln[isa].ignore=1;
        for(isb=0;isb<25;isb++){
                for(isc=0;isc<81;isc++){
                        ln[isa].f[isb].c[isc]='\0';
                        }
                }
        }
if(DEBUG>=0){printf("init_struct at  9\n");}
/* Read in values defining line and field types */
pdb_def();
if(DEBUG>=0){printf("init_struct at 12 \n");}
return;
}
int isAtom (linedef * line)
Definition at line 149 of file load_pdb.c.
Referenced by findTotalResidue(), getAssembly(), getResInfo(), and howManyMolecules().
{
  if(((*line).a == 2 || (*line).a == 3) && (*line).b == 1)
    return 1;
  else
    return 0;
}
assembly* load_pdb (char * file_name)
Definition at line 4 of file load_pdb.c.
References ACT, CRYX, CRYY, CRYZ, DATE, DEBUG, getAssembly(), howManyMolecules(), IN, init_struct(), INWC, LASTOKX, LASTOKY, LASTOKZ, LASTRES, LASTX, LASTY, LASTZ, ln, myfopen(), rwm_line(), SILENT, suf, sufc, UNCTOL, UNCUT, UNx, UNy, UNz, and WARN.
{
  char* temp;
  WARN=1;SILENT=1;INWC=0;DATE=0;UNCUT=1;UNx=1;UNy=1;UNz=1;
  temp = suf; strcpy(temp,".pdb");
  temp = sufc; strcpy(temp,"_change.txt"); ACT='0';
  DEBUG=-1;LASTRES=-1;LASTOKX=0;LASTOKY=0;LASTOKZ=0;
  UNCTOL=0;CRYX=0;CRYY=0;CRYZ=0;LASTX=0;LASTY=0;LASTZ=0;
  //int resNum;
  int ma;
  //molecule* mol;
  assembly* asmbl;
  IN = myfopen(file_name, "r");
 /*scans pdb file for number of lines
  allocates memory for line structures
  initializes structures that contain line formats*/
  init_struct();
  rewind(IN);
  //Read in lines to ln structure
  printf("Reading in %s...\n",file_name);
  for(ma=0;ma<INWC;ma++){
  if(DEBUG>=1){printf("made it to here main line loop %d ...\n", ma);}
        rwm_line(ma+1);
        }
  //Determine the number of molecules in the pdb
  printf("There are %d molecule(s)\n",howManyMolecules());
  asmbl = getAssembly();
  printf("PDB Information Successfully Read.\n");
  free(ln);
  return asmbl;
}
void pdb_def ()
Definition at line 34 of file pdb_def.c.
References pdb_line::b, pdb_line_info::c, pdb_line_info::f, pdb_a, and pdb_line_info::t.
Referenced by init_struct().
              {
/* Class for this set of Records : Once Only -- Class 0
 *      Class 0 records should occur, at most, once in any pdb file */
/* RECORD Name : CRYST1 */
strcpy(pdb_a[0].b[0].typ,"CRYST1");  /*  */
pdb_a[0].b[0].f         =       11;  /*  */
pdb_a[0].b[0].c[0]      =       6;  /* RECORD NAME */
pdb_a[0].b[0].c[1]      =       9;  /* a */
pdb_a[0].b[0].c[2]      =       9;  /* b */
pdb_a[0].b[0].c[3]      =       9;  /* c */
pdb_a[0].b[0].c[4]      =       7;  /* alpha */
pdb_a[0].b[0].c[5]      =       7;  /* beta */
pdb_a[0].b[0].c[6]      =       7;  /* gamma */
pdb_a[0].b[0].c[7]      =       1;  /* N/A */
pdb_a[0].b[0].c[8]      =       11;  /* sGroup */
pdb_a[0].b[0].c[9]      =       4;  /* z */
pdb_a[0].b[0].c[10]     =       10;  /* N/A */
pdb_a[0].b[0].t[0]      =       's';  /* RECORD NAME */
pdb_a[0].b[0].t[1]      =       'f';  /* a */
pdb_a[0].b[0].t[2]      =       'f';  /* b */
pdb_a[0].b[0].t[3]      =       'f';  /* c */
pdb_a[0].b[0].t[4]      =       'f';  /* alpha */
pdb_a[0].b[0].t[5]      =       'f';  /* beta */
pdb_a[0].b[0].t[6]      =       'f';  /* gamma */
pdb_a[0].b[0].t[7]      =       's';  /* N/A */
pdb_a[0].b[0].t[8]      =       's';  /* sGroup */
pdb_a[0].b[0].t[9]      =       'i';  /* z */
pdb_a[0].b[0].t[10]     =       's';  /* N/A */
/* RECORD Name : END */
strcpy(pdb_a[0].b[1].typ,"END");  /*  */
pdb_a[0].b[1].f         =       2;  /*  */
pdb_a[0].b[1].c[0]      =       6;  /* RECORD NAME */
pdb_a[0].b[1].c[1]      =       74;  /* N/A */
pdb_a[0].b[1].t[0]      =       's';  /* RECORD NAME */
pdb_a[0].b[1].t[1]      =       's';  /* N/A */
/* RECORD Name : HEADER */
strcpy(pdb_a[0].b[2].typ,"HEADER");  /*  */
pdb_a[0].b[2].f         =       7;  /*  */
pdb_a[0].b[2].c[0]      =       6;  /* RECORD NAME */
pdb_a[0].b[2].c[1]      =       4;  /* N/A */
pdb_a[0].b[2].c[2]      =       40;  /* classification   */
pdb_a[0].b[2].c[3]      =       9;  /* depDate          */
pdb_a[0].b[2].c[4]      =       3;  /* N/A */
pdb_a[0].b[2].c[5]      =       4;  /* idCode           */
pdb_a[0].b[2].c[6]      =       14;  /* N/A */
pdb_a[0].b[2].t[0]      =       's';  /* RECORD NAME */
pdb_a[0].b[2].t[1]      =       's';  /* N/A */
pdb_a[0].b[2].t[2]      =       's';  /* classification   */
pdb_a[0].b[2].t[3]      =       's';  /* depDate          */
pdb_a[0].b[2].t[4]      =       's';  /* N/A */
pdb_a[0].b[2].t[5]      =       's';  /* idCode           */
pdb_a[0].b[2].t[6]      =       's';  /* N/A */
/* RECORD Name : MASTER */
strcpy(pdb_a[0].b[3].typ,"MASTER");  /*  */
pdb_a[0].b[3].f         =       15;  /*  */
pdb_a[0].b[3].c[0]      =       6;  /* RECORD NAME */
pdb_a[0].b[3].c[1]      =       4;  /* N/A */
pdb_a[0].b[3].c[2]      =       5;  /* numRemark      */
pdb_a[0].b[3].c[3]      =       5;  /* 0 */
pdb_a[0].b[3].c[4]      =       5;  /* numHet         */
pdb_a[0].b[3].c[5]      =       5;  /* numHelix       */
pdb_a[0].b[3].c[6]      =       5;  /* numSheet       */
pdb_a[0].b[3].c[7]      =       5;  /* numTurn        */
pdb_a[0].b[3].c[8]      =       5;  /* numSite        */
pdb_a[0].b[3].c[9]      =       5;  /* numXform       */
pdb_a[0].b[3].c[10]     =       5;  /* numCoord       */
pdb_a[0].b[3].c[11]     =       5;  /* numTer         */
pdb_a[0].b[3].c[12]     =       5;  /* numConect      */
pdb_a[0].b[3].c[13]     =       5;  /* numSeq         */
pdb_a[0].b[3].c[14]     =       10;  /* N/A */
pdb_a[0].b[3].t[0]      =       's';  /* RECORD NAME */
pdb_a[0].b[3].t[1]      =       's';  /* N/A */
pdb_a[0].b[3].t[2]      =       'i';  /* numRemark      */
pdb_a[0].b[3].t[3]      =       'i';  /* 0 */
pdb_a[0].b[3].t[4]      =       'i';  /* numHet         */
pdb_a[0].b[3].t[5]      =       'i';  /* numHelix       */
pdb_a[0].b[3].t[6]      =       'i';  /* numSheet       */
pdb_a[0].b[3].t[7]      =       'i';  /* numTurn        */
pdb_a[0].b[3].t[8]      =       'i';  /* numSite        */
pdb_a[0].b[3].t[9]      =       'i';  /* numXform       */
pdb_a[0].b[3].t[10]     =       'i';  /* numCoord       */
pdb_a[0].b[3].t[11]     =       'i';  /* numTer         */
pdb_a[0].b[3].t[12]     =       'i';  /* numConect      */
pdb_a[0].b[3].t[13]     =       'i';  /* numSeq         */
pdb_a[0].b[3].t[14]     =       's';  /* N/A */
/* RECORD Name : ORIGXn */
strcpy(pdb_a[0].b[4].typ,"ORIGXn");  /*  */
pdb_a[0].b[4].f         =       1;  /*  */
pdb_a[0].b[4].c[0]      =       80;  /* RECORD NAME */
pdb_a[0].b[4].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : SCALEn */
strcpy(pdb_a[0].b[5].typ,"SCALEn");  /*  */
pdb_a[0].b[5].f         =       1;  /*  */
pdb_a[0].b[5].c[0]      =       80;  /* RECORD NAME */
pdb_a[0].b[5].t[0]      =       's';  /* RECORD NAME */
/* Class 1:  Once - many line :  */
/* RECORD Name : AUTHOR */
strcpy(pdb_a[1].b[0].typ,"AUTHOR");  /*  */
pdb_a[1].b[0].f         =       1;  /*  */
pdb_a[1].b[0].c[0]      =       80;  /* RECORD NAME */
pdb_a[1].b[0].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : CAVEAT */
strcpy(pdb_a[1].b[1].typ,"CAVEAT");  /*  */
pdb_a[1].b[1].f         =       1;  /*  */
pdb_a[1].b[1].c[0]      =       80;  /* RECORD NAME */
pdb_a[1].b[1].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : COMPND */
strcpy(pdb_a[1].b[2].typ,"COMPND");  /*  */
pdb_a[1].b[2].f         =       1;  /*  */
pdb_a[1].b[2].c[0]      =       80;  /* RECORD NAME */
pdb_a[1].b[2].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : EXPDTA */
strcpy(pdb_a[1].b[3].typ,"EXPDTA");  /*  */
pdb_a[1].b[3].f         =       1;  /*  */
pdb_a[1].b[3].c[0]      =       80;  /* RECORD NAME */
pdb_a[1].b[3].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : KEYWDS */
strcpy(pdb_a[1].b[4].typ,"KEYWDS");  /*  */
pdb_a[1].b[4].f         =       1;  /*  */
pdb_a[1].b[4].c[0]      =       80;  /* RECORD NAME */
pdb_a[1].b[4].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : OBSLTE */
strcpy(pdb_a[1].b[5].typ,"OBSLTE");  /*  */
pdb_a[1].b[5].f         =       1;  /*  */
pdb_a[1].b[5].c[0]      =       80;  /* RECORD NAME */
pdb_a[1].b[5].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : SOURCE */
strcpy(pdb_a[1].b[6].typ,"SOURCE");  /*  */
pdb_a[1].b[6].f         =       1;  /*  */
pdb_a[1].b[6].c[0]      =       80;  /* RECORD NAME */
pdb_a[1].b[6].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : SPRSDE */
strcpy(pdb_a[1].b[7].typ,"SPRSDE");  /*  */
pdb_a[1].b[7].f         =       1;  /*  */
pdb_a[1].b[7].c[0]      =       80;  /* RECORD NAME */
pdb_a[1].b[7].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : TITLE */
strcpy(pdb_a[1].b[8].typ,"TITLE");  /*  */
pdb_a[1].b[8].f         =       5;  /*  */
pdb_a[1].b[8].c[0]      =       6;  /* RECORD NAME */
pdb_a[1].b[8].c[1]      =       2;  /* N/A */
pdb_a[1].b[8].c[2]      =       2;  /* continuation    */
pdb_a[1].b[8].c[3]      =       60;  /* title           */
pdb_a[1].b[8].c[4]      =       10;  /* N/A */
pdb_a[1].b[8].t[0]      =       's';  /* RECORD NAME */
pdb_a[1].b[8].t[1]      =       's';  /* N/A */
pdb_a[1].b[8].t[2]      =       's';  /* continuation    */
pdb_a[1].b[8].t[3]      =       's';  /* title           */
pdb_a[1].b[8].t[4]      =       's';  /* N/A */
/* Class 2:  Many - One line each :  */
/* RECORD Name : ANISOU */
strcpy(pdb_a[2].b[0].typ,"ANISOU");  /*  */
pdb_a[2].b[0].f         =       1;  /*  */
pdb_a[2].b[0].c[0]      =       80;  /* RECORD NAME */
pdb_a[2].b[0].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : ATOM */
strcpy(pdb_a[2].b[1].typ,"ATOM");  /*  */
pdb_a[2].b[1].f         =       20;  /*  */
pdb_a[2].b[1].c[0]      =       6;  /* RECORD NAME */
pdb_a[2].b[1].c[1]      =       5;  /* serial         */
pdb_a[2].b[1].c[2]      =       1;  /* N/A */
pdb_a[2].b[1].c[3]      =       4;  /* name           */
pdb_a[2].b[1].c[4]      =       1;  /* altLoc         */
pdb_a[2].b[1].c[5]      =       3;  /* resName        */
pdb_a[2].b[1].c[6]      =       1;  /* N/A */
pdb_a[2].b[1].c[7]      =       1;  /* chainID        */
pdb_a[2].b[1].c[8]      =       4;  /* resSeq         */
pdb_a[2].b[1].c[9]      =       1;  /* iCode          */
pdb_a[2].b[1].c[10]     =       3;  /* N/A */
pdb_a[2].b[1].c[11]     =       8;  /* x */
pdb_a[2].b[1].c[12]     =       8;  /* y */
pdb_a[2].b[1].c[13]     =       8;  /* z */
pdb_a[2].b[1].c[14]     =       6;  /* occupancy      */
pdb_a[2].b[1].c[15]     =       6;  /* tempFactor     */
pdb_a[2].b[1].c[16]     =       6;  /* N/A */
pdb_a[2].b[1].c[17]     =       4;  /* segID          */
pdb_a[2].b[1].c[18]     =       2;  /* element        */
pdb_a[2].b[1].c[19]     =       2;  /* charge         */
pdb_a[2].b[1].t[0]      =       's';  /* RECORD NAME */
pdb_a[2].b[1].t[1]      =       'i';  /* serial         */
pdb_a[2].b[1].t[2]      =       's';  /* N/A */
pdb_a[2].b[1].t[3]      =       's';  /* name           */
pdb_a[2].b[1].t[4]      =       'c';  /* altLoc         */
pdb_a[2].b[1].t[5]      =       's';  /* resName        */
pdb_a[2].b[1].t[6]      =       's';  /* N/A */
pdb_a[2].b[1].t[7]      =       'c';  /* chainID        */
pdb_a[2].b[1].t[8]      =       'i';  /* resSeq         */
pdb_a[2].b[1].t[9]      =       'c';  /* iCode          */
pdb_a[2].b[1].t[10]     =       's';  /* N/A */
pdb_a[2].b[1].t[11]     =       'f';  /* x */
pdb_a[2].b[1].t[12]     =       'f';  /* y */
pdb_a[2].b[1].t[13]     =       'f';  /* z */
pdb_a[2].b[1].t[14]     =       'f';  /* occupancy      */
pdb_a[2].b[1].t[15]     =       'f';  /* tempFactor     */
pdb_a[2].b[1].t[16]     =       's';  /* N/A */
pdb_a[2].b[1].t[17]     =       's';  /* segID          */
pdb_a[2].b[1].t[18]     =       's';  /* element        */
pdb_a[2].b[1].t[19]     =       's';  /* charge         */
/* RECORD Name : CISPEP */
strcpy(pdb_a[2].b[2].typ,"CISPEP");  /*  */
pdb_a[2].b[2].f         =       1;  /*  */
pdb_a[2].b[2].c[0]      =       80;  /* RECORD NAME */
pdb_a[2].b[2].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : CONECT */
strcpy(pdb_a[2].b[3].typ,"CONECT");  /*  */
pdb_a[2].b[3].f         =       1;  /*  */
pdb_a[2].b[3].c[0]      =       80;  /* RECORD NAME */
pdb_a[2].b[3].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : DBREF */
strcpy(pdb_a[2].b[4].typ,"DBREF");  /*  */
pdb_a[2].b[4].f         =       1;  /*  */
pdb_a[2].b[4].c[0]      =       80;  /* RECORD NAME */
pdb_a[2].b[4].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : HELIX */
strcpy(pdb_a[2].b[5].typ,"HELIX");  /*  */
pdb_a[2].b[5].f         =       1;  /*  */
pdb_a[2].b[5].c[0]      =       80;  /* RECORD NAME */
pdb_a[2].b[5].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : HET */
strcpy(pdb_a[2].b[6].typ,"HET");  /*  */
pdb_a[2].b[6].f         =       12;  /*  */
pdb_a[2].b[6].c[0]      =       6;  /* RECORD NAME */
pdb_a[2].b[6].c[1]      =       1;  /* N/A */
pdb_a[2].b[6].c[2]      =       3;  /* hetID          */
pdb_a[2].b[6].c[3]      =       2;  /* N/A */
pdb_a[2].b[6].c[4]      =       1;  /* ChainID        */
pdb_a[2].b[6].c[5]      =       4;  /* seqNum         */
pdb_a[2].b[6].c[6]      =       1;  /* iCode          */
pdb_a[2].b[6].c[7]      =       2;  /* N/A */
pdb_a[2].b[6].c[8]      =       5;  /* numHetAtoms    */
pdb_a[2].b[6].c[9]      =       5;  /* N/A */
pdb_a[2].b[6].c[10]     =       40;  /* text           */
pdb_a[2].b[6].c[11]     =       10;  /* N/A */
pdb_a[2].b[6].t[0]      =       's';  /* RECORD NAME */
pdb_a[2].b[6].t[1]      =       's';  /* N/A */
pdb_a[2].b[6].t[2]      =       's';  /* hetID          */
pdb_a[2].b[6].t[3]      =       's';  /* N/A */
pdb_a[2].b[6].t[4]      =       'c';  /* ChainID        */
pdb_a[2].b[6].t[5]      =       'i';  /* seqNum         */
pdb_a[2].b[6].t[6]      =       'c';  /* iCode          */
pdb_a[2].b[6].t[7]      =       's';  /* N/A */
pdb_a[2].b[6].t[8]      =       'i';  /* numHetAtoms    */
pdb_a[2].b[6].t[9]      =       's';  /* N/A */
pdb_a[2].b[6].t[10]     =       's';  /* text           */
pdb_a[2].b[6].t[11]     =       's';  /* N/A */
/* RECORD Name : HETSYN */
strcpy(pdb_a[2].b[7].typ,"HETSYN");  /*  */
pdb_a[2].b[7].f         =       8;  /*  */
pdb_a[2].b[7].c[0]      =       6;  /* RECORD NAME */
pdb_a[2].b[7].c[1]      =       2;  /* N/A */
pdb_a[2].b[7].c[2]      =       2;  /* continuation    */
pdb_a[2].b[7].c[3]      =       1;  /* N/A */
pdb_a[2].b[7].c[4]      =       3;  /* hetID           */
pdb_a[2].b[7].c[5]      =       1;  /* N/A */
pdb_a[2].b[7].c[6]      =       55;  /* hetSynonyms     */
pdb_a[2].b[7].c[7]      =       10;  /* N/A */
pdb_a[2].b[7].t[0]      =       's';  /* RECORD NAME */
pdb_a[2].b[7].t[1]      =       's';  /* N/A */
pdb_a[2].b[7].t[2]      =       's';  /* continuation    */
pdb_a[2].b[7].t[3]      =       's';  /* N/A */
pdb_a[2].b[7].t[4]      =       's';  /* hetID           */
pdb_a[2].b[7].t[5]      =       's';  /* N/A */
pdb_a[2].b[7].t[6]      =       's';  /* hetSynonyms     */
pdb_a[2].b[7].t[7]      =       's';  /* N/A */
/* RECORD Name : HYDBND */
strcpy(pdb_a[2].b[8].typ,"HYDBND");  /*  */
pdb_a[2].b[8].f         =       1;  /*  */
pdb_a[2].b[8].c[0]      =       80;  /* RECORD NAME */
pdb_a[2].b[8].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : LINK */
strcpy(pdb_a[2].b[9].typ,"LINK");  /*  */
pdb_a[2].b[9].f         =       1;  /*  */
pdb_a[2].b[9].c[0]      =       80;  /* RECORD NAME */
pdb_a[2].b[9].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : MODRES */
strcpy(pdb_a[2].b[10].typ,"MODRES");  /*  */
pdb_a[2].b[10].f        =       1;  /*  */
pdb_a[2].b[10].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[10].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : MTRIXn */
strcpy(pdb_a[2].b[11].typ,"MTRIXn");  /*  */
pdb_a[2].b[11].f        =       1;  /*  */
pdb_a[2].b[11].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[11].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : REVDAT */
strcpy(pdb_a[2].b[12].typ,"REVDAT");  /*  */
pdb_a[2].b[12].f        =       1;  /*  */
pdb_a[2].b[12].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[12].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : SEQADV */
strcpy(pdb_a[2].b[13].typ,"SEQADV");  /*  */
pdb_a[2].b[13].f        =       1;  /*  */
pdb_a[2].b[13].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[13].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : SEQRES */
strcpy(pdb_a[2].b[14].typ,"SEQRES");  /*  */
pdb_a[2].b[14].f        =       1;  /*  */
pdb_a[2].b[14].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[14].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : SHEET */
strcpy(pdb_a[2].b[15].typ,"SHEET");  /*  */
pdb_a[2].b[15].f        =       1;  /*  */
pdb_a[2].b[15].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[15].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : SIGATM */
strcpy(pdb_a[2].b[16].typ,"SIGATM");  /*  */
pdb_a[2].b[16].f        =       1;  /*  */
pdb_a[2].b[16].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[16].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : SIGUIJ */
strcpy(pdb_a[2].b[17].typ,"SIGUIJ");  /*  */
pdb_a[2].b[17].f        =       1;  /*  */
pdb_a[2].b[17].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[17].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : SITE */
strcpy(pdb_a[2].b[18].typ,"SITE");  /*  */
pdb_a[2].b[18].f        =       1;  /*  */
pdb_a[2].b[18].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[18].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : SLTBRG */
strcpy(pdb_a[2].b[19].typ,"SLTBRG");  /*  */
pdb_a[2].b[19].f        =       1;  /*  */
pdb_a[2].b[19].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[19].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : SSBOND */
strcpy(pdb_a[2].b[20].typ,"SSBOND");  /*  */
pdb_a[2].b[20].f        =       1;  /*  */
pdb_a[2].b[20].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[20].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : TURN */
strcpy(pdb_a[2].b[21].typ,"TURN");  /*  */
pdb_a[2].b[21].f        =       1;  /*  */
pdb_a[2].b[21].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[21].t[0]     =       's';  /* RECORD NAME */
/* RECORD Name : TVECT */
strcpy(pdb_a[2].b[22].typ,"TVECT");  /*  */
pdb_a[2].b[22].f        =       1;  /*  */
pdb_a[2].b[22].c[0]     =       80;  /* RECORD NAME */
pdb_a[2].b[22].t[0]     =       's';  /* RECORD NAME */
/* Class 3:  Many -- many line each :  */
/* RECORD Name : FORMUL */
strcpy(pdb_a[3].b[0].typ,"FORMUL");  /*  */
pdb_a[3].b[0].f         =       1;  /*  */
pdb_a[3].b[0].c[0]      =       80;  /* RECORD NAME */
pdb_a[3].b[0].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : HETATM */
strcpy(pdb_a[3].b[1].typ,"HETATM");  /*  */
pdb_a[3].b[1].f         =       20;  /*  */
pdb_a[3].b[1].c[0]      =       6;  /* RECORD NAME */
pdb_a[3].b[1].c[1]      =       5;  /* serial         */
pdb_a[3].b[1].c[2]      =       1;  /* N/A */
pdb_a[3].b[1].c[3]      =       4;  /* name           */
pdb_a[3].b[1].c[4]      =       1;  /* altLoc         */
pdb_a[3].b[1].c[5]      =       3;  /* resName        */
pdb_a[3].b[1].c[6]      =       1;  /* N/A */
pdb_a[3].b[1].c[7]      =       1;  /* chainID        */
pdb_a[3].b[1].c[8]      =       4;  /* resSeq         */
pdb_a[3].b[1].c[9]      =       1;  /* iCode          */
pdb_a[3].b[1].c[10]     =       3;  /* N/A */
pdb_a[3].b[1].c[11]     =       8;  /* x */
pdb_a[3].b[1].c[12]     =       8;  /* y */
pdb_a[3].b[1].c[13]     =       8;  /* z */
pdb_a[3].b[1].c[14]     =       6;  /* occupancy      */
pdb_a[3].b[1].c[15]     =       6;  /* tempFactor     */
pdb_a[3].b[1].c[16]     =       6;  /* N/A */
pdb_a[3].b[1].c[17]     =       4;  /* segID          */
pdb_a[3].b[1].c[18]     =       2;  /* element        */
pdb_a[3].b[1].c[19]     =       2;  /* charge         */
pdb_a[3].b[1].t[0]      =       's';  /* RECORD NAME */
pdb_a[3].b[1].t[1]      =       'i';  /* serial         */
pdb_a[3].b[1].t[2]      =       's';  /* N/A */
pdb_a[3].b[1].t[3]      =       's';  /* name           */
pdb_a[3].b[1].t[4]      =       'c';  /* altLoc         */
pdb_a[3].b[1].t[5]      =       's';  /* resName        */
pdb_a[3].b[1].t[6]      =       's';  /* N/A */
pdb_a[3].b[1].t[7]      =       'c';  /* chainID        */
pdb_a[3].b[1].t[8]      =       'i';  /* resSeq         */
pdb_a[3].b[1].t[9]      =       'c';  /* iCode          */
pdb_a[3].b[1].t[10]     =       's';  /* N/A */
pdb_a[3].b[1].t[11]     =       'f';  /* x */
pdb_a[3].b[1].t[12]     =       'f';  /* y */
pdb_a[3].b[1].t[13]     =       'f';  /* z */
pdb_a[3].b[1].t[14]     =       'f';  /* occupancy      */
pdb_a[3].b[1].t[15]     =       'f';  /* tempFactor     */
pdb_a[3].b[1].t[16]     =       's';  /* N/A */
pdb_a[3].b[1].t[17]     =       's';  /* segID          */
pdb_a[3].b[1].t[18]     =       's';  /* element        */
pdb_a[3].b[1].t[19]     =       's';  /* charge         */
/* RECORD Name : HETNAM */
strcpy(pdb_a[3].b[2].typ,"HETNAM");  /*  */
pdb_a[3].b[2].f         =       8;  /*  */
pdb_a[3].b[2].c[0]      =       6;  /* RECORD NAME */
pdb_a[3].b[2].c[1]      =       2;  /* N/A */
pdb_a[3].b[2].c[2]      =       2;  /* continuation    */
pdb_a[3].b[2].c[3]      =       1;  /* N/A */
pdb_a[3].b[2].c[4]      =       3;  /* hetID           */
pdb_a[3].b[2].c[5]      =       1;  /* N/A */
pdb_a[3].b[2].c[6]      =       55;  /* text            */
pdb_a[3].b[2].c[7]      =       10;  /* N/A */
pdb_a[3].b[2].t[0]      =       's';  /* RECORD NAME */
pdb_a[3].b[2].t[1]      =       's';  /* N/A */
pdb_a[3].b[2].t[2]      =       's';  /* continuation    */
pdb_a[3].b[2].t[3]      =       's';  /* N/A */
pdb_a[3].b[2].t[4]      =       's';  /* hetID           */
pdb_a[3].b[2].t[5]      =       's';  /* N/A */
pdb_a[3].b[2].t[6]      =       's';  /* text            */
pdb_a[3].b[2].t[7]      =       's';  /* N/A */
/* grouping lines :  */
/* RECORD Name : ENDMDL */
strcpy(pdb_a[4].b[0].typ,"ENDMDL");  /*  */
pdb_a[4].b[0].f         =       2;  /*  */
pdb_a[4].b[0].c[0]      =       6;  /* RECORD NAME */
pdb_a[4].b[0].c[1]      =       74;  /* N/A */
pdb_a[4].b[0].t[0]      =       's';  /* RECORD NAME */
pdb_a[4].b[0].t[1]      =       's';  /* N/A */
/* RECORD Name : MODEL */
strcpy(pdb_a[4].b[1].typ,"MODEL");  /*  */
pdb_a[4].b[1].f         =       4;  /*  */
pdb_a[4].b[1].c[0]      =       6;  /* RECORD NAME */
pdb_a[4].b[1].c[1]      =       4;  /* N/A */
pdb_a[4].b[1].c[2]      =       4;  /* serial         */
pdb_a[4].b[1].c[3]      =       66;  /* N/A */
pdb_a[4].b[1].t[0]      =       's';  /* RECORD NAME */
pdb_a[4].b[1].t[1]      =       's';  /* N/A */
pdb_a[4].b[1].t[2]      =       'i';  /* serial         */
pdb_a[4].b[1].t[3]      =       's';  /* N/A */
/* RECORD Name : TER */
strcpy(pdb_a[4].b[2].typ,"TER");  /*  */
pdb_a[4].b[2].f         =       9;  /*  */
pdb_a[4].b[2].c[0]      =       6;  /* RECORD NAME */
pdb_a[4].b[2].c[1]      =       5;  /* serial        */
pdb_a[4].b[2].c[2]      =       6;  /* N/A */
pdb_a[4].b[2].c[3]      =       3;  /* resName       */
pdb_a[4].b[2].c[4]      =       1;  /* N/A */
pdb_a[4].b[2].c[5]      =       1;  /* chainID       */
pdb_a[4].b[2].c[6]      =       4;  /* resSeq        */
pdb_a[4].b[2].c[7]      =       1;  /* iCode         */
pdb_a[4].b[2].c[8]      =       53;  /* N/A */
pdb_a[4].b[2].t[0]      =       's';  /* RECORD NAME */
pdb_a[4].b[2].t[1]      =       'i';  /* serial        */
pdb_a[4].b[2].t[2]      =       's';  /* N/A */
pdb_a[4].b[2].t[3]      =       's';  /* resName       */
pdb_a[4].b[2].t[4]      =       's';  /* N/A */
pdb_a[4].b[2].t[5]      =       'c';  /* chainID       */
pdb_a[4].b[2].t[6]      =       'i';  /* resSeq        */
pdb_a[4].b[2].t[7]      =       'c';  /* iCode         */
pdb_a[4].b[2].t[8]      =       's';  /* N/A */
/* Special :  */
/* RECORD Name : JRNL */
strcpy(pdb_a[5].b[0].typ,"JRNL");  /*  */
pdb_a[5].b[0].f         =       1;  /*  */
pdb_a[5].b[0].c[0]      =       80;  /* RECORD NAME */
pdb_a[5].b[0].t[0]      =       's';  /* RECORD NAME */
/* RECORD Name : REMARK */
strcpy(pdb_a[5].b[1].typ,"REMARK");  /*  */
pdb_a[5].b[1].f         =       6;  /*  */
pdb_a[5].b[1].c[0]      =       6;  /* RECORD NAME */
pdb_a[5].b[1].c[1]      =       1;  /* N/A */
pdb_a[5].b[1].c[2]      =       3;  /* remarkNum       */
pdb_a[5].b[1].c[3]      =       1;  /* N/A */
pdb_a[5].b[1].c[4]      =       59;  /* empty           */
pdb_a[5].b[1].c[5]      =       10;  /* N/A */
pdb_a[5].b[1].t[0]      =       's';  /* RECORD NAME */
pdb_a[5].b[1].t[1]      =       's';  /* N/A */
pdb_a[5].b[1].t[2]      =       'i';  /* remarkNum       */
pdb_a[5].b[1].t[3]      =       's';  /* N/A */
pdb_a[5].b[1].t[4]      =       's';  /* empty           */
pdb_a[5].b[1].t[5]      =       's';  /* N/A */
return;
}
void rwm_line (int)
Definition at line 8 of file rwm_line.c.
References linetype::a, linedef::a, pdb_line::b, linetype::b, linedef::b, pdb_line_info::c, linefield::c, DEBUG, pdb_line_info::f, linedef::f, get_type(), IN, ln, OUT, OUTC, pdb_a, read_neek(), SILENT, and WARN.
Referenced by load_pdb().
{
int rwmdone=0, rwma=0, rwmb=0, rwmstop=-1, rwmmt=-1, rwmnl=-1;
linetype rwmlt;
char rwmaCL='I',rwmaRN='I';
/* Read in first six characters and determine line type */
if(DEBUG>=1){printf("rwm_line 1\n");}
for(rwma=0;rwma<6;rwma++){
        if(rwmstop!=0){
                rwmdone=fgetc(IN);
if(DEBUG>=2){printf("Just got new rwmdone \n");}
                if(rwmdone==EOF){read_neek("EOF",rwmln,rwma);}
                }
        if(((rwmdone=='\n')||(rwmdone==' '))&&(rwma==0)){
if(DEBUG>=1){printf("Empty line found \n");}
                if(rwmdone=='\n'){rwmnl=0;}
                rwmmt=0;
                }
        if((rwmdone=='\n')||(rwmstop==0)){
if(DEBUG>=2){printf("resetting rwmdone \n");}
                rwmnl=0;
                rwmdone=' ';
                rwmstop=0;
                }
        ln[rwmln-1].f[0].c[rwma]=rwmdone;
        }
if(rwmmt==0){ /* If this is an empty line */
        if(rwmnl!=0){
                rwmdone=fgetc(IN);
                while(rwmdone!='\n'){
                        rwmdone=fgetc(IN);
                        }
                }
        if(WARN!=0){fprintf(OUT,"\n");}
        return;
        }
if(DEBUG>=1){printf("rwm_line 2\n");}
// if the first six chars seem to be ok...
// null-terminate the string
ln[rwmln-1].f[0].c[6]='\0';
// made it here?  find out the line type
if(DEBUG>=1){printf("rwm_line 3 fieldname is >>>%s<<<\n",ln[rwmln-1].f[0].c);}
rwmlt=get_type(ln[rwmln-1].f[0].c);
ln[rwmln-1].a=rwmlt.a; // class
ln[rwmln-1].b=rwmlt.b; // number for the sub-class
if(DEBUG>=1){printf("rwmlt.a is %d and rwmlt.b is %d\n",rwmlt.a, rwmlt.b);}
/* Assign action switch from internal defaults */
if(DEBUG>=1){printf("rwm_line 4\n");}
if(DEBUG>=0){printf("rwmlt.a is %d and rwmlt.b is %d\n",rwmlt.a,rwmlt.b);}
/* If get_type returned a valid class: */
if(rwmlt.a==-1){ // If this line type is unknown
// do something....
        rwmaCL='I';
        rwmaRN='D';
        }
//If there line was less than 6 characters
if(rwmstop == 0)
 return;
// If the rule is to modify, read in the rest of the line, first...
for(rwma=1;rwma<pdb_a[rwmlt.a].b[rwmlt.b].f;rwma++){
        for(rwmb=0;rwmb<pdb_a[rwmlt.a].b[rwmlt.b].c[rwma];rwmb++){
                ln[rwmln-1].f[rwma].c[rwmb]=fgetc(IN);
                //fprintf(OUTC,"%c",ln[rwmln-1].f[rwma].c[rwmb]);
                if(ln[rwmln-1].f[rwma].c[rwmb]=='\n'){
                        rwmb=pdb_a[rwmlt.a].b[rwmlt.b].c[rwma];
                        rwma=pdb_a[rwmlt.a].b[rwmlt.b].f;
                        }
                if(ln[rwmln-1].f[rwma].c[rwmb]==EOF){
                        read_neek("EOF",(rwmln),(rwma+1));
                        }
                }
        ln[rwmln-1].f[rwma].c[rwmb]='\0';
        }
if(DEBUG>=0){printf("rwm_line 13\n");}
if((WARN==0)&&(SILENT!=0)){fflush(OUTC);}
return;
}
Variable Documentation
char ACT
Definition at line 31 of file load_pdb.h.
Referenced by load_pdb().
float CRYX
Definition at line 35 of file load_pdb.h.
Referenced by load_pdb().
float CRYY
Definition at line 35 of file load_pdb.h.
Referenced by load_pdb().
float CRYZ
Definition at line 35 of file load_pdb.h.
Referenced by load_pdb().
int DATE
Definition at line 32 of file load_pdb.h.
Referenced by load_pdb(), and mytime().
int DEBUG
Definition at line 36 of file load_pdb.h.
Referenced by get_type(), init_struct(), load_pdb(), and rwm_line().
char froot[200]
Definition at line 30 of file load_pdb.h.
FILE* IN
Definition at line 27 of file load_pdb.h.
Referenced by init_struct(), load_pdb(), and rwm_line().
int INWC
Definition at line 32 of file load_pdb.h.
Referenced by findTotalResidue(), getAssembly(), getResInfo(), howManyMolecules(), init_struct(), and load_pdb().
int LASTOKX
Definition at line 34 of file load_pdb.h.
Referenced by load_pdb().
int LASTOKY
Definition at line 34 of file load_pdb.h.
Referenced by load_pdb().
int LASTOKZ
Definition at line 34 of file load_pdb.h.
Referenced by load_pdb().
int LASTRES
Definition at line 34 of file load_pdb.h.
Referenced by load_pdb().
float LASTX
Definition at line 35 of file load_pdb.h.
Referenced by load_pdb().
float LASTY
Definition at line 35 of file load_pdb.h.
Referenced by load_pdb().
float LASTZ
Definition at line 35 of file load_pdb.h.
Referenced by load_pdb().
linedef line[1]
Definition at line 28 of file load_pdb.h.
Referenced by load_atypes(), load_dlg_mol(), read_amber8_mden(), read_amber_prmtop_asis(), read_prep(), read_prepres(), and slurp_file().
FILE * OUT
Definition at line 27 of file load_pdb.h.
Referenced by rwm_line().
FILE * OUTC
Definition at line 27 of file load_pdb.h.
Referenced by rwm_line().
int SILENT
Definition at line 29 of file load_pdb.h.
Referenced by load_pdb(), and rwm_line().
char suf[6]
Definition at line 30 of file load_pdb.h.
Referenced by load_pdb().
char sufc[20]
Definition at line 30 of file load_pdb.h.
Referenced by load_pdb().
float UNCTOL
Definition at line 35 of file load_pdb.h.
Referenced by load_pdb().
int UNCUT
Definition at line 33 of file load_pdb.h.
Referenced by load_pdb().
int UNx
Definition at line 33 of file load_pdb.h.
Referenced by load_pdb().
int UNy
Definition at line 33 of file load_pdb.h.
Referenced by load_pdb().
int UNz
Definition at line 33 of file load_pdb.h.
Referenced by load_pdb().
int WARN
Definition at line 29 of file load_pdb.h.
Referenced by load_pdb(), and rwm_line().