GLYLIB: molecules.h File Reference
molecules.h File Reference
#include "geometries.h"
#include "parameter_sets.h"
Classes
struct molindex
struct ensindex
struct bond
struct bondset
struct connection_tree
struct molbond
struct molbondset
struct angle_index
struct torsion_index
struct atom
struct residue
struct molecule
struct dockinfo
struct assembly
struct ensemble
Defines
#define GLYLIB_MOLECULES
Functions
void print_molecule (molecule *, int)
void print_residue (residue *, int)
void print_bondset (bondset *, int)
void print_atom (atom *, int)
void print_bond (bond *)
void print_atype (atype *, int)
void print_plane (plane *)
void print_vectormag_3D (vectormag_3D *)
void print_coord_3D (coord_3D *)
void dprint_molecule (molecule *, int)
void dprint_residue (residue *, int)
void dprint_bondset (bondset *, int)
void dprint_atom (atom *, int)
void dprint_bond (bond *)
void dprint_atype (atype *, int)
void dprint_plane (plane *)
void dprint_vectormag_3D (vectormag_3D *)
void dprint_coord_3D (coord_3D *)
void dXprint_molecule (molecule *, int)
void dXprint_residue (residue *, int)
void dXprint_bondset (bondset *, int)
void dXprint_atom (atom *, int)
void dXprint_bond (bond *)
void dXprint_atype (atype *, int)
void dXprint_plane (plane *)
void dXprint_vectormag_3D (vectormag_3D *)
void dXprint_coord_3D (coord_3D *)
void translate_to_COM (molecule *, atype *, int)
void translate_zero_to_coord_M (molecule *, int, int, coord_3D)
void assign_residue_COM (residue *r, atype *ATYPE)
void assign_molecule_COM (molecule *m, atype *ATYPE)
void assign_assembly_COM (assembly *a, atype *ATYPE)
void assign_ensemble_COM (ensemble *e, atype *ATYPE)
coord_3D get_residue_COM (residue *r, atype *ATYPE, int xs)
coord_3D get_molecule_COM (molecule *m, atype *ATYPE, int xs)
coord_3D get_assembly_COM (assembly *a, atype *ATYPE, int xs)
coord_3D get_ensemble_COM (ensemble *e, atype *ATYPE, int xs)
void rotate_vector_to_Z_M (molecule *, int, int, int, int, vectormag_3D)
void rotate_vector_to_Z_list (coord_3D *, int, vectormag_3D)
coord_3D get_geometric_center (coord_3D *, int)
plane get_plane (coord_3D, coord_3D, coord_3D)
vectormag_3D normalize_vec (vectormag_3D)
void normalize_molecule_vectors (molecule *, int, int)
vectormag_3D scalarmult_vec (vectormag_3D, double)
vectormag_3D add_vec (vectormag_3D, vectormag_3D)
vectormag_3D subtract_vec (vectormag_3D, vectormag_3D)
coord_3D scalarmult_coord (coord_3D, double)
coord_3D add_coord (coord_3D, coord_3D)
coord_3D subtract_coord (coord_3D, coord_3D)
vectormag_3D get_crossprod (vectormag_3D, vectormag_3D)
double get_dotprod (vectormag_3D, vectormag_3D)
double get_magnitude (vectormag_3D)
void shift_molecule_atoms_by_vector_scale (molecule *m, int xs, int xt, int vr, double scale)
vectormag_3D get_molecule_point_charge_dipole (molecule *m, int xs, int chgsrc, atype *AT)
vectormag_3D zero_vec ()
coord_3D zero_coord ()
coord_3D vec_to_coord (vectormag_3D)
vectormag_3D coord_to_vec (coord_3D)
void rollMolecule (molecule *, double)
void pitchMolecule (molecule *, double)
void yawMolecule (molecule *, double)
void rollAssembly (assembly *, double)
void pitchAssembly (assembly *, double)
void yawAssembly (assembly *, double)
void outputMolPDB (molecule *, char *)
void outputAsmblPDB (assembly *, char *)
char * spacing (int, int)
double get_alt_rms_res (residue *r, int xs, int xt)
double get_alt_rms_mol (molecule *m, int xs, int xt)
atype * ATYPE_init ()
void initialize_coord_3D (coord_3D *c)
void initialize_vectormag_3D (vectormag_3D *v)
void initialize_plane (plane *p)
void initialize_atype (atype *at)
void initialize_rtype (rtype *rt)
void initialize_mtype (mtype *mt)
void initialize_types (types *t)
void initialize_molindex (molindex *mi)
void initialize_ensindex (ensindex *ei)
void initialize_bond (bond *b)
void initialize_bondset (bondset *bs)
void initialize_molbond (molbond *mb)
void initialize_molbondset (molbondset *mbs)
void initialize_atom (atom *a)
void initialize_residue (residue *r)
void initialize_molecule (molecule *m)
void initialize_dockinfo (dockinfo *di)
void initialize_assembly (assembly *A)
void initialize_ensemble (ensemble *E)
Variables
char * ATYPESFILE
char * RTYPESFILE
char * MTYPESFILE
int NUMAT
Detailed Description
Header file for molecule structures
File begun May 2007 by Lachele Foley and modified continually ever since by Lachele Foley and others, including Mike Tessier.
Definition in file molecules.h.
Define Documentation
#define GLYLIB_MOLECULES
Definition at line 8 of file molecules.h.
Function Documentation
coord_3D add_coord (coord_3D , coord_3D)
Definition at line 7 of file add_coord.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
Referenced by shift_molecule_atoms_by_vector_scale().
{
coord_3D nc;
nc.i=ca.i+cb.i;
nc.j=ca.j+cb.j;
nc.k=ca.k+cb.k;
return nc;
}
vectormag_3D add_vec (vectormag_3D , vectormag_3D)
Definition at line 7 of file add_vec.c.
References vectormag_3D::d, vectormag_3D::i, vectormag_3D::j, and vectormag_3D::k.
{
vectormag_3D nv;
nv.i=va.i+vb.i;
nv.j=va.j+vb.j;
nv.k=va.k+vb.k;
// don't trust the d in nv
nv.d=sqrt(nv.i*nv.i+nv.j*nv.j+nv.k*nv.k);
return nv;
}
void assign_assembly_COM (assembly * a, atype * ATYPE)
Definition at line 83 of file assign_COM.c.
References residue::a, assembly::COM, coord_3D::i, coord_3D::j, coord_3D::k, atype::m, assembly::m, assembly::mass, mywhine(), residue::na, assembly::nm, molecule::nr, molecule::r, atom::t, and atom::x.
{
int ta=0,tr=0,tm=0;
double tmm=0;
// calculate the molecular weight
for(tm=0;tm<a[0].nm;tm++){
for(tr=0;tr<a[0].m[tm][0].nr;tr++){
for(ta=0;ta<a[0].m[tm][0].r[tr].na;ta++){
        tmm+=ATYPE[a[0].m[tm][0].r[tr].a[ta].t].m;
        }
        }
        }
//printf("the molecular weight is %f\n",tmm);
if(tmm==0){mywhine("molecular weight of molecule %s is zero.\n(Have types/masses been assigned?");}
a[0].mass=tmm;
a[0].COM.i=0;
a[0].COM.j=0;
a[0].COM.k=0;
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
// calculate the center of mass
for(tm=0;tm<a[0].nm;tm++){ // COM = sum(m_i * r_i) / sum(m_i)
for(tr=0;tr<a[0].m[tm][0].nr;tr++){ // COM = sum(m_i * r_i) / sum(m_i)
for(ta=0;ta<a[0].m[tm][0].r[tr].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        a[0].COM.i+=a[0].m[tm][0].r[tr].a[ta].x.i*ATYPE[a[0].m[tm][0].r[tr].a[ta].t].m;
        a[0].COM.j+=a[0].m[tm][0].r[tr].a[ta].x.j*ATYPE[a[0].m[tm][0].r[tr].a[ta].t].m;
        a[0].COM.k+=a[0].m[tm][0].r[tr].a[ta].x.k*ATYPE[a[0].m[tm][0].r[tr].a[ta].t].m;
        }
        }
        }
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
a[0].COM.i/=tmm;
a[0].COM.j/=tmm;
a[0].COM.k/=tmm;
//printf("center of mass is at: %20.12e %20.12e %20.12e \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
return;
}
void assign_ensemble_COM (ensemble * e, atype * ATYPE)
Definition at line 131 of file assign_COM.c.
References residue::a, ensemble::COM, coord_3D::i, coord_3D::j, coord_3D::k, atype::m, ensemble::m, ensemble::mass, mywhine(), residue::na, ensemble::nm, molecule::nr, molecule::r, atom::t, and atom::x.
{
int ta=0,tr=0,tm=0;
double tmm=0;
// calculate the molecular weight
for(tm=0;tm<e[0].nm;tm++){
for(tr=0;tr<e[0].m[tm].nr;tr++){
for(ta=0;ta<e[0].m[tm].r[tr].na;ta++){
        tmm+=ATYPE[e[0].m[tm].r[tr].a[ta].t].m;
        }
        }
        }
//printf("the molecular weight is %f\n",tmm);
if(tmm==0){mywhine("molecular weight of molecule %s is zero.\n(Have types/masses been assigned?");}
e[0].mass=tmm;
e[0].COM.i=0;
e[0].COM.j=0;
e[0].COM.k=0;
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
// calculate the center of mass
for(tm=0;tm<e[0].nm;tm++){ // COM = sum(m_i * r_i) / sum(m_i)
for(tr=0;tr<e[0].m[tm].nr;tr++){ // COM = sum(m_i * r_i) / sum(m_i)
for(ta=0;ta<e[0].m[tm].r[tr].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        e[0].COM.i+=e[0].m[tm].r[tr].a[ta].x.i*ATYPE[e[0].m[tm].r[tr].a[ta].t].m;
        e[0].COM.j+=e[0].m[tm].r[tr].a[ta].x.j*ATYPE[e[0].m[tm].r[tr].a[ta].t].m;
        e[0].COM.k+=e[0].m[tm].r[tr].a[ta].x.k*ATYPE[e[0].m[tm].r[tr].a[ta].t].m;
        }
        }
        }
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
e[0].COM.i/=tmm;
e[0].COM.j/=tmm;
e[0].COM.k/=tmm;
//printf("center of mass is at: %20.12e %20.12e %20.12e \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
return;
}
void assign_molecule_COM (molecule * m, atype * ATYPE)
Definition at line 45 of file assign_COM.c.
References residue::a, molecule::COM, coord_3D::i, coord_3D::j, coord_3D::k, molecule::m, atype::m, mywhine(), residue::na, molecule::nr, molecule::r, atom::t, and atom::x.
{
int ta=0,tr=0;
double tmm=0;
// calculate the molecular weight
for(tr=0;tr<m[0].nr;tr++){
for(ta=0;ta<m[0].r[tr].na;ta++){
        tmm+=ATYPE[m[0].r[tr].a[ta].t].m;
        }
        }
//printf("the molecular weight is %f\n",tmm);
if(tmm==0){mywhine("molecular weight of molecule %s is zero.\n(Have types/masses been assigned?");}
m[0].m=tmm;
m[0].COM.i=0;
m[0].COM.j=0;
m[0].COM.k=0;
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
// calculate the center of mass
for(tr=0;tr<m[0].nr;tr++){ // COM = sum(m_i * r_i) / sum(m_i)
for(ta=0;ta<m[0].r[tr].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        m[0].COM.i+=m[0].r[tr].a[ta].x.i*ATYPE[m[0].r[tr].a[ta].t].m;
        m[0].COM.j+=m[0].r[tr].a[ta].x.j*ATYPE[m[0].r[tr].a[ta].t].m;
        m[0].COM.k+=m[0].r[tr].a[ta].x.k*ATYPE[m[0].r[tr].a[ta].t].m;
        }
        }
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
m[0].COM.i/=tmm;
m[0].COM.j/=tmm;
m[0].COM.k/=tmm;
//printf("center of mass is at: %20.12e %20.12e %20.12e \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
return;
}
void assign_residue_COM (residue * r, atype * ATYPE)
Definition at line 11 of file assign_COM.c.
References residue::a, residue::COM, coord_3D::i, coord_3D::j, coord_3D::k, residue::m, atype::m, mywhine(), residue::na, atom::t, and atom::x.
{
int ta=0;
double tmm=0;
// calculate the molecular weight
for(ta=0;ta<r[0].na;ta++){
        tmm+=ATYPE[r[0].a[ta].t].m;
        }
//printf("the molecular weight is %f\n",tmm);
if(tmm==0){mywhine("molecular weight of molecule %s is zero.\n(Have types/masses been assigned?");}
r[0].m=tmm;
r[0].COM.i=0;
r[0].COM.j=0;
r[0].COM.k=0;
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
// calculate the center of mass
for(ta=0;ta<r[0].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        r[0].COM.i+=r[0].a[ta].x.i*ATYPE[r[0].a[ta].t].m;
        r[0].COM.j+=r[0].a[ta].x.j*ATYPE[r[0].a[ta].t].m;
        r[0].COM.k+=r[0].a[ta].x.k*ATYPE[r[0].a[ta].t].m;
        }
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
r[0].COM.i/=tmm;
r[0].COM.j/=tmm;
r[0].COM.k/=tmm;
//printf("center of mass is at: %20.12e %20.12e %20.12e \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
return;
}
atype* ATYPE_init ()
Definition at line 21 of file ATYPE_init.c.
References atype::m, atype::n, atype::nb, and NUMAT.
                   {
atype *A;
NUMAT=15;
A=(atype*)calloc(NUMAT,sizeof(atype));
A[0].n=6;
strcpy(A[0].N,"CG");
strcpy(A[0].NT,"C");
A[0].m=12.011;
strcpy(A[0].desc,"sp3");
A[0].nb=4;
//
A[1].n=6;
strcpy(A[1].N,"CY");
strcpy(A[1].NT,"C");
A[1].m=12.011;
strcpy(A[1].desc,"sp3");
A[1].nb=4;
//
A[2].n=1;
strcpy(A[2].N,"H");
strcpy(A[2].NT,"H");
A[2].m=1.00794;
strcpy(A[2].desc,"sp3");
A[2].nb=1;
//
A[3].n=1;
strcpy(A[3].N,"H1");
strcpy(A[3].NT,"H");
A[3].m=1.00794;
strcpy(A[3].desc,"sp3");
A[3].nb=1;
//
A[4].n=1;
strcpy(A[4].N,"H2");
strcpy(A[4].NT,"H");
A[4].m=1.00794;
strcpy(A[4].desc,"sp3");
A[4].nb=1;
//
A[5].n=1;
strcpy(A[5].N,"HC");
strcpy(A[5].NT,"H");
A[5].m=1.00794;
strcpy(A[5].desc,"sp3");
A[5].nb=1;
//
A[6].n=1;
strcpy(A[6].N,"HO");
strcpy(A[6].NT,"H");
A[6].m=1.00794;
strcpy(A[6].desc,"sp3");
A[6].nb=1;
//
A[7].n=1;
strcpy(A[7].N,"HW");
strcpy(A[7].NT,"H");
A[7].m=1.00794;
strcpy(A[7].desc,"sp3");
A[7].nb=1;
//
A[8].n=7;
strcpy(A[8].N,"N");
strcpy(A[8].NT,"N");
A[8].m=14.01;
strcpy(A[8].desc,"sp2");
A[8].nb=3;
//
A[9].n=8;
strcpy(A[9].N,"OH");
strcpy(A[9].NT,"O");
A[9].m=15.994;
strcpy(A[9].desc,"sp3");
A[9].nb=2;
//
A[10].n=8;
strcpy(A[10].N,"OS");
strcpy(A[10].NT,"O");
A[10].m=15.994;
strcpy(A[10].desc,"sp3");
A[10].nb=2;
//
A[11].n=8;
strcpy(A[11].N,"O");
strcpy(A[11].NT,"O");
A[11].m=15.994;
strcpy(A[11].desc,"sp2");
A[11].nb=1;
//
A[12].n=8;
strcpy(A[12].N,"O2");
strcpy(A[12].NT,"O");
A[12].m=15.994;
strcpy(A[12].desc,"sp2");
A[12].nb=1;
//
A[13].n=8;
strcpy(A[13].N,"OW");
strcpy(A[13].NT,"O");
A[13].m=15.994;
strcpy(A[13].desc,"sp3");
A[13].nb=2;
//
A[14].n=11;
strcpy(A[14].N,"IP");
strcpy(A[14].NT,"Na+");
A[14].m=15.994;
strcpy(A[14].desc,"sp3");
A[14].nb=0;
//theoretically, something like this should work...
//A[]={
//{6,"C",  "C", 12.011, "sp2", 3, {1,1,2}},
//{6,"CG", "C", 12.011, "sp3", 4, {1,1,1,1}},
//{6,"CY", "C", 12.011, "sp3", 4}
//{1,"H",  "H", 1.00794, "sp3", 1}
//{1,"H1", "H", 1.00794, "sp3", 1}
//{1,"H2", "H", 1.00794, "sp3", 1}
//{1,"HC", "H", 1.00794, "sp3", 1}
//{1,"HO", "H", 1.00794, "sp3", 1}
//{1,"HW", "H", 1.00794, "sp3", 1}
//{7,"N",  "N", 14.01,  "sp2", 3}
//{8,"OH", "O", 15.994, "sp3", 2}
//{8,"OS", "O", 15.994, "sp3", 2}
//{8,"O",  "O", 15.994, "sp2", 1}
//{8,"O2", "O", 15.994, "sp2", 1}
//{8,"OW", "O", 15.994, "sp3", 2}
//{11,"IP", "Na+", 15.994, "sp3", 0}
//};
return A;
}
vectormag_3D coord_to_vec (coord_3D)
Definition at line 7 of file coord_to_vec.c.
References vectormag_3D::d, coord_3D::i, vectormag_3D::i, coord_3D::j, vectormag_3D::j, coord_3D::k, and vectormag_3D::k.
{
vectormag_3D nv;
nv.i=c.i;
nv.j=c.j;
nv.k=c.k;
// don't trust entry in 'd' -- normalize now to be certain
nv.d=sqrt(nv.i*nv.i+nv.j*nv.j+nv.k*nv.k);
return nv;
}
void dprint_atom (atom * , int)
Referenced by dprint_residue().
void dprint_atype (atype * , int)
void dprint_bond (bond *)
Definition at line 55 of file dprint_X.c.
Referenced by dprint_atom(), and dprint_bondset().
{
        printf("bond s t o \t%d \t%d \t%20.12f\n",b[0].s,b[0].t,b[0].o);
return;
}
void dprint_bondset (bondset * , int)
Referenced by dprint_residue().
void dprint_coord_3D (coord_3D *)
Definition at line 23 of file dprint_X.c.
Referenced by dprint_atom(), dprint_residue(), and rotate_vector_to_Z_M().
{
        printf("coord i j k \t%20.12f \t%20.12f \t%20.12f\n",c[0].i,c[0].j,c[0].k);
return;
}
void dprint_molecule (molecule * , int)
void dprint_plane (plane *)
Definition at line 33 of file dprint_X.c.
Referenced by dprint_residue().
{
        printf("plane A B C D \t%20.12f \t%20.12f \t%20.12f \t%20.12f\n",p[0].A,p[0].B,p[0].C,p[0].D);
return;
}
void dprint_residue (residue * , int)
Definition at line 110 of file dprint_X.c.
References dprint_atom(), dprint_bondset(), dprint_coord_3D(), and dprint_plane().
Referenced by dprint_molecule().
{
        int pa=0,psz=0,puse=0,pbins=0;
        printf("residue \tn=%d ; N=>>%s<< ; na=%d ; nbs=%d ; nr=%d \n",r[0].n,r[0].N,\
                r[0].na,r[0].nbs,r[0].nr);
        if(i>0){
                puse=malloc_usable_size(r[0].a);
                psz=sizeof(atom);
                pbins=puse/psz;
                //printf("usable return is %d, size is %d, bins is %d\n",puse,psz,pbins);
                printf("\t%d atoms have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<r[0].na)&&(pa<pbins));pa++){
                        printf("\tatom set %d\n",pa);
                        dprint_atom(&(r[0].a[pa]),i);
                        }
                puse=malloc_usable_size(r[0].bs);
                psz=sizeof(bondset);
                pbins=puse/psz;
                printf("\t%d consecutive, linear bonds have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<r[0].nbs)&&(pa<pbins));pa++){
                        printf("\tconsec. lin, bondset set %d\n",pa);
                        dprint_bondset(&(r[0].bs[pa]),i);
                        }
                puse=malloc_usable_size(r[0].rbs);
                psz=sizeof(bondset);
                pbins=puse/psz;
                printf("\t%d consecutive ring bonds have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<r[0].nrbs)&&(pa<pbins));pa++){
                        printf("\tconsec. ring bondset set %d\n",pa);
                        dprint_bondset(&(r[0].rbs[pa]),i);
                        }
                puse=malloc_usable_size(r[0].rc);
                psz=sizeof(coord_3D);
                pbins=puse/psz;
                printf("\t%d ring center coordinates have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<r[0].nrc)&&(pa<pbins));pa++){
                        printf("\tconsec ring coords set %d:  ",pa);
                        dprint_coord_3D(&(r[0].rc[pa]));
                        }
                puse=malloc_usable_size(r[0].rp);
                psz=sizeof(plane);
                pbins=puse/psz;
                printf("\t%d ring plane equations have been allocated: \n",pbins);
                for(pa=0;((pa<i)&&(pa<r[0].nrp)&&(pa<pbins));pa++){
                        printf("\tring plane set %d:  ",pa);
                        dprint_plane(&(r[0].rp[pa]));
                        }
                }
return;
}
void dprint_vectormag_3D (vectormag_3D *)
Referenced by dprint_atom(), and rotate_vector_to_Z_M().
void dXprint_atom (atom * , int)
Referenced by dXprint_residue().
void dXprint_atype (atype * , int)
void dXprint_bond (bond *)
Definition at line 51 of file dXprint_X.c.
Referenced by dXprint_atom(), and dXprint_bondset().
{
        printf("bond s t o \t%d \t%d \t%20.12f\n",b[0].s,b[0].t,b[0].o);
return;
}
void dXprint_bondset (bondset * , int)
Referenced by dXprint_residue().
void dXprint_coord_3D (coord_3D *)
Definition at line 23 of file dXprint_X.c.
Referenced by dXprint_atom(), dXprint_residue(), and load_dlg_mol().
{
        printf("coord i j k \t%20.12f \t%20.12f \t%20.12f\n",c[0].i,c[0].j,c[0].k);
return;
}
void dXprint_molecule (molecule * , int)
Referenced by load_dlg_mol().
void dXprint_plane (plane *)
Definition at line 33 of file dXprint_X.c.
Referenced by dXprint_residue().
{
        printf("plane A B C D \t%20.12f \t%20.12f \t%20.12f \t%20.12f\n",p[0].A,p[0].B,p[0].C,p[0].D);
return;
}
void dXprint_residue (residue * , int)
Definition at line 90 of file dXprint_X.c.
References dXprint_atom(), dXprint_bondset(), dXprint_coord_3D(), and dXprint_plane().
Referenced by dXprint_molecule().
{
        int pa=0;
        printf("residue \tn=%d ; N=>>%s<< ; na=%d ; nbs=%d ; nr=%d \n",r[0].n,r[0].N,\
                r[0].na,r[0].nbs,r[0].nr);
        if(i>0){
                for(pa=0;((pa<i)&&(pa<r[0].na));pa++){
                        printf("\tatom set %d\n",pa);
                        dXprint_atom(&(r[0].a[pa]),i);
                        }
                for(pa=0;((pa<i)&&(pa<r[0].nbs));pa++){
                        printf("\tconsec. lin, bondset set %d\n",pa);
                        dXprint_bondset(&(r[0].bs[pa]),i);
                        }
                for(pa=0;((pa<i)&&(pa<r[0].nrbs));pa++){
                        printf("\tconsec. ring bondset set %d\n",pa);
                        dXprint_bondset(&(r[0].rbs[pa]),i);
                        }
                for(pa=0;((pa<i)&&(pa<r[0].nrc));pa++){
                        printf("\tconsec ring coords set %d:  ",pa);
                        dXprint_coord_3D(&(r[0].rc[pa]));
                        }
                for(pa=0;((pa<i)&&(pa<r[0].nrp));pa++){
                        printf("\tring plane set %d:  ",pa);
                        dXprint_plane(&(r[0].rp[pa]));
                        }
                }
return;
}
void dXprint_vectormag_3D (vectormag_3D *)
Referenced by dXprint_atom().
double get_alt_rms_mol (molecule * m, int xs, int xt)
Definition at line 38 of file get_rms_alt_X.c.
References coord_3D::i, coord_3D::j, coord_3D::k, mywhine(), residue::na, molecule::nr, molecule::r, and subtract_coord().
{
int ai=0,ri=0,nat=0;
double RMS=0;
coord_3D c;
if(xt<0){mywhine("get_alt_rms_mol: target coord cannot be main set");}
if(xs<0){mywhine("get_alt_rms_mol: main set source coords not written yet");}
for(ri=0;ri<m[0].nr;ri++){
        nat+=m[0].r[ri].na;
        for(ai=0;ai<m[0].r[ri].na;ai++){
                c=subtract_coord(m[0].r[ri].a[ai].xa[xs],m[0].r[ri].a[ai].xa[xt]);
                RMS+=c.i*c.i+c.j*c.j+c.k*c.k;
        }}
RMS/=nat;
RMS=sqrt(RMS);
return RMS;
}
double get_alt_rms_res (residue * r, int xs, int xt)
Definition at line 21 of file get_rms_alt_X.c.
References coord_3D::i, coord_3D::j, coord_3D::k, mywhine(), residue::na, and subtract_coord().
{
int ai=0;
double RMS=0;
coord_3D c;
if(xt<0){mywhine("get_alt_rms_res: target coord cannot be main set");}
if(xs<0){mywhine("get_alt_rms_res: main set source coords not written yet");}
for(ai=0;ai<r[0].na;ai++){
        c=subtract_coord(r[0].a[ai].xa[xs],r[0].a[ai].xa[xt]);
        RMS+=c.i*c.i+c.j*c.j+c.k*c.k;
        }
RMS/=r[0].na;
RMS=sqrt(RMS);
return RMS;
}
coord_3D get_assembly_COM (assembly * a, atype * ATYPE, int xs)
Definition at line 105 of file get_COM.c.
References residue::a, coord_3D::i, coord_3D::j, coord_3D::k, atype::m, assembly::m, assembly::mass, mywhine(), residue::na, assembly::nm, molecule::nr, molecule::r, atom::t, atom::x, and atom::xa.
{
int ta=0,tr=0,tm=0;
double tmm=0;
coord_3D c;
// calculate the molecular weight
for(tm=0;tm<a[0].nm;tm++){
for(tr=0;tr<a[0].m[tm][0].nr;tr++){
for(ta=0;ta<a[0].m[tm][0].r[tr].na;ta++){
        tmm+=ATYPE[a[0].m[tm][0].r[tr].a[ta].t].m;
        }
        }
        }
//printf("the molecular weight is %f\n",tmm);
if(tmm==0){mywhine("molecular weight of molecule %s is zero.\n(Have types/masses been assigned?");}
a[0].mass=tmm;
c.i=0;
c.j=0;
c.k=0;
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
// calculate the center of mass
if(xs==-1){
for(tm=0;tm<a[0].nm;tm++){ // COM = sum(m_i * r_i) / sum(m_i)
for(tr=0;tr<a[0].m[tm][0].nr;tr++){ // COM = sum(m_i * r_i) / sum(m_i)
for(ta=0;ta<a[0].m[tm][0].r[tr].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        c.i+=a[0].m[tm][0].r[tr].a[ta].x.i*ATYPE[a[0].m[tm][0].r[tr].a[ta].t].m;
        c.j+=a[0].m[tm][0].r[tr].a[ta].x.j*ATYPE[a[0].m[tm][0].r[tr].a[ta].t].m;
        c.k+=a[0].m[tm][0].r[tr].a[ta].x.k*ATYPE[a[0].m[tm][0].r[tr].a[ta].t].m;
        }
        }
        }
        }
else {
for(tm=0;tm<a[0].nm;tm++){ // COM = sum(m_i * r_i) / sum(m_i)
for(tr=0;tr<a[0].m[tm][0].nr;tr++){ // COM = sum(m_i * r_i) / sum(m_i)
for(ta=0;ta<a[0].m[tm][0].r[tr].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        c.i+=a[0].m[tm][0].r[tr].a[ta].xa[xs].i*ATYPE[a[0].m[tm][0].r[tr].a[ta].t].m;
        c.j+=a[0].m[tm][0].r[tr].a[ta].xa[xs].j*ATYPE[a[0].m[tm][0].r[tr].a[ta].t].m;
        c.k+=a[0].m[tm][0].r[tr].a[ta].xa[xs].k*ATYPE[a[0].m[tm][0].r[tr].a[ta].t].m;
        }
        }
        }
        }
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
c.i/=tmm;
c.j/=tmm;
c.k/=tmm;
//printf("center of mass is at: %20.12e %20.12e %20.12e \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
return c;
}
vectormag_3D get_crossprod (vectormag_3D , vectormag_3D)
Definition at line 7 of file get_crossprod.c.
References vectormag_3D::d, vectormag_3D::i, vectormag_3D::j, and vectormag_3D::k.
Referenced by rotate_vector_to_Z_list(), and rotate_vector_to_Z_M().
{
vectormag_3D xp;
xp.i=a.j*b.k-a.k*b.j;
xp.j=-(a.i*b.k-a.k*b.i);
xp.k=a.i*b.j-a.j*b.i;
xp.d=sqrt(xp.i*xp.i+xp.j*xp.j+xp.k*xp.k);
return xp;
}
double get_dotprod (vectormag_3D , vectormag_3D)
Definition at line 8 of file get_dotprod.c.
References vectormag_3D::i, vectormag_3D::j, and vectormag_3D::k.
{
double dp=0;
dp=(a.i*b.i+a.j*b.j+a.k*b.k);
return dp;
}
coord_3D get_ensemble_COM (ensemble * e, atype * ATYPE, int xs)
Definition at line 167 of file get_COM.c.
References residue::a, coord_3D::i, coord_3D::j, coord_3D::k, atype::m, ensemble::m, ensemble::mass, mywhine(), residue::na, ensemble::nm, molecule::nr, molecule::r, atom::t, atom::x, and atom::xa.
{
int ta=0,tr=0,tm=0;
double tmm=0;
coord_3D c;
// calculate the molecular weight
for(tm=0;tm<e[0].nm;tm++){
for(tr=0;tr<e[0].m[tm].nr;tr++){
for(ta=0;ta<e[0].m[tm].r[tr].na;ta++){
        tmm+=ATYPE[e[0].m[tm].r[tr].a[ta].t].m;
        }
        }
        }
//printf("the molecular weight is %f\n",tmm);
if(tmm==0){mywhine("molecular weight of molecule %s is zero.\n(Have types/masses been assigned?");}
e[0].mass=tmm;
c.i=0;
c.j=0;
c.k=0;
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
// calculate the center of mass
if(xs==-1){
for(tm=0;tm<e[0].nm;tm++){ // COM = sum(m_i * r_i) / sum(m_i)
for(tr=0;tr<e[0].m[tm].nr;tr++){ // COM = sum(m_i * r_i) / sum(m_i)
for(ta=0;ta<e[0].m[tm].r[tr].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        c.i+=e[0].m[tm].r[tr].a[ta].x.i*ATYPE[e[0].m[tm].r[tr].a[ta].t].m;
        c.j+=e[0].m[tm].r[tr].a[ta].x.j*ATYPE[e[0].m[tm].r[tr].a[ta].t].m;
        c.k+=e[0].m[tm].r[tr].a[ta].x.k*ATYPE[e[0].m[tm].r[tr].a[ta].t].m;
        }
        }
        }
        }
else {
for(tm=0;tm<e[0].nm;tm++){ // COM = sum(m_i * r_i) / sum(m_i)
for(tr=0;tr<e[0].m[tm].nr;tr++){ // COM = sum(m_i * r_i) / sum(m_i)
for(ta=0;ta<e[0].m[tm].r[tr].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        c.i+=e[0].m[tm].r[tr].a[ta].xa[xs].i*ATYPE[e[0].m[tm].r[tr].a[ta].t].m;
        c.j+=e[0].m[tm].r[tr].a[ta].xa[xs].j*ATYPE[e[0].m[tm].r[tr].a[ta].t].m;
        c.k+=e[0].m[tm].r[tr].a[ta].xa[xs].k*ATYPE[e[0].m[tm].r[tr].a[ta].t].m;
        }
        }
        }
        }
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
c.i/=tmm;
c.j/=tmm;
c.k/=tmm;
//printf("center of mass is at: %20.12e %20.12e %20.12e \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
return c;
}
coord_3D get_geometric_center (coord_3D * , int)
Definition at line 9 of file get_geometric_center.c.
References coord_3D::i, coord_3D::j, coord_3D::k, and mywhine().
{
int gca=0;
coord_3D C;
if(nc==0){mywhine("cannot get center for zero points (get_geometric_center)");}
C.i=C.j=C.k=0;
//printf("initialized:\n");
//dprint_coord_3D(&C);
//printf("in loop:\n");
for(gca=0;gca<nc;gca++){
//      X.i (center) = avg (atomscoords.x.i) ; and so forth
        C.i+=c[gca].i;
        C.j+=c[gca].j;
        C.k+=c[gca].k;
        //dprint_coord_3D(&C);
        }
C.i/=nc;
C.j/=nc;
C.k/=nc;
//printf("done:\n");
//dprint_coord_3D(&C);
return C;
}
double get_magnitude (vectormag_3D)
Definition at line 7 of file get_magnitude.c.
References vectormag_3D::i, vectormag_3D::j, and vectormag_3D::k.
Referenced by get_molecule_point_charge_dipole(), and rotate_vector_to_Z_M().
{
double d=0;
d=sqrt(v.i*v.i+v.j*v.j+v.k*v.k);
return d;
}
coord_3D get_molecule_COM (molecule * m, atype * ATYPE, int xs)
Definition at line 55 of file get_COM.c.
References residue::a, coord_3D::i, coord_3D::j, coord_3D::k, molecule::m, atype::m, mywhine(), residue::na, molecule::nr, molecule::r, atom::t, atom::x, and atom::xa.
Referenced by get_molecule_point_charge_dipole().
{
int ta=0,tr=0;
double tmm=0;
coord_3D c;
// calculate the molecular weight
for(tr=0;tr<m[0].nr;tr++){
for(ta=0;ta<m[0].r[tr].na;ta++){
        tmm+=ATYPE[m[0].r[tr].a[ta].t].m;
        }
        }
//printf("the molecular weight is %f\n",tmm);
if(tmm==0){mywhine("molecular weight of molecule %s is zero.\n(Have types/masses been assigned?");}
m[0].m=tmm;
c.i=0;
c.j=0;
c.k=0;
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
// calculate the center of mass
if(xs==-1){
for(tr=0;tr<m[0].nr;tr++){ // COM = sum(m_i * r_i) / sum(m_i)
for(ta=0;ta<m[0].r[tr].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        c.i+=m[0].r[tr].a[ta].x.i*ATYPE[m[0].r[tr].a[ta].t].m;
        c.j+=m[0].r[tr].a[ta].x.j*ATYPE[m[0].r[tr].a[ta].t].m;
        c.k+=m[0].r[tr].a[ta].x.k*ATYPE[m[0].r[tr].a[ta].t].m;
        }
        }
        }
else {
for(tr=0;tr<m[0].nr;tr++){ // COM = sum(m_i * r_i) / sum(m_i)
for(ta=0;ta<m[0].r[tr].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        c.i+=m[0].r[tr].a[ta].xa[xs].i*ATYPE[m[0].r[tr].a[ta].t].m;
        c.j+=m[0].r[tr].a[ta].xa[xs].j*ATYPE[m[0].r[tr].a[ta].t].m;
        c.k+=m[0].r[tr].a[ta].xa[xs].k*ATYPE[m[0].r[tr].a[ta].t].m;
        }
        }
        }
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
c.i/=tmm;
c.j/=tmm;
c.k/=tmm;
//printf("center of mass is at: %20.12e %20.12e %20.12e \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
return c;
}
vectormag_3D get_molecule_point_charge_dipole (molecule * m, int xs, int chgsrc, atype * AT)
Definition at line 17 of file get_dipole.c.
References residue::a, atom::ch, vectormag_3D::d, get_magnitude(), get_molecule_COM(), coord_3D::i, vectormag_3D::i, coord_3D::j, vectormag_3D::j, coord_3D::k, vectormag_3D::k, mywhine(), residue::na, molecule::nr, molecule::r, atom::x, atom::xa, and zero_vec().
{
int ta=0,tb,tuse=0,tsz=0,tbins=0;
coord_3D com;
vectormag_3D dip;
dip = zero_vec();
// determine the center of mass
com=get_molecule_COM(m,AT,xs);
// calculate the dipole relative to the center of mass
if(xs==-1){
// sum over all charge*(x-COM)
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        dip.i+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].x.i-com.i);
                        dip.j+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].x.j-com.j);
                        dip.k+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].x.k-com.k);
                        }
                }
        }
else{
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        tuse=malloc_usable_size(m[0].r[ta].a[tb].xa);
                        tsz=sizeof(coord_3D);
                        tbins=tuse/tsz;
                        if(tbins<(xs+1)){mywhine("memory issue: source coords not allocated in get_molecule_point_charge_dipole");}
                        dip.i+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].xa[xs].i-com.i);
                        dip.j+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].xa[xs].j-com.j);
                        dip.k+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].xa[xs].k-com.k);
                        }
                }
        }
dip.d=get_magnitude(dip);
return dip;
}
plane get_plane (coord_3D , coord_3D , coord_3D)
Definition at line 8 of file get_plane.c.
References plane::A, plane::B, plane::C, plane::D, coord_3D::i, coord_3D::j, and coord_3D::k.
{
plane p;
p.A=(two.j-one.j)*(three.k-one.k)-(three.j-one.j)*(two.k-one.k);
p.B=(two.k-one.k)*(three.i-one.i)-(three.k-one.k)*(two.i-one.i);
p.C=(two.i-one.i)*(three.j-one.j)-(three.i-one.i)*(two.j-one.j);
p.D=-(p.A*one.i) - (p.B*one.j) - (p.C*one.k);
//dprint_coord_3D(one);
//dprint_coord_3D(two);
//dprint_coord_3D(three);
//dprint_plane(&p);
return p;
}
coord_3D get_residue_COM (residue * r, atype * ATYPE, int xs)
Definition at line 11 of file get_COM.c.
References residue::a, coord_3D::i, coord_3D::j, coord_3D::k, residue::m, atype::m, mywhine(), residue::na, atom::t, atom::x, and atom::xa.
{
int ta=0;
double tmm=0;
coord_3D c;
// calculate the molecular weight
for(ta=0;ta<r[0].na;ta++){
        tmm+=ATYPE[r[0].a[ta].t].m;
        }
//printf("the molecular weight is %f\n",tmm);
if(tmm==0){mywhine("molecular weight of molecule %s is zero.\n(Have types/masses been assigned?");}
r[0].m=tmm;
c.i=0;
c.j=0;
c.k=0;
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
// calculate the center of mass
if(xs==-1){
for(ta=0;ta<r[0].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        c.i+=r[0].a[ta].x.i*ATYPE[r[0].a[ta].t].m;
        c.j+=r[0].a[ta].x.j*ATYPE[r[0].a[ta].t].m;
        c.k+=r[0].a[ta].x.k*ATYPE[r[0].a[ta].t].m;
        }
        }
else{
for(ta=0;ta<r[0].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        c.i+=r[0].a[ta].xa[xs].i*ATYPE[r[0].a[ta].t].m;
        c.j+=r[0].a[ta].xa[xs].j*ATYPE[r[0].a[ta].t].m;
        c.k+=r[0].a[ta].xa[xs].k*ATYPE[r[0].a[ta].t].m;
        }
        }
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
c.i/=tmm;
c.j/=tmm;
c.k/=tmm;
//printf("center of mass is at: %20.12e %20.12e %20.12e \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
return c;
}
void initialize_assembly (assembly * A)
Definition at line 181 of file initialize_GLYstruct.c.
References assembly::b, assembly::boxh, assembly::boxl, assembly::COM, coord_3D::i, assembly::i, coord_3D::j, coord_3D::k, assembly::m, assembly::mass, assembly::mbs, assembly::nb, assembly::nm, assembly::nmbs, and assembly::nVP.
                                      { // structure for groups of molecules within a larger structure
A[0].i=0; // index
A[0].mass=0; // mass of assembly
A[0].COM.i=A[0].COM.j=A[0].COM.k=0; // center of mass
A[0].nm=0; // number of molecule structures
A[0].m=(molecule**)calloc(1,sizeof(molecule*)); // nm of these
A[0].nb=0; // number of bonds/connections between molecules (H-bonds, for example)
A[0].b=(molbond*)calloc(1,sizeof(molbond)); // nmb of these descriptions of connection
A[0].nmbs=0; // number of sets of connections between molecules (for example, linear chains)
A[0].mbs=(molbondset*)calloc(1,sizeof(molbondset)); // nmbs of these sets
A[0].boxl.i=A[0].boxl.j=A[0].boxl.k=0; // center of mass
A[0].boxh.i=A[0].boxh.j=A[0].boxh.k=0; // center of mass
A[0].nVP=0; // number of void structures
return;
}
void initialize_atom (atom * a)
Definition at line 107 of file initialize_GLYstruct.c.
References atom::b, atom::d, atom::i, coord_3D::i, coord_3D::j, coord_3D::k, atom::mb, atom::n, atom::nalt, atom::nb, atom::nd, atom::ni, atom::nmb, atom::nvec, atom::nVP, atom::t, atom::v, atom::x, and atom::xa.
{
a[0].n=0; // atom number or other identifying index
a[0].t=0; // type number -- must correspond to assignments of "atype" (see)
a[0].nb=0; // number of actual bonds (not expected bonds)
a[0].b=(bond*)calloc(1,sizeof(bond)); // bond structures (nb of these)
a[0].nmb=0; // number of bonds to other residues or molecules
a[0].mb=(molbond*)calloc(1,sizeof(molbond)); // nmb of these
a[0].x.i=a[0].x.j=a[0].x.k=0; // atom's coordinates
a[0].nalt=0; // number of alternate coordinate sets
a[0].xa=(coord_3D*)calloc(1,sizeof(coord_3D)); // nalt of alternate coords
a[0].nvec=0; // number of vector sets
a[0].v=(vectormag_3D*)calloc(1,sizeof(vectormag_3D)); // vector sets
a[0].ni=0; // number of other indices
a[0].i=(int*)calloc(1,sizeof(int)); // other indices, as needed (ni of these)
a[0].nd=0; // number of double-precision parameters
a[0].d=(double*)calloc(1,sizeof(double)); // other parameters, as needed (nd of these)
a[0].nVP=0; // number of void structures
return;
}
void initialize_atype (atype * at)
Definition at line 30 of file initialize_GLYstruct.c.
References atype::bo, atype::m, atype::n, atype::nb, and atype::nlp.
{
at[0].n=0; // atomic number
at[0].nb=0; // number of typical bonds for this atom type
at[0].nlp=0; // number of typical lone pairs (to check geometry sanity)
at[0].m=0; // mass of element type
at[0].bo=(double*)calloc(1,sizeof(double)); // typical bond orders (nb of these)
return;
}
void initialize_bond (bond * b)
Definition at line 81 of file initialize_GLYstruct.c.
References bond::o, bond::s, and bond::t.
{
b[0].s=0; // "source" -- index to first atom in bond
b[0].t=0; // "target" -- index to the other atom in the bond
b[0].o=0; // order of bond
return;
}
void initialize_bondset (bondset * bs)
Definition at line 88 of file initialize_GLYstruct.c.
References bondset::b, and bondset::n.
{
bs[0].n=0; // number of bonds
bs[0].b=(bond*)calloc(1,sizeof(bond)); // n of these
return;
}
void initialize_coord_3D (coord_3D * c)
Definition at line 15 of file initialize_GLYstruct.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
{
c[0].i=c[0].j=c[0].k=0;
return;
}
void initialize_dockinfo (dockinfo * di)
Definition at line 173 of file initialize_GLYstruct.c.
{
printf("This program will exit now, because it requests initialization of\n");
printf("a dockinfo structure, but dockinfo structures should be initialized\n");
printf("within the main program.\n");
exit(1);
return;
}
void initialize_ensemble (ensemble * E)
Definition at line 197 of file initialize_GLYstruct.c.
References ensemble::a, ensemble::boxh, ensemble::boxl, ensemble::COM, coord_3D::i, ensemble::i, coord_3D::j, coord_3D::k, ensemble::m, ensemble::mass, ensemble::na, ensemble::nm, and ensemble::nVP.
                                      { // structure for a larger group of molecules, assemblies, etc.
E[0].i=0; // index
E[0].mass=0; // mass of ensemble
E[0].COM.i=E[0].COM.j=E[0].COM.k=0; // center of mass
E[0].nm=0; // number of molecule structures
E[0].m=(molecule*)calloc(1,sizeof(molecule)); // nm of these
E[0].na=0; // number of assembly structures
E[0].a=(assembly*)calloc(1,sizeof(assembly)); // na of these
E[0].boxl.i=E[0].boxl.j=E[0].boxl.k=0; // center of mass
E[0].boxh.i=E[0].boxh.j=E[0].boxh.k=0; // center of mass
E[0].nVP=0; // number of void structures
return;
}
void initialize_ensindex (ensindex * ei)
Definition at line 71 of file initialize_GLYstruct.c.
References ensindex::a, ensindex::A, ensindex::E, ensindex::i, ensindex::m, and ensindex::r.
{
ei[0].i=0; // general index
ei[0].E=0; // ensemble
ei[0].A=0; // assembly
ei[0].m=0; // molecule index
ei[0].r=0; // residue index
ei[0].a=0; // atom index
return;
}
void initialize_molbond (molbond * mb)
Definition at line 94 of file initialize_GLYstruct.c.
References molindex::a, molindex::i, molindex::m, molbond::o, molindex::r, molbond::s, and molbond::t.
{
mb[0].s.i=mb[0].s.m=mb[0].s.r=mb[0].s.a=0;
mb[0].t.i=mb[0].t.m=mb[0].t.r=mb[0].t.a=0;
mb[0].o=0; // order
return;
}
void initialize_molbondset (molbondset * mbs)
Definition at line 101 of file initialize_GLYstruct.c.
References molbondset::b, and molbondset::n.
{
mbs[0].n=0;  // source & target atoms for bond
mbs[0].b=(molbond*)calloc(1,sizeof(molbond)); // order
return;
}
void initialize_molecule (molecule * m)
Definition at line 150 of file initialize_GLYstruct.c.
References molecule::boxh, molecule::boxl, molecule::COM, molecule::d, coord_3D::i, molecule::i, coord_3D::j, coord_3D::k, molecule::m, molecule::na, molecule::nd, molecule::noi, molecule::nr, molecule::nrb, molecule::nrbs, molecule::nrc, molecule::nVP, molecule::oi, molecule::r, molecule::rb, molecule::rbs, and molecule::rc.
{
m[0].i=0; // index
m[0].m=0; // molecular weight
m[0].COM.i=m[0].COM.j=m[0].COM.k=0; // center of mass for molecule
m[0].na=0; // total number of atoms in molecule
m[0].nr=0; // number of residues
m[0].r=(residue*)calloc(1,sizeof(residue)); // pointers to residues
m[0].nrb=0; // number of bonds between residues
m[0].rb=(molbond*)calloc(1,sizeof(molbond)); // nrb of these descriptions of bonds
m[0].nrbs=0; // number of sets of bonds between residues (for example, linear chains)
m[0].rbs=(molbondset*)calloc(1,sizeof(molbondset)); // nrbs of these sets
m[0].nrc=0; // number of additional reference coordinates (rings, for example)
m[0].rc=(coord_3D*)calloc(1,sizeof(coord_3D)); // nrc of these
m[0].boxl.i=m[0].boxl.j=m[0].boxl.k=0;
m[0].boxh.i=m[0].boxh.j=m[0].boxh.k=0;
m[0].noi=0; // number of other indices
m[0].oi=(int*)calloc(1,sizeof(int)); // other indices, as needed (ni of these)
m[0].nd=0; // number of double-precision parameters
m[0].d=(double*)calloc(1,sizeof(double)); // other parameters, as needed (nd of these)
m[0].nVP=0; // number of void structures
return;
}
void initialize_molindex (molindex * mi)
Definition at line 63 of file initialize_GLYstruct.c.
References molindex::a, molindex::i, molindex::m, and molindex::r.
{
mi[0].i=0; // general index
mi[0].m=0; // molecule index
mi[0].r=0; // residue index
mi[0].a=0; // atom index
return;
}
void initialize_mtype (mtype * mt)
Definition at line 47 of file initialize_GLYstruct.c.
References mtype::c, and mtype::nVP.
{
mt[0].c=0; // type class (amino acid, glycan, solvent, etc.)
mt[0].nVP=0; // number of other information
return;
}
void initialize_plane (plane * p)
Definition at line 25 of file initialize_GLYstruct.c.
References plane::A, plane::B, plane::C, and plane::D.
{
p[0].A=p[0].B=p[0].C=p[0].D=0;
return;
}
void initialize_residue (residue * r)
Definition at line 127 of file initialize_GLYstruct.c.
References residue::a, residue::bs, residue::COM, residue::d, residue::i, coord_3D::i, coord_3D::j, coord_3D::k, residue::m, residue::n, residue::na, residue::nbs, residue::nd, residue::ni, residue::nr, residue::nrbs, residue::nrc, residue::nrp, residue::nVP, residue::rbs, residue::rc, and residue::rp.
{
r[0].n=0; // residue number given in input file
r[0].na=0; // number of atoms in residue
r[0].m=0; // molecular weight
r[0].COM.i=r[0].COM.j=r[0].COM.k=0; // center of mass for molecule
r[0].a=(atom*)calloc(1,sizeof(atom)); // atom structures (na of these)
r[0].nbs=0; // number of bond sets
r[0].bs=(bondset*)calloc(1,sizeof(bondset)); // (consecutive bonds, use these for plotting, etc.)
r[0].nr=0; // number of simple rings (no cage structures, etc.)
r[0].nrbs=0; // number of ring bondsets defined
r[0].rbs=(bondset*)calloc(1,sizeof(bondset)); // bondsets for rings
r[0].nrc=0; // number of ring/reference coordinate sets defined
r[0].rc=(coord_3D*)calloc(1,sizeof(coord_3D)); // coordinates for ring/reference centers
r[0].nrp=0; // number of ring planes defined
r[0].rp=(plane*)calloc(1,sizeof(plane)); // equations for average/approximate/exact/etc. ring planes (where useful)
r[0].ni=0; // number of other indices
r[0].i=(int*)calloc(1,sizeof(int)); // other indices, as needed (ni of these)
r[0].nd=0; // number of double-precision parameters
r[0].d=(double*)calloc(1,sizeof(double)); // other parameters, as needed (nd of these)
r[0].nVP=0; // number of void structures
return;
}
void initialize_rtype (rtype * rt)
Definition at line 39 of file initialize_GLYstruct.c.
References rtype::ac, rtype::c, rtype::nac, and rtype::nVP.
{
rt[0].c=0; // main class (amino acid, glycan, solvent, etc.)
rt[0].nac=0;// number alternate classes
rt[0].ac=(int*)calloc(1,sizeof(int)); // number alternate classes, those classes
rt[0].nVP=0; // number of other information
return;
}
void initialize_types (types * t)
Definition at line 53 of file initialize_GLYstruct.c.
References types::a, types::m, types::na, types::nm, types::nr, and types::r.
{
t[0].na=0; // # of atom types
t[0].a=(atype*)calloc(1,sizeof(atype)); // na of these
t[0].nr=0; // # of residue types
t[0].r=(rtype*)calloc(1,sizeof(rtype)); // nr of these
t[0].nm=0; // # of molecule types
t[0].m=(mtype*)calloc(1,sizeof(mtype)); // nm of these
return;
}
void initialize_vectormag_3D (vectormag_3D * v)
Definition at line 20 of file initialize_GLYstruct.c.
References vectormag_3D::d, vectormag_3D::i, vectormag_3D::j, and vectormag_3D::k.
{
v[0].i=v[0].j=v[0].k=v[0].d=0;
return;
}
void normalize_molecule_vectors (molecule * , int , int)
Definition at line 11 of file normalize_molecule_vectors.c.
References residue::a, mywhine(), residue::na, normalize_vec(), molecule::nr, molecule::r, and atom::v.
{
int na=0,nb=0,nalloc=0;
int nuse=0,nsz=0,nbins=0;
// figure how big the vector array needs to be
if(n1>n2){nalloc=n1+1;}
else{nalloc=n2+1;}
// normalize the vectors
for(na=0;na<m[0].nr;na++){ // for each residue
        for(nb=0;nb<m[0].r[na].na;nb++){ // for each atom
                //make sure there is space...
                nuse=malloc_usable_size(m[0].r[na].a[nb].v);
                nsz=sizeof(vectormag_3D);
                if(nsz==0){mywhine("memory issue (sizeof(vectormag_3D) given as zero) in normalize_molecule_vectors.c");}
                nbins=nuse/nsz;
                if(nbins<nalloc){mywhine("insufficient memory in normalize_molecule_vectors");}
                m[0].r[na].a[nb].v[n2]=normalize_vec(m[0].r[na].a[nb].v[n1]);
                }  // for each atom
        } // for each residue
return;
}
vectormag_3D normalize_vec (vectormag_3D)
Definition at line 7 of file normalize_vec.c.
References vectormag_3D::d, vectormag_3D::i, vectormag_3D::j, and vectormag_3D::k.
Referenced by normalize_molecule_vectors(), rotate_vector_to_Z_list(), and rotate_vector_to_Z_M().
{
vectormag_3D nv;
double temp=0;
// don't trust entry in 'd' -- normalize now to be certain
temp=sqrt(v.i*v.i+v.j*v.j+v.k*v.k);
if(temp!=0){
        nv.i=v.i/temp;
        nv.j=v.j/temp;
        nv.k=v.k/temp;
        nv.d=1;
        }
else{ nv.i=nv.j=nv.k=nv.d=0; }
return nv;
}
void outputAsmblPDB (assembly * , char *)
Definition at line 77 of file outputPDB.c.
References coord_3D::i, coord_3D::j, coord_3D::k, myfopen(), atom::n, atom::N, molecule::nr, spacing(), and atom::x.
{
 //Tells the user what's going on
 printf("Writting file: %s...\n",file_name);
 FILE* file;
 char current_line[80] = ""; char temporary[40] = "";
 char* curLine = current_line; char* temp = temporary;
 char* resName; char* atmName;
 int i,j,k,atmTot,resNum,resTot;
 atom curAtm; molecule* mol;
 file = myfopen(file_name,"w");
 for(k = 0; k < (*asmbl).nm; k++)
 {
  mol = ((*asmbl).m+k)[0]; // changed by BLF on 20080622 -- might need revisiting
  resTot = (*mol).nr;
  for(i = 0; i < resTot; i++)
  {
   resName = (*((*mol).r+i)).N;
   resNum = (*((*mol).r+i)).n;
   atmTot = (*((*mol).r+i)).na;
   for(j = 0; j < atmTot; j++)
   {
    curAtm = (*((*((*mol).r+i)).a+j));
    atmName = curAtm.N;
    strcpy(curLine,"");
    strcat(curLine,"ATOM");
    sprintf(temp,"%d", curAtm.n);
    //Based on how large the atom # is, depends on the # of spaces
    strcat(curLine,spacing(strlen(temp),7));
    //"ATOM atom# atom_name"
    sprintf(temp,"%d  %s", curAtm.n, atmName);
    strcat(curLine,temp);
    //Based on how many char are in the residue name, "   " spaces
    strcat(curLine,spacing(strlen(atmName),4));
    //"ATOM atom# atom_name res_name"
    strcat(curLine,resName);
    sprintf(temp,"%d",resNum);
    //Based on how large the residue # is, "              " spaces
    strcat(curLine,spacing(strlen(temp),6));
    //"ATOM atom# atom_name res_name res#"
    strcat(curLine,temp);
    sprintf(temp,"%.3lf",curAtm.x.i);
    //Based on how large the x cordinate is, "            " spaces
    strcat(curLine,spacing(strlen(temp),12));
    //"ATOM atom# atom_name res_name x"
    strcat(curLine,temp);
    sprintf(temp,"%.3lf",curAtm.x.j);
    //Based on how large the y cordinate is, "            " spaces
    strcat(curLine,spacing(strlen(temp),8));
    //"ATOM atom# atom_name res_name x y"
    strcat(curLine,temp);
    sprintf(temp,"%.3lf",curAtm.x.k);
    //Based on how large the z cordinate is, "            " spaces
    strcat(curLine,spacing(strlen(temp),8));
    //"ATOM atom# atom_name res_name x y z 1.00 0.00"
    sprintf(temp,"%.3lf  1.00  0.00",curAtm.x.k);
    strcat(curLine,temp);
    //Output the line to the new .pbd file
    fprintf(file,"%s\n",curLine);
   }
  }
  fprintf(file,"TER   \n");
 }
 fclose(file);
}
void outputMolPDB (molecule * , char *)
Definition at line 10 of file outputPDB.c.
References coord_3D::i, coord_3D::j, coord_3D::k, myfopen(), atom::n, atom::N, spacing(), and atom::x.
{
 //Tells the user what's going on
 printf("Writting file: %s...\n",file_name);
 FILE* file;
 char current_line[80] = ""; char temporary[40] = "";
 char* curLine = current_line; char* temp = temporary;
 char* resName; char* atmName;
 int i; int j; int atmTot; int resNum; int resTot = (*mol).nr;
 atom curAtm;
 file = myfopen(file_name,"w");
 for(i = 0; i < resTot; i++)
 {
  resName = (*((*mol).r+i)).N;
  resNum = (*((*mol).r+i)).n;
  atmTot = (*((*mol).r+i)).na;
  for(j = 0; j < atmTot; j++)
  {
   curAtm = (*((*((*mol).r+i)).a+j));
   atmName = curAtm.N;
   strcpy(curLine,"");
   strcat(curLine,"ATOM");
   sprintf(temp,"%d", curAtm.n);
   //Based on how large the atom # is, depends on the # of spaces
   strcat(curLine,spacing(strlen(temp),7));
   //"ATOM atom# atom_name"
   sprintf(temp,"%d  %s", curAtm.n, atmName);
   strcat(curLine,temp);
   //Based on how many char are in the residue name, "   " spaces
   strcat(curLine,spacing(strlen(atmName),4));
   //"ATOM atom# atom_name res_name"
   strcat(curLine,resName);
   sprintf(temp,"%d",resNum);
   //Based on how large the residue # is, "              " spaces
   strcat(curLine,spacing(strlen(temp),6));
   //"ATOM atom# atom_name res_name res#"
   strcat(curLine,temp);
   sprintf(temp,"%.3lf",curAtm.x.i);
   //Based on how large the x cordinate is, "            " spaces
   strcat(curLine,spacing(strlen(temp),12));
   //"ATOM atom# atom_name res_name x"
   strcat(curLine,temp);
   sprintf(temp,"%.3lf",curAtm.x.j);
   //Based on how large the y cordinate is, "            " spaces
   strcat(curLine,spacing(strlen(temp),8));
   //"ATOM atom# atom_name res_name x y"
   strcat(curLine,temp);
   sprintf(temp,"%.3lf",curAtm.x.k);
   //Based on how large the z cordinate is, "            " spaces
   strcat(curLine,spacing(strlen(temp),8));
   //"ATOM atom# atom_name res_name x y z 1.00 0.00"
   sprintf(temp,"%.3lf  1.00  0.00",curAtm.x.k);
   strcat(curLine,temp);
   //Output the line to the new .pbd file
   fprintf(file,"%s\n",curLine);
  }
 }
 fclose(file);
}
void pitchAssembly (assembly * , double)
Definition at line 103 of file rotation.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
{
  //Tells the user what's going on
  printf("Pitching assembly approx. %.0lf degrees...\n",(rad*57.2957795));
  int i,j,k;
  molecule* mol; residue* curRes; atom* curAtm;
  coord_3D temp; temp.i = 0; temp.j = 0; temp.k = 0;
  for(k = 0; k < (*asmbl).nm; k++)
  {
   mol = ((*asmbl).m+k)[0]; // changed by BLF on 20080622 -- might need revisiting
   for(i = 0; i < (*mol).nr; i++)
   {
    curRes = ((*mol).r+i);
    for(j = 0; j < (*curRes).na; j++)
    {
     curAtm = ((*curRes).a+j);
     //Rotating about the Y-axis
     temp.i=((*curAtm).x.i*cos(rad))+((*curAtm).x.k*-sin(rad));
     (*curAtm).x.j = (*curAtm).x.j;
     temp.k=((*curAtm).x.i*sin(rad))+((*curAtm).x.k*cos(rad));
     (*curAtm).x.i = temp.i; (*curAtm).x.k = temp.k;
    }
   }
  }
}
void pitchMolecule (molecule * , double)
Definition at line 30 of file rotation.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
{
  //Tells the user what's going on
  printf("Pitching molecule approx. %.0lf degrees...\n",(rad*57.2957795));
  int i,j;
  residue* curRes; atom* curAtm;
  coord_3D temp; temp.i = 0; temp.j = 0; temp.k = 0;
  for(i = 0; i < (*mol).nr; i++)
  {
   curRes = ((*mol).r+i);
   for(j = 0; j < (*curRes).na; j++)
   {
    curAtm = ((*curRes).a+j);
    //Rotating about the Y-axis
    temp.i=((*curAtm).x.i*cos(rad))+((*curAtm).x.k*-sin(rad));
    (*curAtm).x.j = (*curAtm).x.j;
    temp.k=((*curAtm).x.i*sin(rad))+((*curAtm).x.k*cos(rad));
    (*curAtm).x.i = temp.i; (*curAtm).x.k = temp.k;
   }
  }
}
void print_atom (atom * , int)
void print_atype (atype * , int)
void print_bond (bond *)
void print_bondset (bondset * , int)
void print_coord_3D (coord_3D *)
void print_molecule (molecule * , int)
void print_plane (plane *)
void print_residue (residue * , int)
void print_vectormag_3D (vectormag_3D *)
void rollAssembly (assembly * , double)
Definition at line 76 of file rotation.c.
References coord_3D::i, coord_3D::j, coord_3D::k, and atom::x.
{
  //Tells the user what's going on
  printf("Rolling assembly approx. %.0lf degrees...\n",(rad*57.2957795));
  int i,j,k;
  molecule* mol; residue* curRes; atom* curAtm;
  coord_3D temp; temp.i = 0; temp.j = 0; temp.k = 0;
  for(k = 0; k < (*asmbl).nm; k++)
  {
   mol = ((*asmbl).m+k)[0]; // changed by BLF on 20080622 -- might need revisiting
   for(i = 0; i < (*mol).nr; i++)
   {
    curRes = ((*mol).r+i);
    for(j = 0; j < (*curRes).na; j++)
    {
     curAtm = ((*curRes).a+j);
     //Rotating about the X-axis
     (*curAtm).x.i = (*curAtm).x.i;
     temp.j=((*curAtm).x.j*cos(rad))+((*curAtm).x.k*sin(rad));
     temp.k=((*curAtm).x.j*-sin(rad))+((*curAtm).x.k*cos(rad));
     (*curAtm).x.j = temp.j; (*curAtm).x.k = temp.k;
    }
   }
  }
}
void rollMolecule (molecule * , double)
Definition at line 7 of file rotation.c.
References coord_3D::i, coord_3D::j, coord_3D::k, and atom::x.
{
  //Tells the user what's going on
  printf("Rolling molecule approx. %.0lf degrees...\n",(rad*57.2957795));
  int i,j;
  residue* curRes; atom* curAtm;
  coord_3D temp; temp.i = 0; temp.j = 0; temp.k = 0;
  for(i = 0; i < (*mol).nr; i++)
  {
   curRes = ((*mol).r+i);
   for(j = 0; j < (*curRes).na; j++)
   {
    curAtm = ((*curRes).a+j);
    //Rotating about the X-axis
    (*curAtm).x.i = (*curAtm).x.i;
    temp.j=((*curAtm).x.j*cos(rad))+((*curAtm).x.k*sin(rad));
    temp.k=((*curAtm).x.j*-sin(rad))+((*curAtm).x.k*cos(rad));
    (*curAtm).x.j = temp.j; (*curAtm).x.k = temp.k;
   }
  }
}
void rotate_vector_to_Z_list (coord_3D * , int , vectormag_3D)
Definition at line 47 of file rotate_vector_to_Z.c.
References vectormag_3D::d, get_crossprod(), coord_3D::i, vectormag_3D::i, coord_3D::j, vectormag_3D::j, coord_3D::k, vectormag_3D::k, mywhine(), and normalize_vec().
{
int ra=0;
vectormag_3D cX,cY,cZ; // direction cosines for X Y and Z
coord_3D RC; // temporary coords
// If the requested direction already points along z
if((v.i==0)&&(v.j==0)){ return; }
// get direction cosines for unit vector along new Z axis (the rotation axis)
cZ=normalize_vec(v);
if(cZ.d==0){mywhine("zero-length vector passed to rotate_vector_to_Z (can't rotate to that)");}
if(cZ.j!=0){ // if the j component of the target direction isn't zero
        // set abitrary point in new XY plane for positive Y position
        cY.i=cZ.i; // set xY=iZ
        cY.k=cZ.k; // set zY=kZ
        cY.j=-(cZ.k*cZ.k+cZ.i*cZ.i)/cZ.j;  ; // solve for yY in X-Y plane
        // turn that into a unit vector (make into direction cosines)
        cY=normalize_vec(cY);
        // get direction cosines for unit vector along new X axis
        // (this is the X-prod of the new Y and Z axes)
        cX=get_crossprod(cZ,cY);
        }
else{ // the i component isn't zero (or we would have exited)
        // set abitrary point in new XY plane for positive X position
        cX.j=cZ.j; // set yX=jZ, which is zero or we wouldn't be here...
        cX.k=cZ.k; // set zX=kZ
        cX.i=-(cZ.k*cZ.k)/cZ.i;  ; // solve for yY in X-Y plane
        // turn that into a unit vector (make into direction cosines)
        cX=normalize_vec(cX);
        // get direction cosines for unit vector along new X axis
        // (this is the X-prod of the new Y and Z axes)
        cY=get_crossprod(cZ,cX);
        }
// rotate molecule
for(ra=0;ra<n;ra++){ // for each residue
        RC.i=cX.i*XS[ra].i + cX.j*XS[ra].j + cX.k*XS[ra].k;
        RC.j=cY.i*XS[ra].i + cY.j*XS[ra].j + cY.k*XS[ra].k;
        RC.k=cZ.i*XS[ra].i + cZ.j*XS[ra].j + cZ.k*XS[ra].k;
        XS[ra]=RC;
        }
return;
}
void rotate_vector_to_Z_M (molecule * , int , int , int , int , vectormag_3D)
Definition at line 94 of file rotate_vector_to_Z.c.
References residue::a, vectormag_3D::d, dprint_coord_3D(), dprint_vectormag_3D(), get_crossprod(), get_magnitude(), coord_3D::i, vectormag_3D::i, coord_3D::j, vectormag_3D::j, coord_3D::k, vectormag_3D::k, mywhine(), residue::na, normalize_vec(), molecule::nr, molecule::r, atom::v, atom::x, and atom::xa.
{
int ra=0,rb=0,localdebug=0;;
vectormag_3D cX,cY,cZ,RV; // direction cosines for X Y and Z
residue *R; // residue pointer for convenience
coord_3D RC;
// get direction cosines for unit vector along new Z axis (the rotation axis)
if(localdebug>=2){
printf("in rotate_vector_to_Z_M xs is %d ; xl is %d ; vs is %d ; vl is %d \n",xs,xl,vs,vl);
printf("normalizing rotation vector.  Before (v) \n");
dprint_vectormag_3D(&v);
}
// If the requested direction already points along z
if((v.i==0)&&(v.j==0)){ return; }
// get direction cosines for unit vector along new Z axis (the rotation axis)
cZ=normalize_vec(v);
if(localdebug>=2){
printf("normalizing rotation vector.  After (cZ)\n");
dprint_vectormag_3D(&cZ);
}
if(cZ.d==0){mywhine("zero-length vector passed to rotate_vector_to_Z (can't rotate to that)");}
if(cZ.j!=0){ // if the j component of the target direction isn't zero
        // set abitrary point in new XY plane for positive Y position
        cY.i=cZ.i; // set xY=iZ
        cY.k=cZ.k; // set zY=kZ
        cY.j=-(cZ.k*cZ.k+cZ.i*cZ.i)/cZ.j;  ; // solve for yY in X-Y plane
        // turn that into a unit vector (make into direction cosines)
if(localdebug>=2){
printf("normalizing Y axis vector. Before:\n");
dprint_vectormag_3D(&cY);
}
        cY=normalize_vec(cY);
if(localdebug>=2){
printf("normalized Y axis vector:\n");
dprint_vectormag_3D(&cY);
}
        // get direction cosines for unit vector along new X axis
        // (this is the X-prod of the new Y and Z axes)
        cX=get_crossprod(cZ,cY);
if(localdebug>=2){
printf("Just got X axis vector:\n");
dprint_vectormag_3D(&cX);
}
        }
else{ // the i component isn't zero (or we would have exited)
        // set abitrary point in new XY plane for positive X position
        cX.j=cZ.j; // set yX=jZ, which is zero or we wouldn't be here...
        cX.k=cZ.k; // set zX=kZ
        cX.i=-(cZ.k*cZ.k)/cZ.i;  ; // solve for yY in X-Y plane
        // turn that into a unit vector (make into direction cosines)
if(localdebug>=2){
printf("normalizing X axis vector (cZ.j=0).  Before:\n");
dprint_vectormag_3D(&cX);
}
        cX=normalize_vec(cX);
if(localdebug>=2){
printf("normalized X axis vector:\n");
dprint_vectormag_3D(&cX);
}
        // get direction cosines for unit vector along new X axis
        // (this is the X-prod of the new Y and Z axes)
        cY=get_crossprod(cZ,cX);
if(localdebug>=2){
printf("Just got Y axis vector:\n");
dprint_vectormag_3D(&cY);
}
        }
//dprint_molecule(&m[0],24);
//dprint_residue(&m[0].r[0],24);
//printf("m[0].nr is %d\n",m[0].nr);
// rotate molecule
if((xs==-1)&&(xl==-1)){ //this makes code harder to read, but execution faster
if(localdebug>=2){
printf("(xs==-1)&&(xl==-1)\n");
printf("m[0].nr is %d\n",m[0].nr);
}
for(ra=0;ra<m[0].nr;ra++){ // for each residue
        R=&m[0].r[ra]; // this isn't necessary, and certainly slows the execution
                //by a few nanoseconds, bit it makes reading the code a bit easier
        for(rb=0;rb<R[0].na;rb++){ // for each atom
                RC.i=cX.i*R[0].a[rb].x.i + cX.j*R[0].a[rb].x.j + cX.k*R[0].a[rb].x.k;
                RC.j=cY.i*R[0].a[rb].x.i + cY.j*R[0].a[rb].x.j + cY.k*R[0].a[rb].x.k;
                RC.k=cZ.i*R[0].a[rb].x.i + cZ.j*R[0].a[rb].x.j + cZ.k*R[0].a[rb].x.k;
                R[0].a[rb].x=RC;
if(localdebug>=2){dprint_coord_3D(&R[0].a[rb].x); }
                } // for each atom
        } // for each residue
        }
if((xs!=-1)&&(xl==-1)){ //this makes code harder to read, but execution faster
for(ra=0;ra<m[0].nr;ra++){ // for each residue
        R=&m[0].r[ra]; // this isn't necessary, and certainly slows the execution
                //by a few nanoseconds, bit it makes reading the code a bit easier
        for(rb=0;rb<R[0].na;rb++){ // for each atom
                RC.i=cX.i*R[0].a[rb].xa[xs].i + cX.j*R[0].a[rb].xa[xs].j + cX.k*R[0].a[rb].xa[xs].k;
                RC.j=cY.i*R[0].a[rb].xa[xs].i + cY.j*R[0].a[rb].xa[xs].j + cY.k*R[0].a[rb].xa[xs].k;
                RC.k=cZ.i*R[0].a[rb].xa[xs].i + cZ.j*R[0].a[rb].xa[xs].j + cZ.k*R[0].a[rb].xa[xs].k;
                R[0].a[rb].x=RC;
if(localdebug>=2){dprint_coord_3D(&R[0].a[rb].x); }
                } // for each atom
        } // for each residue
        }
if((xs==-1)&&(xl!=-1)){ //this makes code harder to read, but execution faster
for(ra=0;ra<m[0].nr;ra++){ // for each residue
        R=&m[0].r[ra]; // this isn't necessary, and certainly slows the execution
                //by a few nanoseconds, bit it makes reading the code a bit easier
        for(rb=0;rb<R[0].na;rb++){ // for each atom
                RC.i=cX.i*R[0].a[rb].x.i + cX.j*R[0].a[rb].x.j + cX.k*R[0].a[rb].x.k;
                RC.j=cY.i*R[0].a[rb].x.i + cY.j*R[0].a[rb].x.j + cY.k*R[0].a[rb].x.k;
                RC.k=cZ.i*R[0].a[rb].x.i + cZ.j*R[0].a[rb].x.j + cZ.k*R[0].a[rb].x.k;
                R[0].a[rb].xa[xl]=RC;
if(localdebug>=2){dprint_coord_3D(&R[0].a[rb].x); }
                } // for each atom
        } // for each residue
        }
if((xs!=-1)&&(xl!=-1)){ //this makes code harder to read, but execution faster
for(ra=0;ra<m[0].nr;ra++){ // for each residue
        R=&m[0].r[ra]; // this isn't necessary, and certainly slows the execution
                //by a few nanoseconds, bit it makes reading the code a bit easier
        for(rb=0;rb<R[0].na;rb++){ // for each atom
                RC.i=cX.i*R[0].a[rb].xa[xs].i + cX.j*R[0].a[rb].xa[xs].j + cX.k*R[0].a[rb].xa[xs].k;
                RC.j=cY.i*R[0].a[rb].xa[xs].i + cY.j*R[0].a[rb].xa[xs].j + cY.k*R[0].a[rb].xa[xs].k;
                RC.k=cZ.i*R[0].a[rb].xa[xs].i + cZ.j*R[0].a[rb].xa[xs].j + cZ.k*R[0].a[rb].xa[xs].k;
                R[0].a[rb].xa[xl]=RC;
if(localdebug>=2){dprint_coord_3D(&R[0].a[rb].x); }
                } // for each atom
        } // for each residue
        }
// if vector rotation is specified
if((vs>=0)&&(vl>=0)){
for(ra=0;ra<m[0].nr;ra++){ // for each residue
        R=&m[0].r[ra]; // this isn't necessary, and certainly slows the execution
                //by a few nanoseconds, bit it makes reading the code a bit easier
        for(rb=0;rb<R[0].na;rb++){ // for each atom
                RV.i=cX.i*R[0].a[rb].v[vs].i + cX.j*R[0].a[rb].v[vs].j + cX.k*R[0].a[rb].v[vs].k;
                RV.j=cY.i*R[0].a[rb].v[vs].i + cY.j*R[0].a[rb].v[vs].j + cY.k*R[0].a[rb].v[vs].k;
                RV.k=cZ.i*R[0].a[rb].v[vs].i + cZ.j*R[0].a[rb].v[vs].j + cZ.k*R[0].a[rb].v[vs].k;
                RV.d=get_magnitude(RV); // not that it should change...
                R[0].a[rb].v[vl]=RV;
if(localdebug>=2){
        printf("Source (%d), intermediate and rotated (%d) vectors for set %d:\n",vs,vl,rb);
        dprint_vectormag_3D(&R[0].a[rb].v[vs]);
        dprint_vectormag_3D(&RV);
        dprint_vectormag_3D(&R[0].a[rb].v[vl]);
        }
                } // for each atom
        } // for each residue
        }
return;
}
coord_3D scalarmult_coord (coord_3D , double)
Definition at line 29 of file add_coord.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
Referenced by shift_molecule_atoms_by_vector_scale().
{
coord_3D nc;
nc.i=ca.i*cb;
nc.j=ca.j*cb;
nc.k=ca.k*cb;
return nc;
}
vectormag_3D scalarmult_vec (vectormag_3D , double)
Definition at line 5 of file scalarmult_vec.c.
References vectormag_3D::d, vectormag_3D::i, vectormag_3D::j, and vectormag_3D::k.
{
vectormag_3D nv;
nv.i=v.i*s;
nv.j=v.j*s;
nv.k=v.k*s;
// don't trust the d in nv
nv.d=sqrt(nv.i*nv.i+nv.j*nv.j+nv.k*nv.k);
return nv;
}
void shift_molecule_atoms_by_vector_scale (molecule * m, int xs, int xt, int vr, double scale)
Definition at line 21 of file vector_movements.c.
References residue::a, add_coord(), mywhine(), residue::na, molecule::nr, molecule::r, scalarmult_coord(), vec_to_coord(), atom::x, and atom::xa.
{
int ta=0,tb,tuse=0,tsz=0,tbins=0;
coord_3D c;
// move atoms by scale * vector
if((xs==-1)&&(xt==-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        c=scalarmult_coord(vec_to_coord(m[0].r[ta].a[tb].v[vr]),scale);
                        m[0].r[ta].a[tb].x=add_coord(m[0].r[ta].a[tb].x,c);
                        }
                }
        }
if((xs!=-1)&&(xt==-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        tuse=malloc_usable_size(m[0].r[ta].a[tb].xa);
                        tsz=sizeof(coord_3D);
                        tbins=tuse/tsz;
                        if(tbins<(xs+1)){mywhine("memory issue: source coords (1) not allocated in shift_molecule_atoms_by_vector_scale");}
                        c=scalarmult_coord(vec_to_coord(m[0].r[ta].a[tb].v[vr]),scale);
                        m[0].r[ta].a[tb].x=add_coord(m[0].r[ta].a[tb].xa[xs],c);
                        }
                }
        }
if((xs==-1)&&(xt!=-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        tuse=malloc_usable_size(m[0].r[ta].a[tb].xa);
                        tsz=sizeof(coord_3D);
                        tbins=tuse/tsz;
                        if(tbins<(xt+1)){mywhine("memory issue: translated coords (1) not allocated in shift_molecule_atoms_by_vector_scale");}
                        c=scalarmult_coord(vec_to_coord(m[0].r[ta].a[tb].v[vr]),scale);
                        m[0].r[ta].a[tb].xa[xt]=add_coord(m[0].r[ta].a[tb].x,c);
                        }
                }
        }
if((xs!=-1)&&(xt!=-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        tuse=malloc_usable_size(m[0].r[ta].a[tb].xa);
                        tsz=sizeof(coord_3D);
                        tbins=tuse/tsz;
                        if(tbins<(xs+1)){mywhine("memory issue: source coords (2) not allocated in shift_molecule_atoms_by_vector_scale");}
                        if(tbins<(xt+1)){mywhine("memory issue: translated coords (2) not allocated in shift_molecule_atoms_by_vector_scale");}
                        c=scalarmult_coord(vec_to_coord(m[0].r[ta].a[tb].v[vr]),scale);
                        m[0].r[ta].a[tb].xa[xt]=add_coord(m[0].r[ta].a[tb].xa[xs],c);
                        }
                }
        }
return;
}
char* spacing (int , int)
Definition at line 149 of file outputPDB.c.
Referenced by outputAsmblPDB(), and outputMolPDB().
{
 char returning[15] = ""; char* ret = returning;
 int i;
 for(i = 0; i < totLen - strLen; i++)
  strcat(ret," ");
 return ret;
}
coord_3D subtract_coord (coord_3D , coord_3D)
Definition at line 18 of file add_coord.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
Referenced by get_alt_rms_mol(), get_alt_rms_res(), and translate_zero_to_coord_M().
{
coord_3D nc;
nc.i=ca.i-cb.i;
nc.j=ca.j-cb.j;
nc.k=ca.k-cb.k;
return nc;
}
vectormag_3D subtract_vec (vectormag_3D , vectormag_3D)
Definition at line 21 of file add_vec.c.
References vectormag_3D::d, vectormag_3D::i, vectormag_3D::j, and vectormag_3D::k.
{
vectormag_3D nv;
nv.i=va.i-vb.i;
nv.j=va.j-vb.j;
nv.k=va.k-vb.k;
// don't trust the d in nv
nv.d=sqrt(nv.i*nv.i+nv.j*nv.j+nv.k*nv.k);
return nv;
}
void translate_to_COM (molecule * , atype * , int)
Definition at line 15 of file translate_to_COM.c.
References residue::a, molecule::COM, coord_3D::i, coord_3D::j, coord_3D::k, atype::m, mywhine(), residue::na, molecule::r, atom::t, atom::x, and atom::xa.
{
int ta=0,tuse=0,tsz=0,tbins=0;
double tmm=0;
// calculate the molecular weight of residue 0 (the molecule, here)
for(ta=0;ta<m[0].r[0].na;ta++){
        tmm+=ATYPE[m[0].r[0].a[ta].t].m;
        }
//printf("the molecular weight is %f\n",tmm);
if(tmm==0){mywhine("molecular weight of molecule %s is zero.\n(Have types/masses been assigned?");}
// glucose $molwt=174.078;
m[0].COM.i=0;
m[0].COM.j=0;
m[0].COM.k=0;
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
// calculate the center of mass
for(ta=0;ta<m[0].r[0].na;ta++){ // COM = sum(m_i * r_i) / sum(m_i)
        m[0].COM.i+=m[0].r[0].a[ta].x.i*ATYPE[m[0].r[0].a[ta].t].m;
        m[0].COM.j+=m[0].r[0].a[ta].x.j*ATYPE[m[0].r[0].a[ta].t].m;
        m[0].COM.k+=m[0].r[0].a[ta].x.k*ATYPE[m[0].r[0].a[ta].t].m;
        }
//printf("center of mass is at: %f %f %f \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
m[0].COM.i/=tmm;
m[0].COM.j/=tmm;
m[0].COM.k/=tmm;
//printf("center of mass is at: %20.12e %20.12e %20.12e \n",m[0].COM.i,m[0].COM.j,m[0].COM.k);
// move center of mass to specified location
if(tw==-1){
        for(ta=0;ta<m[0].r[0].na;ta++){ // xyz(new) = xyz(old) - COM
                m[0].r[0].a[ta].x.i-=m[0].COM.i;
                m[0].r[0].a[ta].x.j-=m[0].COM.j;
                m[0].r[0].a[ta].x.k-=m[0].COM.k;
                }
        }
else{
        for(ta=0;ta<m[0].r[0].na;ta++){ // xyz(new) = xyz(old) - COM
                tuse=malloc_usable_size(m[0].r[0].a[ta].xa);
                tsz=sizeof(coord_3D);
                if(tsz==0){mywhine("memory issue: sizeof(coord_3D) given as zero in translate_to_COM.c");}
                tbins=tuse/tsz;
                //print_coord_3D(&m[0].r[0].a[ta].x);
                if(tbins<(tw+1)){mywhine("insufficient memory allocated before translate_to_COM");}
                m[0].r[0].a[ta].xa[tw].i=m[0].r[0].a[ta].x.i-m[0].COM.i;
                m[0].r[0].a[ta].xa[tw].j=m[0].r[0].a[ta].x.j-m[0].COM.j;
                m[0].r[0].a[ta].xa[tw].k=m[0].r[0].a[ta].x.k-m[0].COM.k;
                }
        }
return;
}
void translate_zero_to_coord_M (molecule * , int , int , coord_3D)
Definition at line 12 of file translate_zero_to_coord.c.
References residue::a, mywhine(), residue::na, molecule::nr, molecule::r, subtract_coord(), atom::x, and atom::xa.
{
int ta=0,tb,tuse=0,tsz=0,tbins=0;
// move center of mass to specified location
if((xs==-1)&&(xt==-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        m[0].r[ta].a[tb].x=subtract_coord(m[0].r[ta].a[tb].x,c);
                        }
                }
        }
if((xs!=-1)&&(xt==-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        tuse=malloc_usable_size(m[0].r[ta].a[tb].xa);
                        tsz=sizeof(coord_3D);
                        tbins=tuse/tsz;
                        if(tbins<(xs+1)){mywhine("memory issue: source coords (1) not allocated in translate_zero_to_coord");}
                        m[0].r[ta].a[tb].x=subtract_coord(m[0].r[ta].a[tb].xa[xs],c);
                        }
                }
        }
if((xs==-1)&&(xt!=-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        tuse=malloc_usable_size(m[0].r[ta].a[tb].xa);
                        tsz=sizeof(coord_3D);
                        tbins=tuse/tsz;
                        if(tbins<(xt+1)){mywhine("memory issue: translated coords (1) not allocated in translate_zero_to_coord");}
                        m[0].r[ta].a[tb].xa[xt]=subtract_coord(m[0].r[ta].a[tb].x,c);
                        }
                }
        }
if((xs!=-1)&&(xt!=-1)){
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        tuse=malloc_usable_size(m[0].r[ta].a[tb].xa);
                        tsz=sizeof(coord_3D);
                        tbins=tuse/tsz;
                        if(tbins<(xs+1)){mywhine("memory issue: source coords (2) not allocated in translate_zero_to_coord");}
                        if(tbins<(xt+1)){mywhine("memory issue: translated coords (2) not allocated in translate_zero_to_coord");}
                        m[0].r[ta].a[tb].xa[xt]=subtract_coord(m[0].r[ta].a[tb].xa[xs],c);
                        }
                }
        }
return;
}
coord_3D vec_to_coord (vectormag_3D)
Definition at line 20 of file coord_to_vec.c.
References vectormag_3D::i, coord_3D::i, vectormag_3D::j, coord_3D::j, vectormag_3D::k, and coord_3D::k.
Referenced by shift_molecule_atoms_by_vector_scale().
{
coord_3D nc;
nc.i=v.i;
nc.j=v.j;
nc.k=v.k;
return nc;
}
void yawAssembly (assembly * , double)
Definition at line 130 of file rotation.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
{
  //Tells the user what's going on
  printf("Yawing assembly approx. %.0lf degrees...\n",(rad*57.2957795));
  int i,j,k;
  molecule* mol; residue* curRes; atom* curAtm;
  coord_3D temp; temp.i = 0; temp.j = 0; temp.k = 0;
  for(k = 0; k < (*asmbl).nm; k++)
  {
   mol = ((*asmbl).m+k)[0]; // changed by BLF on 20080622 -- might need revisiting
   for(i = 0; i < (*mol).nr; i++)
   {
    curRes = ((*mol).r+i);
    for(j = 0; j < (*curRes).na; j++)
    {
     curAtm = ((*curRes).a+j);
     //Rotating about the Z-axis
     temp.i=((*curAtm).x.i*cos(rad))+((*curAtm).x.j*sin(rad));
     temp.j=((*curAtm).x.i*-sin(rad))+((*curAtm).x.j*cos(rad));
     (*curAtm).x.i = temp.i; (*curAtm).x.j = temp.j;
     (*curAtm).x.k = (*curAtm).x.k;
    }
   }
  }
}
void yawMolecule (molecule * , double)
Definition at line 53 of file rotation.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
{
  //Tells the user what's going on
  printf("Yawing molecule approx. %.0lf degrees...\n",(rad*57.2957795));
  int i,j;
  residue* curRes; atom* curAtm;
  coord_3D temp; temp.i = 0; temp.j = 0; temp.k = 0;
  for(i = 0; i < (*mol).nr; i++)
  {
   curRes = ((*mol).r+i);
   for(j = 0; j < (*curRes).na; j++)
   {
    curAtm = ((*curRes).a+j);
    //Rotating about the Z-axis
    temp.i=((*curAtm).x.i*cos(rad))+((*curAtm).x.j*sin(rad));
    temp.j=((*curAtm).x.i*-sin(rad))+((*curAtm).x.j*cos(rad));
    (*curAtm).x.i = temp.i; (*curAtm).x.j = temp.j;
    (*curAtm).x.k = (*curAtm).x.k;
   }
  }
}
coord_3D zero_coord ()
Definition at line 19 of file zero_vec_crd.c.
References coord_3D::i, coord_3D::j, and coord_3D::k.
Referenced by read_prepres().
                     {
coord_3D nc;
nc.i=nc.j=nc.k=0;
return nc;
}
vectormag_3D zero_vec ()
Definition at line 9 of file zero_vec_crd.c.
References vectormag_3D::d, vectormag_3D::i, vectormag_3D::j, and vectormag_3D::k.
Referenced by get_molecule_point_charge_dipole().
                       {
vectormag_3D nv;
nv.i=nv.j=nv.k=nv.d=0;
return nv;
}
Variable Documentation
char* ATYPESFILE
Definition at line 12 of file molecules.h.
char * MTYPESFILE
Definition at line 12 of file molecules.h.
int NUMAT
Definition at line 302 of file molecules.h.
Referenced by ATYPE_init().
char * RTYPESFILE
Definition at line 12 of file molecules.h.