GLYLIB: get_dipole.c File Reference
get_dipole.c File Reference
#include <mylib.h>
#include <molecules.h>
Functions
vectormag_3D get_molecule_point_charge_dipole (molecule *m, int xs, int chgsrc, atype *AT)
Function Documentation
vectormag_3D get_molecule_point_charge_dipole (molecule * m, int xs, int chgsrc, atype * AT)
Definition at line 17 of file get_dipole.c.
References residue::a, atom::ch, vectormag_3D::d, get_magnitude(), get_molecule_COM(), coord_3D::i, vectormag_3D::i, coord_3D::j, vectormag_3D::j, coord_3D::k, vectormag_3D::k, mywhine(), residue::na, molecule::nr, molecule::r, atom::x, atom::xa, and zero_vec().
{
int ta=0,tb,tuse=0,tsz=0,tbins=0;
coord_3D com;
vectormag_3D dip;
dip = zero_vec();
// determine the center of mass
com=get_molecule_COM(m,AT,xs);
// calculate the dipole relative to the center of mass
if(xs==-1){
// sum over all charge*(x-COM)
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        dip.i+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].x.i-com.i);
                        dip.j+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].x.j-com.j);
                        dip.k+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].x.k-com.k);
                        }
                }
        }
else{
        for(ta=0;ta<m[0].nr;ta++){
                for(tb=0;tb<m[0].r[ta].na;tb++){
                        tuse=malloc_usable_size(m[0].r[ta].a[tb].xa);
                        tsz=sizeof(coord_3D);
                        tbins=tuse/tsz;
                        if(tbins<(xs+1)){mywhine("memory issue: source coords not allocated in get_molecule_point_charge_dipole");}
                        dip.i+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].xa[xs].i-com.i);
                        dip.j+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].xa[xs].j-com.j);
                        dip.k+=m[0].r[ta].a[tb].ch[chgsrc]*(m[0].r[ta].a[tb].xa[xs].k-com.k);
                        }
                }
        }
dip.d=get_magnitude(dip);
return dip;
}