GLYLIB: load_amber_prmtop.c File Reference
load_amber_prmtop.c File Reference
#include "AMBER/amber_prmtop.h"
Functions
assembly load_amber_prmtop (fileset F)
Function Documentation
assembly load_amber_prmtop (fileset F)
Definition at line 7 of file load_amber_prmtop.c.
References amber_prmtop_init(), parse_amber_prmtop(), and read_amber_prmtop_asis().
{
amber_prmtop *P;
assembly A;
// initialize the amber prmtop info
P=(amber_prmtop *)calloc(1,sizeof(amber_prmtop));
amber_prmtop_init(P);
// load info as-is into sections
read_amber_prmtop_asis(F,P);
// parse sections into a glylib assembly structure
A=parse_amber_prmtop(P);
return A;
}