GLYLIB: get_rms_alt_X.c File Reference
get_rms_alt_X.c File Reference
#include <mylib.h>
#include <molecules.h>
Functions
double get_alt_rms_res (residue *r, int xs, int xt)
double get_alt_rms_mol (molecule *m, int xs, int xt)
Function Documentation
double get_alt_rms_mol (molecule * m, int xs, int xt)
Definition at line 38 of file get_rms_alt_X.c.
References coord_3D::i, coord_3D::j, coord_3D::k, mywhine(), residue::na, molecule::nr, molecule::r, and subtract_coord().
{
int ai=0,ri=0,nat=0;
double RMS=0;
coord_3D c;
if(xt<0){mywhine("get_alt_rms_mol: target coord cannot be main set");}
if(xs<0){mywhine("get_alt_rms_mol: main set source coords not written yet");}
for(ri=0;ri<m[0].nr;ri++){
        nat+=m[0].r[ri].na;
        for(ai=0;ai<m[0].r[ri].na;ai++){
                c=subtract_coord(m[0].r[ri].a[ai].xa[xs],m[0].r[ri].a[ai].xa[xt]);
                RMS+=c.i*c.i+c.j*c.j+c.k*c.k;
        }}
RMS/=nat;
RMS=sqrt(RMS);
return RMS;
}
double get_alt_rms_res (residue * r, int xs, int xt)
Definition at line 21 of file get_rms_alt_X.c.
References coord_3D::i, coord_3D::j, coord_3D::k, mywhine(), residue::na, and subtract_coord().
{
int ai=0;
double RMS=0;
coord_3D c;
if(xt<0){mywhine("get_alt_rms_res: target coord cannot be main set");}
if(xs<0){mywhine("get_alt_rms_res: main set source coords not written yet");}
for(ai=0;ai<r[0].na;ai++){
        c=subtract_coord(r[0].a[ai].xa[xs],r[0].a[ai].xa[xt]);
        RMS+=c.i*c.i+c.j*c.j+c.k*c.k;
        }
RMS/=r[0].na;
RMS=sqrt(RMS);
return RMS;
}