GLYLIB: src/string_utilities.c File Reference
string_utilities.c File Reference
#include <mylib.h>
Functions
const char * prune_string_whitespace (const char *I)
const char * get_char_string (const char *x, char j, int w)
const char * get_float_string (double x, char j, int w, int d)
const char * get_exp_string (double x, char j, int w, int d)
Detailed Description
Functions for writing variable strings.
Contains utilities that produce numbers in certain formats or that remove initial and trailing whitespace, etc.
Definition in file string_utilities.c.
Function Documentation
const char* get_char_string (const char * x, char j, int w)
Functions that produce variable-format output for numbers and strings.
There must be some already-written way to do this, but I suspect I can write the functions before I can figure that out. So, these functions will generate strings when one does not know ahead of time the output format.
For example:
Assume you know you need to write out a double variable in exponential notation, but that the program will determine the proper number of decimal places and character width. These functions will help.
So, where normally, you might write:
fprintf("%18.8e",x);
that's a right justified exponential, 18 chars wide with 8 decimal places
You can do, instead:
char j,*s;
int w,d;
w = figure_out_width();
d = figure_out_number_decimal_places();
j = figure_out_justification(); // 'L' or 'l' for left, 'R' or 'r' for right
s = strdup(get_exp_string(x,j,w,d));
fprintf("%s",s);
Normally, this is a lot of bother. But, at times, it can be useful.
I'm lazy, so the maximum number of digits that can be printed is about 145. For float values, that number is divided into pre- and post-decimal, which makes for some limits. Hopefully, these limits are generous enough for most applications. This is hard-coded in the number->string functions below. There are much cooler ways to do this, and anyone who wants to code them is very welcome to do so.
If the incoming string (x) is longer than outgoing size (w), write something to stderr and print what fits
< Allocate memory for new string
Definition at line 104 of file string_utilities.c.
References mywhine().
const char* get_exp_string (double x, char j, int w, int d)
Returns a character string corresponding to a exponential notation representation of the number supplied by x. The return string will have a width of w characters, d of which will be integers appearing to the right of the decimal point. The number will be justified as per the character in j (l or L or r or R for left or right).
Definition at line 337 of file string_utilities.c.
const char* get_float_string (double x, char j, int w, int d)
Returns a character string corresponding to a floating point representation of the number supplied by x. The return string will have a width of w characters, d of which will be integers appearing to the right of the decimal point. The number will be justified as per the character in j (l or L or r or R for left or right).
If the incoming string (x) is longer than outgoing size (w), write something to stderr and print what fits
< Allocate memory for new string
Otherwise, print a really wide version of the incoming number to a really wide string Here, the string is 150 chars wide, and 74 of those chars are decimal digits. Another 74 are allocated for the integer part of the float representation. That leaves two spaces, one for a decimal point and another for '-' if needed. At present, this function will not return a '+' sign for positive values.
< 150 wide, minus +/- designation and decimal point and half of that for the fraction
< tst=integer part ; d=fraction part ; 2 = space for . & sign (comes later)
< the starting point in the big number
< Allocate memory for new string
< the ending point in the big number
< check the integer where the null character will finally go
< but only if that won't put us over 150 chars (shouldn't ever happen, really)
< Allocate memory for new string
See if we have a "9X' situation where we have to round up
< Print the first character (space or '-')
< Print a 1 in the next space
For the rest of the string-1, for every 9 add a zero (one space over). Copy any decimals as-is
< Ensure null termination
Increment the "first_not_nine" digit
Change other nines to zeros
< Ensure null termination
< if that situation isn't present
Increment the "end-1" digit
< Ensure null termination
< Ensure termination.
< Allocate memory for new string
< Calculated the padding needed (if any)
Definition at line 150 of file string_utilities.c.
References mywhine().
const char* prune_string_whitespace (const char * I)
Function to prune leading and trailing whitespace from a string
< A counter
< Length (meaning varies)
< Length of incoming string
< Start point for pruned string
< End point for pruned string
< Outgoing string
< Begin at the last character
Definition at line 16 of file string_utilities.c.
Referenced by add_to_moiety_selection(), and get_keysvals_from_slurp().