GLYLIB: inc/declarations.h File Reference
declarations.h File Reference
Defines
#define GLYLIB_DECLARES
Functions
dockinfo * load_dlg_mol (fileset F, types *T)
void load_atypes (fileset FT, types *T)
void findAD3Energies (fileset F, dockinfo *D, int di)
void findAD4Energies (fileset F, dockinfo *D, int di)
Define Documentation
#define GLYLIB_DECLARES
Definition at line 5 of file declarations.h.
Function Documentation
void findAD3Energies (fileset F, dockinfo * D, int di)
Definition at line 291 of file load_dlg_mol.c.
References fileset::F, and line.
Referenced by load_dlg_mol().
void findAD4Energies (fileset F, dockinfo * D, int di)
Definition at line 324 of file load_dlg_mol.c.
References fileset::F, and line.
Referenced by load_dlg_mol().
void load_atypes (fileset FT, types * T)
Definition at line 15 of file load_atypes.c.
References types::a, atype::bo, atype::desc, fileset::F, line, myfreopen(), mywhine(), atype::N, fileset::N, types::na, atype::nb, atype::NT, and read_eek().
dockinfo* load_dlg_mol (fileset F, types * T)
Add BOX information to the molecule structure.
Definition at line 16 of file load_dlg_mol.c.
References residue::a, types::a, molecule::BOX, boxinfo::C, boxinfo::CD, molecule::COM, residue::COM, coord_nD::D, deallocateMolecule(), dXprint_molecule(), dockinfo::eFEB, dockinfo::eKi, fileset::F, dockinfo::fDE, dockinfo::fIE, dockinfo::fIEL, findAD3Energies(), findAD4Energies(), boxinfo::GTYPE, dockinfo::i, coord_3D::i, isolateDockedPDB(), isolateInputPDB(), coord_3D::j, coord_3D::k, fileslurp::L, line, load_pdb_from_slurp(), molecule::m, atype::m, residue::m, dockinfo::M, mywhine(), fileslurp::n, atom::n, dockinfo::n, fileset::N, types::na, residue::na, atom::nalt, molecule::nBOX, boxinfo::nC, boxinfo::nCD, coord_nD::nD, molecule::nr, residue::nrc, molecule::nrc, atype::NT, dockinfo::Q, dockinfo::QN, dockinfo::QN0, molecule::r, dockinfo::RC, residue::rc, molecule::rc, read_eek(), slurp_file(), boxinfo::STYPE, atom::t, dockinfo::TFE, dockinfo::Tmp, dockinfo::TR, dockinfo::USE, atom::x, and atom::xa.