GLYLIB: "File Utilities"
"File Utilities"
Classes
struct fileset
struct fileslurp
A structure for a function similar to the perl notion of "slurping" a file.
Functions
FILE * myfopen (const char *Name, const char *option)
Opens a file with error checking.
FILE * myfreopen (const char *Name, const char *, FILE *option)
Like myfopen, but the freopen version.
void read_eek (const char *surprise, const char *FileDesc)
Complains (EEK!!!) if a file read fails.
void read_neek (const char *surprise, int line, int field)
Complains (EEK!!!) if a file read fails.
void read_fneek (const char *surprise, int line, int field, const char *FILENAME)
Complains (EEK!!!) if a file read fails.
int crdsnaps (const char *, const char *, int)
counts snapshots in a crd file
const char * mytime (const char *)
Gets the time in a nice format.
int sscan_file (FILE *F, const char *str)
Scans a file for instances of a string.
int cscan_file (FILE *F, char c)
Scans a file for instances of a character.
fileslurp slurp_file (fileset F)
Slurps in the contents of an entire file.
Detailed Description
Function Documentation
int crdsnaps (const char * , const char * , int)
counts snapshots in a crd file
Makes certain that the number of snapshots read from a crd file makes sense in terms of the given topology file. This declaration should be moved to some other location eventually (not so general -- really just amber).
Definition at line 5 of file crdsnaps.c.
References myfopen(), and mywhine().
{
int csa=0,csnat=0,csnsnp=0,csstat=0,cssig=0;
char cstst[501];
double csEa=0,csEb=0,csEc=0;
FILE *CST,*CSC;
// Probe top file for number of atoms
CST=myfopen(cstop,"r");
csstat=fscanf(CST,"%s",cstst);
if(csstat!=1) mywhine("Error reading topology file");
//printf("cstst is >>>%s<<<\n",cstst);
while(csstat==1){
        //printf("\t in loop cstst is >>>%s<<<\n",cstst);
        if(strcmp(cstst,"POINTERS")==0){
                csstat=fscanf(CST,"%s",cstst);
//printf("cstst is >>>%s<<<\n",cstst);
                if(csstat!=1) mywhine("Error reading topology file");
                csstat=fscanf(CST,"%d",&csnat);
//printf("csnat is >>>%d<<<\n",csnat);
                if(csstat!=1) mywhine("Error reading number of atoms in topology file.");
                //break;
                }
        if(strcmp(cstst,"BOX_DIMENSIONS")==0) csnat++;
        //if(csnat!=0) break;
        csstat=fscanf(CST,"%s",cstst);
        }
if(csnat==0) mywhine("Got zero for number of atoms.");
//printf("crdsnaps after CST loop\n");
fclose(CST);
//printf("crdsnaps after close CST\n");
// Probe crd file for total number of snapshots
//printf("crdsnaps opening CSC\n");
CSC=myfopen(cscrd,"r");
//printf("crdsnaps fgets CSC\n");
fgets(cstst,201,CSC);
//printf("cstst is >>>%s<<<\n",cstst);
if(cstst==NULL) mywhine("Error reading coordinate file.");
//if(strlen(cstst)==0) mywhine("Error reading coordinate file.");
//printf("cstst about to fscanf \n");
csstat=fscanf(CSC,"%lf %lf %lf",&csEa,&csEb,&csEc);;
//printf("cstst after fscanf  csstat is >>>%d<<<\n",csstat);
// START HERE -- fix this for loop structure
printf(" ");
while(csstat==3){
        csa=1;
        while(csa<csnat){
                csstat=fscanf(CSC,"%lf %lf %lf",&csEa,&csEb,&csEc);
//printf("csa is %d; csnat is %d, csstat is %d\n",csa,csnat,csstat);
                if(csstat!=3) break;
                csa++;
                //switch(cssig){
                        //case 0:       printf("\b-");
                                //cssig=1;
                                //break;
                        //case 1:       printf("\b\\");
                                //cssig=2;
                                //break;
                        //case 2:       printf("\b|");
                                //cssig=3;
                                //break;
                        //case 3:       printf("\b/");
                                //cssig=0;
                                //break;
                        //default: mywhine("something wrong in cssig in crdsnaps.c");
                        //}
                }
        if(csa==csnat){csnsnp++;}
        else if (csa!=1){mywhine("Mismatch between NATOMs in top and crd files.\n\
\tPerhaps there is a mismatch between BOX info in crd and top."); }
//printf("csa is %d; csnat is %d; csnsnp is %d\n",csa,csnat,csnsnp);
        csstat=fscanf(CSC,"%lf %lf %lf",&csEa,&csEb,&csEc);
        if((csnsnp%csdot)==0){printf("%d  ",csnsnp);}
        switch(cssig){
                case 0: printf("\b-");
                        cssig=1;
                        break;
                case 1: printf("\b\\");
                        cssig=2;
                        break;
                case 2: printf("\b|");
                        cssig=3;
                        break;
                case 3: printf("\b/");
                        cssig=0;
                        break;
                default: mywhine("something wrong in cssig in crdsnaps.c");
                }
//printf("csstat is %d\n",csstat);
        }
printf("\n");
return csnsnp;
}
int cscan_file (FILE * F, char c)
Scans a file for instances of a character.
Returns the number of times the character c is found in file F
Definition at line 25 of file scan_file.c.
{
int cfr=0;
char cfck=0;
cfck=fgetc(FC);
while (cfck!=EOF) {
        if(cfck==c){cfr++;}
        cfck=fgetc(FC);
        }
rewind(FC);
return cfr;
}
FILE* myfopen (const char * Name, const char * option)
Opens a file with error checking.
Opens a file with error checking. This function will open a file and then check to see if the file actually opened. If not, it will write a descriptive error message and exit(1) the program. Doing this saves many, many core dumps.
Definition at line 6 of file myfopen.c.
Referenced by crdsnaps(), load_pdb(), outputAsmblPDB(), outputMolPDB(), parse_amber_prmtop(), read_amber_prmtop_asis(), slurp_file(), and write_amber_prmtop().
{
FILE *MYFP;
MYFP=fopen(myfilename,myopentype);
if(MYFP==NULL){
        printf("Error opening file.\n");
        printf("Expected location is:\n\n");
        printf("\t%s\n\n",myfilename);
        printf("Attempted file open for %s\n",myopentype);
        printf("Exiting.\n");
        exit(1);
        }
return MYFP;
}
FILE* myfreopen (const char * Name, const char * , FILE * option)
Like myfopen, but the freopen version.
Like myfopen, but the freopen version.
Definition at line 25 of file myfopen.c.
Referenced by load_atypes(), read_amber8_mden(), and read_prep().
{
FILE *MYFP;
MYFP=freopen(myfilename,myopentype,alreadyopen);
if(MYFP==NULL){
        printf("Error opening file.\n");
        printf("Expected location is:\n\n");
        printf("\t%s\n\n",myfilename);
        printf("Attempted file open for %s\n",myopentype);
        printf("Exiting.\n");
        exit(1);
        }
return MYFP;
}
const char* mytime (const char *)
Gets the time in a nice format.
Usage:
const char * mylocaltimestring,mytime(format)
-for example:
strcpy(mylocaltimestring,mytime("format"));
where:
format is one of:
[keyword] [example]
YYYYMMDD 20070321
YYYYMMDDhhmmss 20070321152110
pretty Wed, 21 March, 2007
longpretty 15:12:10, Wed, 21 March, 2007
Definition at line 17 of file mytime.c.
References DATE, and mywhine().
{
char timestring[1001],month[101],day[101];
 char* tm;
int DATE;
struct tm TM;
time_t LT;
// Get date
LT = time(NULL);
TM = *localtime(&LT);
switch(TM.tm_mon){
        case 0:         strcpy(month,"January");
                        break;
        case 1:         strcpy(month,"February");
                        break;
        case 2:         strcpy(month,"March");
                        break;
        case 3:         strcpy(month,"April");
                        break;
        case 4:         strcpy(month,"May");
                        break;
        case 5:         strcpy(month,"June");
                        break;
        case 6:         strcpy(month,"July");
                        break;
        case 7:         strcpy(month,"August");
                        break;
        case 8:         strcpy(month,"September");
                        break;
        case 9:         strcpy(month,"October");
                        break;
        case 10:        strcpy(month,"November");
                        break;
        case 11:        strcpy(month,"December");
                        break;
        default:        mywhine("Error assigning month in mytime.c");
        }
switch(TM.tm_wday){
        case 0:         strcpy(day,"Monday");
                        break;
        case 1:         strcpy(day,"Tuesday");
                        break;
        case 2:         strcpy(day,"Wednesday");
                        break;
        case 3:         strcpy(day,"Thursday");
                        break;
        case 4:         strcpy(day,"Friday");
                        break;
        case 5:         strcpy(day,"Saturday");
                        break;
        case 6:         strcpy(day,"Sunday");
                        break;
        default:        mywhine("Error assigning week day in mytime.c");
        }
if(strcmp(timehow,"YYYYMMDD")==0){
//      YYYYMMDD        20070321
        DATE=19000000 + TM.tm_year*10000 + (TM.tm_mon+1)*100 + TM.tm_mday;
        sprintf(timestring,"%d",DATE);
        }
if(strcmp(timehow,"YYYYMMDDhhmmss")==0){
//      YYYYMMDDhhmmss  20070321152110
        DATE=190000 + TM.tm_year*100 + (TM.tm_mon+1);
        sprintf(timestring,"%d",DATE);
        DATE=TM.tm_mday*1000000 + 10000*TM.tm_hour + 100*TM.tm_min + TM.tm_sec;
        sprintf(timestring,"%s%d",timestring,DATE);
        }
if(strcmp(timehow,"pretty")==0){
//      pretty          Wednesday, 21 March, 2007
        DATE=1900+TM.tm_year;
        sprintf(timestring,"%s, %d %s, %d",day,TM.tm_mday,month,DATE);
        }
if(strcmp(timehow,"longpretty")==0){
//      longpretty      15:12:10, Wednesday, 21 March, 2007
        DATE=1900+TM.tm_year;
        sprintf(timestring,"%02d:%02d:%02d, %s, %d %s, %d",TM.tm_hour,TM.tm_min,\
TM.tm_sec,day,TM.tm_mday,month,DATE);
        }
 tm = timestring;
return tm;
}
void read_eek (const char * surprise, const char * FileDesc)
Complains (EEK!!!) if a file read fails.
Complains (EEK!!!) if a file read fails. Prints the following: "
Unexpected surprise during read of file FileDesc.
Exiting.
"
Definition at line 6 of file read_eek.c.
Referenced by load_atypes(), load_dlg_mol(), read_amber_prmtop_asis(), and read_prepres().
{
printf("Unexpected %s during read of file: %s\n",EEK,fdesc);
printf("Exiting.\n");
exit(1);
return;
}
void read_fneek (const char * surprise, int line, int field, const char * FILENAME)
Complains (EEK!!!) if a file read fails.
Complains (EEK!!!) if a file read fails.
Definition at line 18 of file read_neek.c.
Referenced by read_amber_prmtop_asis().
{
printf("Unexpected: %s \n\treading line %d at field %d\n\tfile:%s\n",
        NEEK,x,y,FILENAME);
printf("Exiting.\n");
exit(1);
return;
}
void read_neek (const char * surprise, int line, int field)
Complains (EEK!!!) if a file read fails.
Complains (EEK!!!) if a file read fails. Prints the following: "
"
Definition at line 7 of file read_neek.c.
Referenced by rwm_line().
{
printf("Unexpected %s when reading line %d at field f[%d]\n",
        NEEK,x,y);
printf("Exiting.\n");
exit(1);
return;
}
fileslurp slurp_file (fileset F)
Slurps in the contents of an entire file.
Definition at line 19 of file fileslurp.c.
References fileset::F, fileslurp::L, line, myfopen(), fileslurp::n, and fileset::N.
{
fileslurp S;
char templine[2001],*line;
int doneflag=0;
// fgets each line in the file, place in temporary hold
// issue warning if any line is longer than 2000 chars, but
// finish reading the thing in anyhow.
// open the file
F.F=myfopen(F.N,"r");
// read the file
S.n=0;
S.L=(char**)calloc(1,sizeof(char*));
while(fgets(templine,2000,F.F)!=NULL){
        line=strdup(templine);
        if(strchr(templine,'\n')==NULL){ // got a line over 2000 chars
                fprintf(stderr,"found line over 2000 chars in file ");
                fprintf(stderr,"%s at line %d. reading anyway.\n",F.N,(S.n+1));
                doneflag=1;
                while(doneflag==1){
                        fgets(templine,2000,F.F);
        line=(char*)realloc(line,(strlen(line)+strlen(templine)+1)*sizeof(char));
                        strcat(line,templine);
                        if(strchr(templine,'\n')!=NULL){doneflag=0;}
                        }
                }
        S.n++;
        S.L=(char**)realloc(S.L,S.n*sizeof(char*));
        S.L[S.n-1]=strdup(line);
        } // close the while loop
return S;
}
int sscan_file (FILE * F, const char * str)
Scans a file for instances of a string.
Returns the number of times the string str is found in file F
Definition at line 7 of file scan_file.c.
{
int sfr=0,sfck=1;
char sfs[250];
sfck=fscanf(FS,"%s",sfs);
while (sfck!=EOF) {
        if(strcmp(sfs,s)==0){
                sfr++;
                }
        sfck=fscanf(FS,"%s",sfs);
        }
rewind(FS);
return sfr;
}