GLYLIB: src/read_amber_prmtop.c File Reference
read_amber_prmtop.c File Reference
#include "AMBER/amber_prmtop.h"
Functions
void read_amber_prmtop_asis (fileset F, amber_prmtop *P)
Function Documentation
void read_amber_prmtop_asis (fileset F, amber_prmtop * P)
Definition at line 17 of file read_amber_prmtop.c.
References amber_prmtop_section::D, fileset::F, amber_prmtop::FN, amber_prmtop_section::FORMAT, line, myfopen(), mywhine(), amber_prmtop_section::N, fileset::N, amber_prmtop_section::nc, amber_prmtop::nS, amber_prmtop_section::nt, read_eek(), read_fneek(), amber_prmtop::S, amber_prmtop::SN, and amber_prmtop::VERSION.
Referenced by load_amber_prmtop().