GLYLIB: dXprint_X.c File Reference
dXprint_X.c File Reference
#include <mylib.h>
#include <molecules.h>
Functions
void dXprint_coord_3D (coord_3D *c)
void dXprint_vectormag_3D (vectormag_3D *v)
void dXprint_plane (plane *p)
void dXprint_atype (atype *t, int i)
void dXprint_bond (bond *b)
void dXprint_atom (atom *a, int i)
void dXprint_bondset (bondset *bs, int i)
void dXprint_residue (residue *r, int i)
void dXprint_molecule (molecule *m, int i)
Function Documentation
void dXprint_atom (atom * a, int i)
Definition at line 56 of file dXprint_X.c.
References dXprint_bond(), dXprint_coord_3D(), dXprint_vectormag_3D(), atom::i, coord_3D::j, coord_3D::k, and atom::x.
{
        int pa=0;
        printf("atom \tn=%d ; N=>>%s<< ; t=%d ; nb=%d ; nalt=%d ; nvec=%d\n",a[0].n,a[0].N,\
                a[0].t,a[0].nb,a[0].nalt,a[0].nvec);
        printf("\tcoords x y z \t%20.12f \t%20.12f \t%20.12f\n",a[0].x.i,a[0].x.j,a[0].x.k);
        if(i>0){
                for(pa=0;((pa<i)&&(pa<a[0].nb));pa++){
                        printf("\tbond set %d:  ",pa);
                        dXprint_bond(&(a[0].b[pa]));
                        }
                for(pa=0;((pa<i)&&(pa<a[0].nalt));pa++){
                        printf("\talt coord set %d:  ",pa);
                        dXprint_coord_3D(&(a[0].xa[pa]));
                        }
                for(pa=0;((pa<i)&&(pa<a[0].nvec));pa++){
                        printf("\tset %d:  ",pa);
                        dXprint_vectormag_3D(&(a[0].v[pa]));
                        }
                }
return;
}
void dXprint_atype (atype * t, int i)
Definition at line 38 of file dXprint_X.c.
{
        int pa=0;
        printf("atype \tn=%d ; N=>>%s<< ; NT=>>%s<< ; m=%20.12f ; nb=%d\n",t[0].n,t[0].N,t[0].NT,t[0].m,t[0].nb);
        printf("\tdesc=>>%s<<\n",t[0].desc);
        if(i>0){
                for(pa=0;((pa<i)&&(pa<t[0].nb));pa++){
                        printf("\t%20.12f",t[0].bo[pa]);
                        }
                printf("\n");
                }
return;
}
void dXprint_bond (bond * b)
Definition at line 51 of file dXprint_X.c.
Referenced by dXprint_atom(), and dXprint_bondset().
{
        printf("bond s t o \t%d \t%d \t%20.12f\n",b[0].s,b[0].t,b[0].o);
return;
}
void dXprint_bondset (bondset * bs, int i)
Definition at line 78 of file dXprint_X.c.
References dXprint_bond().
{
        int pa=0;
        printf("bondset contains n=%d bonds\n",bs[0].n);
        if(i>0){
                for(pa=0;((pa<i)&&(pa<bs[0].n));pa++){
                        printf("\tconsec bonds set %d : \t",pa);
                        dXprint_bond(&(bs[0].b[pa]));
                        }
                }
return;
}
void dXprint_coord_3D (coord_3D * c)
Definition at line 23 of file dXprint_X.c.
Referenced by dXprint_atom(), dXprint_residue(), and load_dlg_mol().
{
        printf("coord i j k \t%20.12f \t%20.12f \t%20.12f\n",c[0].i,c[0].j,c[0].k);
return;
}
void dXprint_molecule (molecule * m, int i)
Definition at line 119 of file dXprint_X.c.
References dXprint_residue().
{
        int pa=0;
        printf("molecule \ti=%d ; N=>>%s<< ; nr=%d \n",m[0].i,m[0].N,m[0].nr);
        if(i>0){
                for(pa=0;((pa<i)&&(pa<m[0].nr));pa++){
                        printf("\t\tset %d\n",pa);
                        dXprint_residue(&(m[0].r[pa]),i);
                        }
                }
return;
}
void dXprint_plane (plane * p)
Definition at line 33 of file dXprint_X.c.
Referenced by dXprint_residue().
{
        printf("plane A B C D \t%20.12f \t%20.12f \t%20.12f \t%20.12f\n",p[0].A,p[0].B,p[0].C,p[0].D);
return;
}
void dXprint_residue (residue * r, int i)
Definition at line 90 of file dXprint_X.c.
References dXprint_atom(), dXprint_bondset(), dXprint_coord_3D(), and dXprint_plane().
Referenced by dXprint_molecule().
{
        int pa=0;
        printf("residue \tn=%d ; N=>>%s<< ; na=%d ; nbs=%d ; nr=%d \n",r[0].n,r[0].N,\
                r[0].na,r[0].nbs,r[0].nr);
        if(i>0){
                for(pa=0;((pa<i)&&(pa<r[0].na));pa++){
                        printf("\tatom set %d\n",pa);
                        dXprint_atom(&(r[0].a[pa]),i);
                        }
                for(pa=0;((pa<i)&&(pa<r[0].nbs));pa++){
                        printf("\tconsec. lin, bondset set %d\n",pa);
                        dXprint_bondset(&(r[0].bs[pa]),i);
                        }
                for(pa=0;((pa<i)&&(pa<r[0].nrbs));pa++){
                        printf("\tconsec. ring bondset set %d\n",pa);
                        dXprint_bondset(&(r[0].rbs[pa]),i);
                        }
                for(pa=0;((pa<i)&&(pa<r[0].nrc));pa++){
                        printf("\tconsec ring coords set %d:  ",pa);
                        dXprint_coord_3D(&(r[0].rc[pa]));
                        }
                for(pa=0;((pa<i)&&(pa<r[0].nrp));pa++){
                        printf("\tring plane set %d:  ",pa);
                        dXprint_plane(&(r[0].rp[pa]));
                        }
                }
return;
}
void dXprint_vectormag_3D (vectormag_3D * v)
Definition at line 28 of file dXprint_X.c.
{
        printf("vectormag i j k d \t%20.12f \t%20.12f \t%20.12f \t%20.12f\n",v[0].i,v[0].j,v[0].k,v[0].d);
return;
}